### ISSUE TITLE
Cmake fails to build forge

### ISSUE THREAD

**Issue by Keno** [arrayfire/arrayfire#719] opened 2015-05-28 01:34 UTC
Hi there,

I'm trying to build arrayfire and the make command failed with:

```
[  0%] No configure step for 'forge-ext'
CMake Error: The source directory "/Users/kfischer/.julia/ArrayFire/deps/src/arrayfire/third_party/forge/src/forge-ext-build/<SOURCE_DIR>" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make[2]: *** [third_party/forge/src/forge-ext-stamp/forge-ext-configure] Error 1
make[1]: *** [CMakeFiles/forge-ext.dir/all] Error 2
make: *** [all] Error 2
```

Any ideas?

**Comment by shehzan10** [comment] 2015-05-28 01:43
Can you tell me which version of CMake you are using?
And try by changing these lines in CMakeModules/build_forge.cmake
```
CONFIGURE_COMMAND ${CMAKE_COMMAND} -Wno-dev "-G${CMAKE_GENERATOR}" <SOURCE_DIR>
-DCMAKE_SOURCE_DIR:PATH=<SOURCE_DIR>
```
to 
```
CONFIGURE_COMMAND ${CMAKE_COMMAND} -Wno-dev "-G${CMAKE_GENERATOR}" ${prefix}/src/forge-ext
-DCMAKE_SOURCE_DIR:PATH=${prefix}/src/forge-ext
```

**Comment by Keno** [comment] 2015-05-28 01:47
Yep, that worked.

**Comment by Keno** [comment] 2015-05-28 01:48
I was just using `cmake -DGLFW_LIBRARY=~/.julia/GLFW/deps/usr/lib/libglfw.dylib -DGLFW_INCLUDE_DIR=~/.julia/GLFW/deps/usr/include/`. I also tried using Ninja, but that failed for other reasons, so I decided to try makefiles first.

**Comment by Keno** [comment] 2015-05-28 01:50
Also
```
> cmake --version
cmake version 3.2.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by pavanky** [comment] 2015-05-29 14:12
@shehzan10 Can this issue be marked as resolved or do we need to fix something on our end ?

**Comment by shehzan10** [comment] 2015-05-29 14:42
I'm not sure what the cause of this is. We haven't heard of this problem from any other users. I thought it might be an older CMake version, but that does not seem to be the case.

The solution I gave will fix it. But maybe once we find the cause, the fix would propbably be different.

**Comment by unbornchikken** [comment] 2015-06-02 08:23
I'm also having issue of building forge on Windows. The problem is, it has dependency on freetype2, that forge tries to clone, but it fails with no avail error:

git://git.sv.nongnu.org/freetype/freetype2.git

I have to manually change repo url to:

http://git.savannah.gnu.org/cgit/freetype/freetype2.git

in `build\third_party\forge\src\forge-ext\CMakeModules\build_freetype.cmake` after configure.

**Comment by shehzan10** [comment] 2015-06-02 13:20
Thanks for reporting this. We'll make the changes in forge.

**Comment by shehzan10** [comment] 2015-06-02 13:43
This has been fixed in forge. Can you delete the third_party directory and try again.

**Comment by unbornchikken** [comment] 2015-06-02 13:56
It works at my side on Windows, thanks.

**Comment by shehzan10** [comment] 2015-06-02 13:57
Great. I'm closing this issue. @Keno if the problem persists, please reopen this.

**Closed by shehzan10** 2015-06-02 13:58 UTC
