### ISSUE TITLE
Can I give a  implement to 2D matrix with specified axis(0 or 1)

### ISSUE THREAD

**Issue by xichaoqiang** [arrayfire/arrayfire#2844] opened 2020-04-15 11:49 UTC
I have a 2d matirx. And I want implemet fft to each coloumn of it.
How can I do ?

**Comment by 9prady9** [comment] 2020-04-15 11:52
[fft](http://arrayfire.org/docs/group__signal__func__fft.htm#ga8b445e474508d96da691a9608dec5403) shuld be able to handle a bunch of vectors.

`fft(in)`

**Comment by xichaoqiang** [comment] 2020-04-15 12:00
Thanks for your reply.

**Comment by umar456** [comment] 2020-04-15 13:03
These types of questions should be directed to our Slack channel or google groups. Closing this because this is not a bug in ArrayFire.

**Closed by umar456** 2020-04-15 13:03 UTC
