### ISSUE TITLE
af::gaussianKernel is extremely slow (10ms to calculate 3 floats)

### ISSUE THREAD

**Issue by rggjan** [arrayfire/arrayfire#1118] opened 2015-11-24 09:01 UTC
I'm just optimizing my application, and found one bottleneck is the af::gaussianKernel function that I execute once per frame (since the kernel size could potentially change).

Running this line:

    af_print(af::gaussianKernel(3, 1, 2));

outputs:

    [3 1 1 1]
    0.3192 
    0.3617 
    0.3192 

The execution time for this is between 10ms and 11ms on the Cuda backend (ArrayFire 3.2.0) with a Nvidia GeForce GTX 980 graphics card.

I know I could cache the values, but this cannot possibly take longer than a milisecond, there has to be some severe performance issue here.

Or am I missing something?

**Comment by pavanky** [comment] 2015-11-24 12:53
@rggjan How are you timing this ? Can you run the same thing multiple times and see what you are getting ?

**Comment by rggjan** [comment] 2015-11-24 14:15
This is within a larger arrayfire application. When I run it multiple times, I always get around 10 or 11 miliseconds, with little variance. It is timed using std::chrono::high_resolution_clock.

However, I just wrote a small standalone application to test this, and here it doesn't seem to be happening:

    #include <arrayfire.h>

    #include <chrono>

    int64_t GetTime() {
      using namespace std::chrono;
      auto now = high_resolution_clock::now();
      return duration_cast<nanoseconds>(now.time_since_epoch()).count();
    }

    int main(int argc, char **argv) {
      af_print(af::gaussianKernel(3, 1, 2));

      auto before = GetTime();
      int num = 100;
      for (int i=0; i<num; i++) {
        af_print(af::gaussianKernel(3, 1, 2));
      }
      auto after = GetTime();
      std::cout << "Time: " << (after - before)/1000./1000./num << "ms" << std::endl;

      return 0;
    }


I get:

```
af::gaussianKernel(3, 1, 2)
[3 1 1 1]
    0.3192 
    0.3617 
    0.3192 

Time: 0.2202ms
```

which is much more reasonable. Could it be that it only happens when the cpu and/or gpu are very busy otherwise?

Still, its strange. I currently have a function that generates and applies that kernel to a 1000x2000 pixel array. Doing multiple convolve2 calls always take around 3ms total, while the two af::gaussianKernel calls that I have take 20ms together. So within my application, making the gaussianKernel a static variable reduces the time for the function from 23 to 3 ms. Too bad this is not so easily reproducable...

**Comment by pavanky** [comment] 2015-11-29 21:19
@rggjan Since arrayfire is asynchronous, if you do not put `af::sync` at the right places, the time taken from the earlier operations is also timed.

Even in this code sample you have here, you are displaying the time taken to generate gaussianKernel as well as copy to host and display them.

I am closing this issue for now unless we can get some reproducible code for this.

**Closed by pavanky** 2015-11-29 21:19 UTC

**Comment by rggjan** [comment] 2015-11-30 08:09
Ok, thanks for looking into it, anyway!

I'll update you if I can find a more reproducible sample...
