### ISSUE TITLE
af::end-1 throws an exception (AF_ERROR 12) - Update: AF_ERROR 7 with the bug fix

### ISSUE THREAD

**Issue by Kerkil** [arrayfire/arrayfire#343] opened 2015-01-15 23:28 UTC
This code 
```
    try{
        af_print(A(af::end-1));
    } catch (af::exception &e){
        std::cout << e.what() << std::endl;
        throw;
    }
```
throws this exception:
```
A(af::end-1) /Users/kerkil/Git/arrayfire/src/api/cpp/array.cpp:206: AF_ERROR 12
Error in /Users/kerkil/Git/arrayfire/src/api/c/dim4.cpp(180):
Sequence out of bounds
libc++abi.dylib: terminating with uncaught exception of type af::exception
The program has unexpectedly finished.
```

Did the behavior/definition `af::end` change from AF2.0 to 3.0?

**Comment by pavanky** [comment] 2015-01-16 05:57
@Kerkil This is now fixed in devel.

**Comment by Kerkil** [comment] 2015-01-16 15:01
@pavanky Thanks!

**Comment by Kerkil** [comment] 2015-01-16 15:47
This time, I get a different exception:
```
A(af::end-1) /Users/kerkil/Git/arrayfire/src/api/cpp/array.cpp:213: AF_ERROR 7
Error in /Users/kerkil/Git/arrayfire/src/api/c/dim4.cpp(186):
Size mismatch between input and output
libc++abi.dylib: terminating with uncaught exception of type af::exception
The program has unexpectedly finished.
```

**Closed** 2015-01-22 20:37 UTC
Labels: bug

**Comment by pavanky** [comment] 2015-01-22 20:39
@Kerkil Hopefully the issue is finally closed ? Can you verify on your end ?

**Comment by Kerkil** [comment] 2015-01-22 22:33
@pavanky Yup. This works beautifully. Very handy tools to have~
Thanks a lot for your guys help!
