### ISSUE TITLE
Unable to use arrayfire on Windows with Intel HD Graphics 620

### ISSUE THREAD

**Issue by kira505** [arrayfire/arrayfire#2041] opened 2018-01-16 10:34 UTC
When i select the intel device and try to set the backend as CPU or OPENCL, It gives the following error. 

ArrayFire Exception (Internal error:998):
In function int __cdecl cuda::DeviceManager::setActiveDevice(int,int)
In file src\backend\cuda\platform.cpp:594
CUDA Error (10): invalid device ordinal

In function void __cdecl af::setDevice(const int)
In file src\api\cpp\device.cpp:92

**Comment by 9prady9** [comment] 2018-01-16 12:55
@kira505 Can you please show how you are doing `set*` calls when you are getting this error.

**Comment by kira505** [comment] 2018-01-17 01:33
When i use unified option the devicecount() returns 1 and hence the error.  where as when i use opencl option through config manager i get devicecount() as 3.

 af::setDevice(1);
af_set_backend(AF_BACKEND_OPENCL);
af::info();

The error comes in when i call af_set_backend() in unified mode. 

I have two gpus(NVIDIA,Intel) on my desktop. So total devices are 3. I am fine to use OPENCL mode. I get speedup on Nvidia GPU but when i run the code on Intel HD 620 using opencl mode it takes too much time. Any particular reason?

**Comment by 9prady9** [comment] 2018-01-17 02:41
@kira505 It seems like you are confused about unified API. Let me clarify it in case you misunderstood the unified API. When you use unified API, you are linking your program against `libaf.dll/lib`(Windows) which lets you choose backend(CPU, CUDA & OpenCL) and select a device among the devices on that chosen backend. Without unified API, you have to link your code against each backend's library every time you change your backend. All backends can't be used simulatenously.

Can you please share a standalone example that can help us reproduce this error.

One general advice, don't mix up C-API (`af_`) with C++ API (`af::*`);

**Comment by kira505** [comment] 2018-01-17 06:49
When using device 1(intel HD graphics card) in opencl model it gets hanged. Why am i not able to use the intel gpu? 

In af_CPU mode does it perform evaluations in SIMD fashion or just sequential?  
[sample.zip](https://github.com/arrayfire/arrayfire/files/1637954/sample.zip)

**Comment by 9prady9** [comment] 2018-01-17 07:10
CPU backend is a 100% sequential execution. 

The sample is one of our examples, `filters.cpp`.  I don't see any `af::setBackend` calls in the sample you shared. Original description says you have getting the following error.

```
ArrayFire Exception (Internal error:998):
In function int __cdecl cuda::DeviceManager::setActiveDevice(int,int)
In file src\backend\cuda\platform.cpp:594
CUDA Error (10): invalid device ordinal
```
I am confused whats the problem here. Has the above issue resolved by itself ? Is the hang a different issue ?

There is a known issue with Intel OpenCL driver on Windows platform where the ArrayFire program seg faults towards end of execution while cleaning up OpenCL resources. We have observed this problem other OpenCL libraries as well, so it is an Intel OpenCL driver issue. 

Does the program ever finish exeuction on Intel device for you ? You can try updating your Intel HD graphics OpenCL driver/runtime, that may resolve the problem if Intel fixed the problem in their drivers. Also, I believe Intel's OpenCL driver for Intel CPU is different from that of their intergrated GPU, so please make sure you are using the right driver.

**Comment by kira505** [comment] 2018-01-17 08:17
My desktop had 2 gpus, when i tried selecting gpu number in unified mode it gave that error. So to reproduce the error you will have to run it on some intel gpu. 

The program does finish execution but takes longer than CPU. I will try to update the driver.

**Comment by 9prady9** [comment] 2018-01-17 08:40
With two devices, valid device ids are `0` and `1`. Can you show me the output of `af::info()` function call . I gave the sample ouput below, my machine has only one device, so it shows only one.
```
ArrayFire v3.6.0 (OpenCL, 64-bit Linux, build 8c04cc15)
[0] NVIDIA: GeForce GTX 1060 3GB, 3012 MB
```
I don't have a Intel integrated GPU readily available for me, so unfortunately I can only guide you through the debugging process at the moment.

*The program does finish execution but takes longer than CPU. I will try to update the driver.*

How are you timing arrayfire code ? If you are not using timeit already, can you please time your arrayfire code using **`timeit`** function described [here](http://arrayfire.org/docs/timing.htm).

**Comment by kira505** [comment] 2018-01-17 10:58
<img width="663" alt="sample" src="https://user-images.githubusercontent.com/35486217/35039269-51dd3904-fbb8-11e7-9016-6b15e38752a8.png">

I am timing it appropriately. But the problem comes with intel hd graphic card. The drivers are also fine but still takes too much time compared to cpu.

**Comment by 9prady9** [comment] 2018-01-22 07:24
@kira505 
I am not sure why intel HD graphics 620 is running slower than CPU. @pavanky Any thoughts ?

Regarding the invalid device error, I haven't been able to reproduce it on my end yet. Can you please share a very simple code stub that reproduces the invalid error you are getting when you use unified API(`af.dll`).  Try to create an example code from scratch with just the lines that are causing problem instead of modifying an existing example. That way, it would be easy to narrow down the issue.

Note: Please make sure you have all required dlls (afcpu, afcuda, afopencl & all dependencies) available via PATH when you use unified API.

**Comment by pavanky** [comment] 2018-01-22 08:20
There's too much going on in this issue. The original issue seems to have stemmed from the fact that the program was being linked with `afcuda` instead of `af`.

I am not sure why the intel gpu is "slow". If it is hanging, it could be because of various reasons. Have you tried running other OpenCL programs on it?

And in the future, please try to create a new ticket for different issues. A single github issue isnt the place to discuss ongoing problems. If you prefer a more direct conversation, don't hesitate to use the chatroom on slack.

**Comment by 9prady9** [comment] 2018-05-08 13:17
@kira505 Since the original issue has been addressed - used wrong library for linking. I am closing this one for now. Feel free to reopen if you are still facing any issue.

Note: ArrayFire 3.6 it out and please do check it out.

**Closed by 9prady9** 2018-05-08 13:17 UTC
