### ISSUE TITLE
[Question] Potential issue with arrayfire/cuda interoperability when using cusolverDn library inside an arrayfire application

### ISSUE THREAD

**Issue by PierreLadis** [arrayfire/arrayfire#3018] opened 2020-09-28 12:45 UTC
Hello,

I'm trying to use the function "cusolverDnSsyevd" of the "cusolverDn" library to perform EVD of a symmetric hermitian matrix inside an arrayfire program.

The code is here, as well as the compilation line I'm using:
https://github.com/PierreLadis/arrayfire_tests/blob/c4cc07830f2a3690837e15c5afb4491100370f06/test_EVCD3.cpp

I tried two different ways:

1). function "evd_interop" (see code by following the link above): I started by following the guidelines for arrayfire/cuda interoperability detailed in the paragraph: "Adding custom CUDA kernels to an existing ArrayFire application". I start by retrieving the id of the cuda stream used by arrayfire and then, I make use of the function "cusolverDnSetStream" to force "cuSolver" to work inside that stream. The cuda part completes normally. 
I get an error when I try to use the results of the cuda function with arrayfire:
"terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):  "

2). function "evd_standalone" (see code): I did a standalone cuda program that does evd. (I checked as a first step that it doesn't contain errors by using it outside arrayfire context in a standalone program compiled without linking to arrayfire). 
It also raises an error (same as before) when I'm trying to use the results from it with arrayfire after the function "evd_standalone" has completed.

I also tried to make cublas matrix multiplication work using the same framework of code for interoperability: it completes without any problem. So the problem seems specific to the use of "cuSolverDn" with arrayfire.

I'm using precompiled binaries of arrayfire 3.7.2 on a linux CentOS machine with 4 GPUs.
Here is the output of af::info():
ArrayFire v3.7.2 (CUDA, 64-bit Linux, build 218dd2c)
Platform: CUDA Runtime 10.0, Driver: 410.79
[0] GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
-1- GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
-2- GeForce GTX 1080 Ti, 11179 MB, CUDA Compute 6.1
-3- GeForce GTX 1080 Ti, 11176 MB, CUDA Compute 6.1

Thank you in advance for considering my request.

**Comment by 9prady9** [comment] 2020-09-28 17:25
Just leaving a note for any future users who might be using CUDA 9 toolkit and face issues with `cusolverDnSsyevd` function with diagonal matrices: Apparently it is a bug that is fixed in CUDA 10 and above. Confirmed by NVIDIA here - https://forums.developer.nvidia.com/t/cusolver-work-improperly-with-cusolverdnssyevd/62648

I didn't know this and was wondering why my non-arrayfire snippet was giving nans for simple diagonal matrix :)

**Comment by PierreLadis** [comment] 2020-09-29 08:39
Sorry that you spent time on a CUDA bug ... Indeed I didn't see it appear when using CUDA 10.0, the result is the one expected even for diagonal matrices. I should have been less lazy and use a proper symmetric matrix for the sample :).

**Comment by 9prady9** [comment] 2020-09-29 09:00
That's alright, I was just leaving the note for any other users who might encounter similar issue.

By the way, I upgraded my system to latest CUDA 10 and driver, and I don't see any errors w.r.t this environment using your standalone code snippet even while using arrayfire's function. Given below is the compilation command I used
```bash
~$ g++ test_EVCD3.cpp -o solver.run -I/usr/local/cuda/include -I$AF_PATH/include -L/usr/local/cuda/lib64 -L$AF_PATH/lib -lcusolver -lafcuda -lcudart
```

I have just edited the following section for quick debugging
```c++
#if 1
    af::array D = evd_interop(d, diag_val); // using cuda-arrayfire interoperability
#else
    // computing evd in a standalone way (not using arrayfire in any way)
    float *ptr_D = evd_standalone(d, diag_val);
    printf("\nFirst ten values of eigen vector matrix:\n");
    for (int i=0; i < 10; i++) {
        printf("%f | ", ptr_D[i]);
    }
    printf("\n\n");
    af::array D = af::array(d, ptr_D);
#endif
```

I haven't changed the compilation command for non-arrayfire code path also as you aren't using any RAW CUDA kernels. If your CUDA code just using CUDA libraries directly, you don't need to use nvcc. Using `cudart`, `cusolver` is like any other C/C++ libraries unless RAW kernels are involved.

**Comment by 9prady9** [comment] 2020-09-29 09:01
Do note that this is with library built on my system. I am going to try out with installer binaries soon and will update here again.

**Comment by 9prady9** [comment] 2020-09-29 10:34
@PierreLadis 

I just tried with `evd_interop` code-path using website binaries and still unable to reproduce the problem. The following are the differences between our setups:

- CUDA GPU Compute version: I have 3.0 while yours is 6.1
- Driver Version: I have 450.** while yours has 410.**.

I doubt it could be driver issue, but it is worth checking it out. Can you please update your driver version and check if that changes the outcome. I will try to run the code on different compute GPU to check if that has anything to do with it. Thank you.

**Comment by PierreLadis** [comment] 2020-09-29 11:29
Thank you for your quick answers !
I will try with a more recent CUDA driver as you said. As it depends on the network admin to update the drivers, I won't have the results today, but I'll let you know when it's tested.

By the way, could it be something linked to the multi-GPU setting ?

Otherwise, I tested with an older version of arrayfire (3.6.x), and it completes without error this time. Just a strange CUDA error pops out from time to time which doesn't cause the program to stop: "CUDA Error (9): invalid configuration argument". As if there was something wrong with the parametrisation of "cusolverDnSsyevd". But obviously, there isn't. And this error isn't caught by the "assert" in my code, it's raised somewhere else afterwards.
I have this error as well when using arrayfire 3.7.2. Here is the complete error log I'm obtaining when running the code I posted with both "evd_interop" and "evd_standalone" (the CUDA error seems to be raised when executing the "sum" instruction line 140):
"
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function void cuda::kernel::reduce_first_launcher(cuda::Param<To>, cuda::CParam<Ti>, cuda::uint, cuda::uint, cuda::uint, bool, double) [with Ti = float; To = float; af_op_t op = (af_op_t)0; cuda::uint = unsigned int]
In file src/backend/cuda/kernel/reduce.hpp:298
CUDA Error (9): invalid configuration argument

 0# 0x00007F4BCD845312 in /product/x86_64/local/arrayfire_3.7.2/arrayfire/lib64/libafcuda.so.3
 1# 0x00007F4BCD846382 in /product/x86_64/local/arrayfire_3.7.2/arrayfire/lib64/libafcuda.so.3
 2# 0x00007F4BCD84A751 in /product/x86_64/local/arrayfire_3.7.2/arrayfire/lib64/libafcuda.so.3
 3# 0x00007F4BCEBBB71B in /product/x86_64/local/arrayfire_3.7.2/arrayfire/lib64/libafcuda.so.3
 4# af::sum(af::array const&, int) in /product/x86_64/local/arrayfire_3.7.2/arrayfire/lib64/libafcuda.so.3
 5# 0x0000000000402821 in ./evd3
 6# __libc_start_main in /lib64/libc.so.6
 7# 0x0000000000402A2F in ./evd3

In f
Aborted
"

**Comment by 9prady9** [comment] 2020-09-29 11:47
Can you please try the following in that order, independently.
- Add `cudaSetDevice(cuda_id)` and run the program again.
```
  int cuda_id = afcu::getNativeId(getDevice());
  printf("cuda_id = %d\n", cuda_id);
  cudaStream_t af_cuda_stream = afcu::getStream(cuda_id);
  cudaSetDevice(cuda_id); //
```
- Don't upload the host side array returned by `evd_interop` and just print the first ten values of eigen values and check if the program finishes fine.

Note to not to mix the above two points.

**Comment by PierreLadis** [comment] 2020-09-29 12:15
- Adding cudaSetDevice(cuda_id) in "evd_interop": I get the same error.

- Not uploading the host side array returned by "evd_standalone" and printing the first ten values: the program completes without error and the printed values are as expected.

**Comment by PierreLadis** [comment] 2020-09-29 12:20
Something weird I noticed:
Doing this treatment at the end causes the program to complete without error:
`
float *ptr_D = evd_standalone(d, diag_val); // computing evd in a standalone way (not using arrayfire in any way)
for (int i=0; i < 10; i++) printf("%f | ", ptr_D[i]);
printf("\n");
af::array D = af::array(d, ptr_D);
printf("trace = %f\n", sum<float>(D, 0));
`

But doing this, which should be equivalent, fails:
`
float *ptr_D = evd_standalone(d, diag_val); // computing evd in a standalone way (not using arrayfire in any way)
for (int i=0; i < 10; i++) printf("%f | ", ptr_D[i]);
printf("\n");
af::array af_trace = sum(D, 0); 
float trace_f; af_trace.host(&trace_f);
printf("trace = %f\n", trace_f);
`

**Comment by 9prady9** [comment] 2020-09-29 12:27
If that is the case, then I would guess af_trace isn't actually a scalar. Have you tried printing the dims of `af_trace` in the second case ? Also, is the missing `D` creation in the second code snippet is a copy paste mistake or is there D else where which isn't actually a vector ?

**Comment by PierreLadis** [comment] 2020-09-29 12:53
Yes, sorry, it's a copy paste mistake. I'm creating "D": "af::array D = af::array(d, ptr_D);"
"D" is of size "d", so, "sum(D, 0)" is of size 1. The problem is that the instruction which fails is "sum(D, 0)"; whereas "sum<float>(D, 0);" succeeds. A simple "af_print(D(af::seq(0, 10)));" fails as well. And i guess any function which is doing something with "D" after i created it with "af::array D = af::array(d, ptr_D);".

**Comment by PierreLadis** [comment] 2020-09-29 12:58
I can retrieve the dimension of "D" without raising an error : I just did it. Without suprises, it prints that dimension is "300" (==d).

**Comment by PierreLadis** [comment] 2020-09-29 13:25
In fact, it does not even seem to be linked with the re-use of "D" or not. 
I tried this code:

`
float *ptr_D = evd_standalone(d, diag_val);
printf("Cleaning device\n");
af_device_gc();
printf("Done cleaning device\n");

// not trying to re-use D
af::array temp1 = af::randu(10);
af::array temp2 = af::randu(10);
af::array temp12 = temp1+temp2;
af_print(temp12); // failing with an error here
`

And it fails as well when trying to execute the af_print in the end.
It looks as if arrayfire context got corrupted by the execution of the CUDA part.

**Comment by 9prady9** [comment] 2020-09-29 13:28
Not sure what is going on your end, I am unable to reproduce this on Ubuntu 18.04. Perhaps, it is CentOS specific, I would have to try on it.

What is the error when it fails at `af_print(temp12)` ? Please re-run the program after doing `export AF_TRACE=all && export AF_PRINT_ERRORS=1`.

**Comment by PierreLadis** [comment] 2020-09-29 13:39
Here is the full execution log:

[log.txt](https://github.com/arrayfire/arrayfire/files/5299313/log.txt)

**Comment by PierreLadis** [comment] 2020-09-29 13:54
if it helps, here is a simpler log obtained by just running:

`
float *ptr_D = evd_standalone(d, diag_val);
af::array temp1 = af::randu(10);
af_print(temp1); // failing with an error here
`
which raises the error as well.

[log2.txt](https://github.com/arrayfire/arrayfire/files/5299465/log2.txt)

**Comment by PierreLadis** [comment] 2020-09-29 15:47
Unfortunately, it didn't change by deleting these files (. 
Here is the new log:

[log3.txt](https://github.com/arrayfire/arrayfire/files/5300264/log3.txt)

But the error got this time characterised as an "argument not found" by the Jit when calling the kernel "transpose". Well, that's my interpretation of the log.

**Comment by 9prady9** [comment] 2020-09-29 15:57
Cool, just wanted to rule out that. I shall try to get this tested on different system and a CentOS setup to see if it can reproduced anywhere else - I need some time to get this done.

One final check: Did you try running a ArrayFire helloworld example ? The reason I ask is if any ArrayFire code is giving an issue, then the helloworld should also.

**Comment by PierreLadis** [comment] 2020-09-29 16:17
I have very complex arrayfire applications which run perfectly fine (I just checked again in case something would have changed :)). 
The problem seems specific to this setting when I try to mix cuda functions with arrayfire. 
But as I told you, I tried "gemm" cublas matrix multiplication inside an arrayfire application and had no problem with it. 
Same for RAW kernel using arrayfire/cuda interoperability.
That's why I thought it might be something specific with cuSolverDn.
I noticed an other weird thing: when I use a smaller "d" for the size of the matrix (d=30), the program completes without error ...

**Comment by PierreLadis** [comment] 2020-09-29 16:21
I found the limit to be "d=65". "d=66" is already raising an error.

**Comment by 9prady9** [comment] 2020-09-29 16:25
You can try building master branch of repository to check if you are getting similar error with arrayfire built on your system. You can following instructions from below links to clone and build arrayfire
1. To clone https://github.com/arrayfire/arrayfire/wiki
2. To build CUDA backend 
    - https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#general-dependencies
    - https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux#cuda-backend-dependencies

I assume you have CUDA toolkit already installed, so it shouldn't be hard to build CUDA backend. The only other dependency you would need to install is boost.

**Comment by PierreLadis** [comment] 2020-09-29 16:28
yes, I'll try to do this. I'll keep you updated. Many thanks for your patience and your time .

**Comment by 9prady9** [comment] 2020-09-30 05:25
A quick update: my colleague tried on the following setup and both non-arrayfire and arrayfire code-paths worked for him as well.
```
ArrayFire v3.7.2 (CUDA, 64-bit Linux, build 218dd2c)
Platform: CUDA Runtime 10.0, Driver: 450.66
[0] GeForce GTX 1080, 8112 MB, CUDA Compute 6.1
```

He tried with the following combinations and the code worked as expected.
- ArrayFire v3.7.2, CUDA 10
- ArrayFire 3.8 (master branch), CUDA 11

How did your trials go ?
- Updating driver
- Using built arrayfire.

**Comment by 9prady9** [comment] 2020-10-01 02:28
@PierreLadis What is the CentOS version you are using ?

**Comment by PierreLadis** [comment] 2020-10-01 09:21
Here is the version info: CentOS Linux release 7.6.1810 (Core).
I'll tell you later about the trials (updating driver + building arrayfire from source). I don't have the admin rights on the GPU server I'm using, so I have to wait for the network admin to do it.

**Comment by 9prady9** [comment] 2020-10-01 09:31
Ok, take your time. I shall update here once I test it out on Centos - I am going to try via docker so I should be able to give you a Dockerfile for further trials if you have docker access.

**Comment by 9prady9** [comment] 2020-10-01 13:44
I have been unable to reproduce this on centos 7 docker image as well. I am out of ideas at the moment. @umar456 Anything else you want to try ? Have a look at earlier comments what we have tried already.

@PierreLadis 
Used this nvidia docker image `nvidia/cuda:10.2-devel-centos7` as base image as it provides the required CUDA toolkit.

I only had to have [`nvidia-container runtime`](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html)  enabled for launching the container. Once running, I installed devtoolset 7, git, cmake, make and boost 1.74 on the centos container to build the code snippet using 3.7.2 binary and CUDA toolkit.

I have placed the code snippet you shared in my [fork's](https://github.com/9prady9/arrayfire) branch [issue3018](https://github.com/9prady9/arrayfire/blob/issue3018/examples/helloworld/test_EVCD3.cpp). You can clone this repo to use this or ADD your local file from the container. ADDing the file is easier, I just had it on branch as I was testing on different machines.

**Comment by 9prady9** [comment] 2020-10-20 09:46
@PierreLadis Any update on your side ?

**Comment by 9prady9** [comment] 2020-12-08 09:54
Closing due to inactivity. @PierreLadis In case you have any new insights or feedback to share, please do.

Feel free to reopen if the issue persists on your end, it would be nice if you can reproduce the problem in a docker image so that we can reliably debug and test the problem scenario.

If you have found a solution, please share your what you did to resolve it. Thank you.

**Closed by 9prady9** 2020-12-08 09:54 UTC
Labels: question
