### ISSUE TITLE
matmul and reduce over huge tensors

### ISSUE THREAD

**Issue by gonzaloiglesiasiglesias** [arrayfire/arrayfire#2446] opened 2019-02-26 10:52 UTC
Hi,
Let's say that we have these two tensors
A: 64000 x 10 x 100
B: 10 x 512 x 100

C= af::matmul(A,B) has size 64000 x 512 x 100.
In my application, this matmul is in many cases followed by summing all slices together, which of course returns a matrix D of dimensions 64000 x 512.
To avoid OOM issues due to matmul I'm currently looping through the slices of A, B to run
matmul operations and accumulate into D on the fly.   Is there a more efficient way?

Thanks!

**Comment by umar456** [comment] 2019-03-02 05:13
Instead of doing the batches individually. You can work on a larger batch size. For example instead of performing 100 matmuls you can do smaller batch operations over 20 or so.

We have some ideas to perform this operation on pre-allocated memory so you would place the results directly into the memory space. It's not implemented yet and I don't think it will be in the upcoming release but should be in the one after.

**Comment by WilliamTambellini** [comment] 2019-03-11 23:05
Hi @umar456 
Outputing to a preallocated space would nt resolve that issue : the issue here is that a giant tensor is allocated in order to store the full matmul output (100 slices) before reducing it (sum on the 3rd dim). 
The title of that item should consequently better be "matmul and reduce" : in that case, there is no need to store the full matmul output tensor, reducing/accumulating on the fly slice after slice should do a better job and save tons of memory.    
I m wondering if simply using cublasSgemmStridedBatched() and setting "strideC" to 0 would nt do the job :
https://docs.nvidia.com/cuda/cublas/#cublas-lt-t-gt-gemmstridedbatched
?

**Comment by WilliamTambellini** [comment] 2019-03-25 21:48
Ok some good news :  using the beta param as documented there 
https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemm

 C = α op ( A ) op ( B ) + β C 

does allow to accumulate the output to a single 2d output matrix :   

A=
0 1 
1 2 
2 3 
 0  1 
 1  2 
 2  3 
B=
0 1 2 
1 2 3 
 0  1  2 
 1  2  3 

SerializedGemm: A=3 2 2  B=2 3 2  C=3 3  beta=0
C=
1 2 3 
2 5 8 
3 8 13 

SerializedGemm: A=3 2 2  B=2 3 2  C=3 3  beta=1
C=
2 4 6 
4 10 16 
6 16 26 


So if I m correct all we need is to be able to set the value of beta.
Today it seems to be hard coded to 0 : 
https://github.com/arrayfire/arrayfire/blob/496d11102fb38bac0494febd2996e01762dae640/src/backend/cuda/blas.cpp#L177
 T beta = scalar<T>(0);

and dont see a beta option in af::matmul() API : 
http://arrayfire.org/docs/group__blas__func__matmul.htm

TBC

**Comment by WilliamTambellini** [comment] 2019-03-25 21:59
Considering the table on : 
http://arrayfire.org/docs/group__blas__func__matmul.htm
it would also mean to offer a third batched matmul type :
A = M K b2
B = K N b2
Output to be just 2d : M N

I see 2 needed API changes :  first adding the alpha&beta params to matmul as new optional args : 

af::matmul(const array &lhs, const array &rhs, 
 const matProp optLhs = AF_MAT_NONE, const matProp optRhs = AF_MAT_NONE,
 const float alpha = 1, const float beta = 0)  

but secondly we would need another param for the user to specify if he d like do : 
- a normal batched matmul : 3d * 3d to 3d
- an (potentially accumulated, beta=1) reduced batched matmul : 3d * 3d to 2d

@9prady9 which API would you recommend ?

**Comment by 9prady9** [comment] 2019-03-26 09:22
Adding GEMM equation for reference:
```
 C = α op ( A ) op ( B ) + β C 
```

I think the requested operation can be done using existing functionality. For any non-zero value of β , the code will look like the following:
```c++
af::array A = af::randu(M, K, b2, b3);
af::array B = af::randu(K, N, b2, b3);
af::array C = beta * matmul(A, B);
af::array sumC = sum(moddims(C, dim4(M, N, b2*b3)), 2);
```
Batched implementations of upstream libraries(I have checked cuBLAS) expect separate C for each input of the batched data. Therefore, I don't think this should be treated as extension of existing BLAS functionality.

Even if the beta is different for each set of matrices in the batch, the operation can still be done with some minor changes to the above code.
```c++
af::array A = af::randu(M, K, b2, b3);
af::array B = af::randu(K, N, b2, b3);
af::array betas(dim4(1, 1, b2, b3), hostBetas); //upload all constants to device memory
betas = tile(betas, M, N); // transforms into [M N b2 b3] array
af::array C = betas * matmul(A, B); //element wise multiplication of [M N b2 b3] arrays
af::array sumC = sum(moddims(C, dim4(M, N, b2*b3)), 2);
```
In my opinion, even if a new function is added to do the above operation, it would be convenience wrapper for the same set of operations shown above at C++ API level.

@umar456 What do you think ?

**Comment by 9prady9** [comment] 2019-03-26 15:05
@WilliamTambellini I just noticed that original description about space issues. Although what I said works as an algorithm, it consumes quite an additional amount of space - I was replying to the comment where I was referred to. Sorry about that.

We are working on altering the C-API to accept pre-allocated af_array as output af_array handle for `af_matmul`. Once that is implemented, we will add a new function that accumulates a batch of matrix multiplications without allocating additional memory. That new function should be able to address this issue.

What you suggested(given below) should work fine for the new API
```c++
af::array af::accumMatmul(const array &lhs, const array &rhs,
const matProp optLhs = AF_MAT_NONE, const matProp optRhs = AF_MAT_NONE,
const float alpha = 1, const float beta = 0);
```

What is this case - `a normal batched matmul : 3d * 3d to 3d` ? Can you please elaborate this case.

**Comment by WilliamTambellini** [comment] 2019-03-26 17:31
Hi @9prady9  
Yes please keep in mind the main request here is to do fast matmul over very deep tensors (hundreds of slices) without needing much mem because the output would just be accumulated into a 2d tensor.
A new accumMatmul(...) would for sure do the job.
What I called a normal batched matmul is a matmul preserving rank between inputs and output : matmul(3d, 3d) to output a 3d tensor. Here we are speaking about a reduction : matmul(3d, 3d) to output a 2d tensor (the same for 4d inputs to be reduced to 2d). 

Now speaking about perf, I have tried to use the batched cublas gemm and indeed looks like it s not possible to compute all slices to the same output C. 
Would it mean that the implementation would need to do a for loop on the 3rd dim and call a regular gemm slice after slice ?

**Comment by 9prady9** [comment] 2019-03-27 08:26
@WilliamTambellini Yes, that is correct. The user has to loop over the batched data accumulating the result. 

However, following @umar456 first advice, the user can go for a hybrid approach: Divide original batch size into smaller batch size, that can fit in given memory. For each smaller batch, run 3rd dimension reduction I posted earlier and accumulate into a final C. Whats the smaller batch size has to based on some runtime metrics I think rather than having a fixed value.

**Comment by WilliamTambellini** [comment] 2019-04-01 21:27
Ok tks. As a baseline, before trying to optimize, here is  a dummy for loop : 

    const unsigned ns = left.dims(2);
    assert(left.dims(2) == rigth.dims(2));
    for (unsigned z = 0; z < ns; ++z) {
      o += af::matmul(left.slice(z), right.slice(z), transposeLeft ? AF_MAT_TRANS : AF_MAT_NONE, transposeRight ? AF_MAT_TRANS : AF_MAT_NONE);
    }

Is it at least a correct/licit implementation ?
Tks

**Comment by 9prady9** [comment] 2019-04-02 05:53
Yes, you can even move the calculation of `AF_MAT_TRANS` outside the loop - two less branching statements inside the loop.

**Comment by 9prady9** [comment] 2019-04-02 09:44
I forgot to mention one more item, in the above basic for loop, `af::matmul` call is going to allocate memory at least once. Since each slices memory is going to be same, memory manager should be able to re-use for all iterations.

**Comment by 9prady9** [comment] 2019-04-02 10:03
I am not sure if it is a leak as you mentioned in #2478 but I did find out the reason behind increasing buffer count.  It is because `+=` operator. I am looking into it further.

**Comment by WilliamTambellini** [comment] 2019-04-03 00:48
> I forgot to mention one more item, in the above basic for loop, `af::matmul` call is going to allocate memory at least three buffers size of `M*N`: output, input slices . Since each slices memory is going to be same, memory manager should be able to re-use it for all iterations.

That is not good : input tensors (ie M & N) could be pretty big. 
The output tensor is 2d so it should be acceptable to allocate mem for it specially is empty but why would af allocate memory for input slices whereas the input datas are already in memory ?
Tks

**Comment by 9prady9** [comment] 2019-04-03 02:02
> That is not good : input tensors (ie M & N) could be pretty big.
> The output tensor is 2d so it should be acceptable to allocate mem for it specially is empty but why would af allocate memory for input slices whereas the input datas are already in memory ?

I have correction in my [one of my earlier comment](https://github.com/arrayfire/arrayfire/issues/2446#issuecomment-478923096). I can confirm now that there is only one allocation happening on each iteration of the loop - output memory allocation i.e. size of M*N . I was confused by the fact that output allocation wasn't being reused in subsequent iterations. Coming to the point of increasing buffers, it is because reuse of output allocation wasn't happening. The reason output reallocation wasn't happening is because of `+=` operation creates a jit node that keeps a reference to the output memory allocation of matmul operation. Hence, until the criteria for automatic evaluation happens, new buffers are allocated. Once automatic evaluation is triggered, buffer count will drop down again.

So, there is no memory leak #2478 as we were worried about. It is a side-effect of `+=` and jit.

In light of these increasing buffers, it may be useful to run eval on `output` once in few iterations. Something like the following
```cpp
 for (unsigned z = 0; z < ns; ++z) {
    o +=  af::matmul(left.slice(z), right.slice(z), l, r);
    if (z % 10 == 0) { // choose this condition based on the application
      o.eval();
    }
}

```

**Comment by umar456** [comment] 2019-06-20 02:03
This can be done with the addition of the #2481 PR and the af_gemm function. You can use the following code to matmul and reduce the large tensor without allocating too much memory:

```c++
    // Preallocate output matrix
    array C = constant(0, dim4(aDims[0], bDims[1])); 
    af_array a = A.get();
    af_array b = B.get();
    af_array c = C.get();

    float alpha = 1.0f;
    float beta = 1.0f;
    int batch_size = aDims[0];
     for(int i = 0; i < batch_size; i++) {
        af_seq slice[] = {af_span, af_span, {static_cast<double>(i), static_cast<double>(i), 1.}};
        af_array asub, bsub;
        af_index(&asub, a, 3, slice);
        af_index(&bsub, b, 3, slice);
        af_gemm(&c, AF_MAT_NONE, AF_MAT_NONE, &alpha, asub, bsub, &beta);
        af_release_array(asub);
        af_release_array(bsub);
      }
```

There is no equivalent why of doing this with the C++ API so you will have to use the C function.

**Closed by umar456** 2019-06-20 02:03 UTC
