### ISSUE TITLE
The problem of array index

### ISSUE THREAD

**Issue by xingchenp** [arrayfire/arrayfire#280] opened 2014-12-30 05:57 UTC
if array index indices the elements bigger than 0.1 in the array a and I want to change the corresponding elements to 0, such as:

        array a = randu(10, 10);
	array index = a > 0.1;
	a(index) = 0;

it will not work because array() doesn't accept argument type of array, if there is candidate to solve this problem？

**Comment by pavanky** [comment] 2015-01-04 04:27
I am closing this as a duplicate of #245

**Closed by pavanky** 2015-01-04 04:27 UTC
Labels: feature
