### ISSUE TITLE
Follow-up testing with pocl

### ISSUE THREAD

**Issue by ghisvail** [arrayfire/arrayfire#1575] opened 2016-09-08 10:15 UTC
I followed up on my testing of AF with `pocl` after the initial problems reported in #1553 were fixed (thanks!). I started from afresh with an up-to-date repository and the `pocl` cache completely cleared. Here are the results:

build command: `cmake .. -DBUILD_GRAPHICS=OFF -DBUILD_CUDA=OFF -DBUILD_CPU=OFF -DBUILD_OPENCL=ON -DBUILD_TEST=ON`

test command: `ctest --output-on-failure --force-new-ctest-process  -R opencl -E "large|dense"`

summary:

```
97% tests passed, 3 tests failed out of 100

Total Test time (real) = 2108.71 sec

The following tests FAILED:
      8 - Test_bilateral_opencl (Failed)
     41 - Test_homography_opencl (SEGFAULT)
    101 - Test_transpose_inplace_opencl (SEGFAULT)
```

details:

```
  8/100 Test   #8: Test_bilateral_opencl ...............***Failed    1.94 sec
Running main() from gtest_main.cc
[==========] Running 28 tests from 11 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from BilateralOnImage
[ RUN      ] BilateralOnImage.Grayscale
NRMSD = 5.12807e-39
[       OK ] BilateralOnImage.Grayscale (845 ms)
[ RUN      ] BilateralOnImage.Color
NRMSD = 5.33849e-39
[       OK ] BilateralOnImage.Color (791 ms)
[----------] 2 tests from BilateralOnImage (1636 ms total)

[----------] 3 tests from BilateralOnData/0, where TypeParam = float
[ RUN      ] BilateralOnData/0.Rectangle
NRMSD = 0
[       OK ] BilateralOnData/0.Rectangle (1 ms)
[ RUN      ] BilateralOnData/0.Rectangle_Batch
NRMSD = 0
[       OK ] BilateralOnData/0.Rectangle_Batch (1 ms)
[ RUN      ] BilateralOnData/0.InvalidArgs
[       OK ] BilateralOnData/0.InvalidArgs (0 ms)
[----------] 3 tests from BilateralOnData/0 (2 ms total)

[----------] 3 tests from BilateralOnData/1, where TypeParam = double
[ RUN      ] BilateralOnData/1.Rectangle
/home/ghislain/local/src/arrayfire/build/test/bilateral_opencl: symbol lookup error: /home/ghislain/.cache/pocl/kcache/DP/AOKIFACNCAJCCMAPJHOBPIKGMBEHEAEINEFJB/bilateral/16-16-1/bilateral.so: undefined symbol: _Z14_cl_native_expd
/home/ghislain/local/src/arrayfire/build/test/bilateral_opencl: symbol lookup error: /home/ghislain/.cache/pocl/kcache/DP/AOKIFACNCAJCCMAPJHOBPIKGMBEHEAEINEFJB/bilateral/16-16-1/bilateral.so: undefined symbol: _Z14_cl_native_expd



39/100 Test  #41: Test_homography_opencl ..............***Exception: SegFault  9.12 sec
Running main() from gtest_main.cc
[==========] Running 7 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from Homography/0, where TypeParam = float
[ RUN      ] Homography/0.Tux_RANSAC
1 warning generated.
2 warnings generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
/home/ghislain/local/src/arrayfire/test/homography.cpp:163: Failure
Expected: (fabs(out_t[elIter] - gold_t[elIter]) / tDims[elIter & 1]) <= (0.1f), actual: 0.326523 vs 0.1
at: 0

[  FAILED  ] Homography/0.Tux_RANSAC, where TypeParam = float (5221 ms)
[ RUN      ] Homography/0.Tux_RANSAC_90degrees
/home/ghislain/local/src/arrayfire/test/homography.cpp:163: Failure
Expected: (fabs(out_t[elIter] - gold_t[elIter]) / tDims[elIter & 1]) <= (0.1f), actual: 0.560771 vs 0.1
at: 0

[  FAILED  ] Homography/0.Tux_RANSAC_90degrees, where TypeParam = float (824 ms)
[ RUN      ] Homography/0.Tux_RANSAC_resize
/home/ghislain/local/src/arrayfire/test/homography.cpp:163: Failure
Expected: (fabs(out_t[elIter] - gold_t[elIter]) / tDims[elIter & 1]) <= (0.1f), actual: 0.342227 vs 0.1
at: 0

[  FAILED  ] Homography/0.Tux_RANSAC_resize, where TypeParam = float (570 ms)
[----------] 3 tests from Homography/0 (6615 ms total)

[----------] 3 tests from Homography/1, where TypeParam = double
[ RUN      ] Homography/1.Tux_RANSAC
1 warning generated.



 93/100 Test #101: Test_transpose_inplace_opencl .......***Exception: SegFault  1.09 sec
Running main() from gtest_main.cc
[==========] Running 60 tests from 10 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from Transpose/0, where TypeParam = float
[ RUN      ] Transpose/0.TranposeIP_10
[       OK ] Transpose/0.TranposeIP_10 (718 ms)
[ RUN      ] Transpose/0.TranposeIP_64
[       OK ] Transpose/0.TranposeIP_64 (348 ms)
[ RUN      ] Transpose/0.TranposeIP_300
/home/ghislain/local/src/arrayfire/test/transpose_inplace.cpp:59: Failure
Value of: outData[elIter]
  Actual: 0.859355
Expected: trsData[elIter]
Which is: 5.77769e-36
at: 86700

[  FAILED  ] Transpose/0.TranposeIP_300, where TypeParam = float (3 ms)
[ RUN      ] Transpose/0.TranposeIP_1000

```

clinfo:

```
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 2.0 pocl 0.13, LLVM 3.8.1
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     pthread-Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
  Device Vendor                                   GenuineIntel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 pocl
  Driver Version                                  0.13
  Device OpenCL C Version                         OpenCL C 2.0
  Device Type                                     CPU, Default
  Device Profile                                  FULL_PROFILE
  Max compute units                               4
  Max clock frequency                             3300MHz
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     equally, by counts
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Preferred work group size multiple              8
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 8 / 8        (n/a)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              10424524800 (9.709GiB)
  Error Correction support                        No
  Max memory allocation                           10424524800 (9.709GiB)
  Unified memory for Host and Device              Yes
  Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   Yes
    Fine-grained system sharing                   No
    Atomics                                       Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
  Max size for global variable                    0
  Preferred total size of global vars             0
  Global Memory cache type                        Read/Write
  Global Memory cache size                        32768
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            651532800 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
    Max number of read/write image args           <printDeviceInfo:106: get CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS : error -30>
  Max number of pipe args                         16
  Max active pipe reservations                    1
  Max pipe packet size                            1024
  Local memory type                               Global
  Local memory size                               10424524800 (9.709GiB)
  Max constant buffer size                        10424524800 (9.709GiB)
  Max number of constant args                     8
  Max size of kernel argument                     1024
  Queue properties (on host)                      
    Out-of-order execution                        No
    Profiling                                     Yes
  Queue properties (on device)                    
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Preferred size                                16384 (16KiB)
    Max size                                      262144 (256KiB)
  Max queues on device                            1
  Max events on device                            1024
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir cl_khr_int64 cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [POCL]
  clCreateContext(NULL, ...) [default]            Success [POCL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.9
  ICD loader Profile                              OpenCL 2.1
```

**Comment by pavanky** [comment] 2016-09-08 19:16
@ghisvail 

- bilateral is definitely an implementation bug. We can incorporate a work around for pocl for now.
- we have not touched `transpose_inplace` in a few releases, so it looks like a regression from their end. I'll double check by testing against their older releases.

- homography needs further investigation.

**Comment by pavanky** [comment] 2016-09-12 00:01
@ghisvail 

- reg bilateral: implemented a work around for bilateral. 

- reg transpose: tried building older versions of pocl without success. But this test is not failing on any other opencl implementations including CPU versions from Intel and AMD. Any chance you can test this on an older version yourself ?

- reg homography: This is failing on multiple CPU OpenCL implementations. I created this issue to deal with it for a future bugfix release: https://github.com/arrayfire/arrayfire/issues/1583

**Comment by pavanky** [comment] 2016-09-13 02:41
Alright fixed bilateral and homography.

Any update on the trials about transpose?

**Comment by pavanky** [comment] 2016-12-06 02:58
@ghisvail removing the release milestone. Please let us know if there is an update on this.

**Comment by ghisvail** [comment] 2016-12-06 07:44
I'll re-evaluate this issue when `v3.4.2` is released. Thanks for the heads-up.

**Comment by pavanky** [comment] 2017-08-02 08:05
@ghisvail closing this for now. Let me know if this is still an issue.

**Closed by pavanky** 2017-08-02 08:05 UTC
Labels: OpenCL
