### ISSUE TITLE
function for Mesh Grid (2D and 3D) and comprehensive Documentation

### ISSUE THREAD

**Issue by Haider-BA** [arrayfire/arrayfire#1342] opened 2016-03-17 15:37 UTC
Hello,

I want to request new function to create 2D and 3D mesh grid just like in matlab `[X,Y] = meshgrid(xgv,ygv)`. However this could be done by using **Tile**, **moddims** and **seq** in ArrayFire but it looks cumbersome e.g. ` array x = tile(moddims(seq(nx),nx,1), 1,ny);
    array y = tile(moddims(seq(ny),1,ny), nx,1);`.

Documentation is not comprehensive for the functions/methods available in ArrayFire. Kindly explain them with more wording and direct examples on the same page where function defined (please refer to MatLab or Python documentation).

**Comment by shehzan10** [comment] 2016-03-17 18:28
You can simply use [range](http://arrayfire.org/docs/group__data__func__range.htm).
All you need to do is
```
array x = range(dim4(nx, ny), 0);
array y = range(dim4(nx, ny), 1);
```

**Comment by pavanky** [comment] 2016-03-17 18:50
I think the problem is you are searching for terms you learnt from a different language. Our documentation is quite clear about what range does. We can perhaps be more explicit in our tutorials to point the users in the right direction.

I am closing the issue because the requested feature is readily available.

**Closed by pavanky** 2016-03-17 18:50 UTC
Labels: question
