### ISSUE TITLE
Build fails with Ninja

### ISSUE THREAD

**Issue by Keno** [arrayfire/arrayfire#861] opened 2015-06-29 03:21 UTC
```
$ ninja
[58/1450] Performing configure step for 'forge-ext'
Re-run cmake no build system arguments
-- GLFW found!
-- Using Dynamic GLEWmx Lib
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/.julia/v0.4/ArrayFire/deps/build/arrayfire/third_party/forge/src/forge-ext-build
[66/1450] Performing build step for 'forge-ext'
FAILED: cd /home/ubuntu/.julia/v0.4/ArrayFire/deps/build/arrayfire/third_party/forge/src/forge-ext-build && /usr/bin/cmake --build /home/ubuntu/.julia/v0.4/ArrayFire/deps/build/arrayfire/third_party/forge/src/forge-ext-build --config . && /usr/bin/cmake -E touch /home/ubuntu/.julia/v0.4/ArrayFire/deps/build/arrayfire/third_party/forge/src/forge-ext-stamp/forge-ext-build
ninja: error: 'third_party/freetype/lib/libfreetype.a', needed by 'src/libforge.so', missing and no known rule to make it
```
It works fine with make (`-j1`) though, so this might just be a missing dependency.

**Comment by pavanky** [comment] 2015-06-29 03:35
@Keno as a temporary solution you can run cmake with `-DBUILD_GRAPHICS=OFF` to continue using ninja. In the mean time we'll try to figure out what the issue is.

**Comment by Keno** [comment] 2015-06-29 03:36
As I mentioned, it works fine with `make`, so I'm all set. This is just FYI so that the next user might have better luck ;).

**Comment by pavanky** [comment] 2015-06-29 03:44
@Keno Looks like it is a problem when building forge. I am moving the bug upstream. Closing this issue for now.

**Comment by pavanky** [comment] 2015-06-29 03:44
Perhaps I will need to reopen this because the forge tag needs to be updated to fix the issue in arrayfire.

**Comment by pavanky** [comment] 2015-06-29 19:53
@Keno This is now fixed in the devel branch.

**Closed** 2015-06-29 19:53 UTC

**Comment by Keno** [comment] 2015-06-29 19:54
Thanks you!
