### ISSUE TITLE
Different device pointer returned following arithmetic operations

### ISSUE THREAD

**Issue by mlloreda** [arrayfire/arrayfire#1768] opened 2017-04-27 00:08 UTC
Happening after passing the device array as an operand to arithmetic operations. All backends exhibiting this behavior.

```c++
af::array arr = af::randu(2, 2);
af_array c_arr = arr.get();

void *dptr_old;
af_get_device_ptr(&dptr_old, c_arr);

af_array out;
af_add(&out, af::constant(0,2,2).get(), c_arr, false);

void *dptr_new;
af_get_device_ptr(&dptr_new, c_arr);

std::cout << "OLD: " << dptr_old << '\n';
std::cout << "NEW: " << dptr_new << '\n';
assert(dptr_old == dptr_new);
```

**Comment by FilipeMaia** [comment] 2017-05-10 18:43
In certain situations `af_get_device_ptr()` causes a copy. If you don't want this behaviour try `af_get_raw_ptr()`.

**Comment by Thormidable** [comment] 2017-05-18 10:30
Hi All,
   I've checked the V3.4.2 Release interface and I can't find a function called af_get_raw_ptr().
 I can find af_get_data_ptr() but this would require us to copy data out and in to Arrayfire, causing quite an overhead. 

Following your comment, we have added a af_sync(-1) after af_get_device_ptr() to force the system to wait for any operations, generated by af_get_device_ptr(). Is this the proper method for avoiding this issue?

**Comment by pavanky** [comment] 2017-05-18 16:11
@Thormidable `af_get_raw_ptr` is not included when you include `arrayfire.h`. You will need to include `af/internal.h`. This was done because it is a bit unsafe and the behavior can change between versions.

**Comment by pavanky** [comment] 2017-05-19 06:36
@mlloreda @Thormidable  To expand upon @FilipeMaia's comment, `af_get_device_ptr` creates a lock on the device memory. This behhavior was done so that arrayfire does not accidentally free up or over write device memory. 

I am closing this issue because this is expected behavior.

**Closed by pavanky** 2017-05-19 06:36 UTC
Labels: bug
