### ISSUE TITLE
[Perf] Low performance of the convolve_(cuda and opencl)

### ISSUE THREAD

**Issue by felixt56** [arrayfire/arrayfire#3310] opened 2022-10-14 12:27 UTC
convolve test

Description
===========

Reproducible Code
-----------------

System Information
------------------
ArrayFire Version: 3.9.0
Operating System: Ubuntu 20.04
Device: 
Driver version: 
[nvidia_data.txt] (https://github.com/arrayfire/arrayfire/files/9786231/nvidia_data.txt)

Checklist
---------
- [x ] I have read [timing ArrayFire](http://arrayfire.org/docs/timing.htm)

[convolve_cpu.txt](https://github.com/arrayfire/arrayfire/files/9786256/convolve_cpu.txt)
[convolve_cuda.txt](https://github.com/arrayfire/arrayfire/files/9786257/convolve_cuda.txt)
[convolve_opencl.txt](https://github.com/arrayfire/arrayfire/files/9786258/convolve_opencl.txt)

**Comment by felixt56** [comment] 2022-10-14 13:07
I've installed ArrayFire on the comp with Nvidia Graphics card and cuda capable.
I 've run the the three tests: convolve(_cpu, _cuda, _opencl) and got  very strange results. The fastest one is convolve_cpu and the convolve_opencl is terrible slow. Can anybody explain these results?

**Comment by syurkevi** [comment] 2022-10-14 17:08
Closing as duplicate of https://github.com/arrayfire/arrayfire/issues/3202 .
Tests are not meant to be benchmarks. This resource has some hints for writing a benchmark: http://arrayfire.org/docs/timing.htm
Please reopen if you confirm performance slowdowns with the RTX 4000. On the T4 based system we have on google colab I am getting 230us vs. 1.4ms gpu vs. cpu for 3x3 kernel and 1024x1024 signal.

**Closed by syurkevi** 2022-10-14 17:08 UTC
Labels: perf
