### ISSUE TITLE
Complex square root

### ISSUE THREAD

**Issue by Godisemo** [arrayfire/arrayfire#1463] opened 2016-06-17 09:38 UTC
Is it possible to implement the csqrt function for ArrayFire? It is used quite a lot in my scientific computations.

**Comment by 9prady9** [comment] 2016-06-17 10:21
@Godisemo 

As of now, the `af::sqrt` function doesn't handle complex type arrays. However, you can easily work around this by doing something such as below

```cpp
af::array csqrt(const af::array& in)
{
    af::array r = af::real(in);
    af::array i = af::imag(in);

    af::array phi = af::atan2(i, r)/2.0f;
    af::array a = af::sqrt(af::hypot(r, i));

    return af::complex(a*af::cos(phi), a*af::sin(phi));
}
```

You are always welcome to contribute the missing feature.

**Comment by Godisemo** [comment] 2016-06-17 10:25
Thanks for the quick reply. This is precisely the solution I am working on right now.

Would you expect this to give good performance?
Is complex square root something you could consider adding?

**Comment by 9prady9** [comment] 2016-06-17 10:44
Basic functions such as `real`, `imag`, etc. combined with JIT capability of ArrayFire are what makes our library unique. A more sophisticated function can be written out using much simpler functions similar to the way complex square root is implemented in above code stub.

On my laptop with NVIDIA GT 650M mobile card, above code is getting an average run time of 23 milliseconds for complex array of size 4096x4096.

You can time arrayfire code as per the guidelines mentioned [here](http://arrayfire.org/docs/timing.htm).

@pavanky shall answer your question about adding complex array support for sqrt function.

**Comment by pavanky** [comment] 2016-06-17 15:19
We have https://github.com/arrayfire/arrayfire/issues/769 to address this issue. When we do implement this, it will look more or less like what @9prady9 suggested internally. There will not be a performance hit.

BTW if you do decide to contribute, it will need to use our internal API so it will not be exactly similar to what pradeep suggested here.

**Comment by pavanky** [comment] 2016-06-17 15:21
One quick addition to the solution pradeep has given use to add the following as the first line:

```
if (in.isReal()) return af::sqrt(in);
```

**Comment by pavanky** [comment] 2016-06-17 15:23
Considering that you have a work around for now and that it is a duplicate of #769, I am closing the issue for now. If you have any questions, we can still continue the discussion.

**Closed by pavanky** 2016-06-17 15:23 UTC
Labels: duplicate
