### ISSUE TITLE
cmake examples failure on master: OpenMP::OpenMP_CXX not found

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2046] opened 2018-01-22 18:03 UTC
Hi
On recent master, cmake fails with such messages: 
```
CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_bagging_cpu" links to target "OpenMP::OpenMP_CXX" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:13 (add_executable)

CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_rbm_cpu" links to target "OpenMP::OpenMP_CXX" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:45 (add_executable)

CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_perceptron_cpu" links to target "OpenMP::OpenMP_CXX" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:41 (add_executable)

CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_neural_network_cpu" links to target "OpenMP::OpenMP_CXX"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:37 (add_executable)

CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_logistic_regression_cpu" links to target
  "OpenMP::OpenMP_CXX" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:29 (add_executable)


CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_kmeans_cpu" links to target "OpenMP::OpenMP_CXX" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:25 (add_executable)


CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_naive_bayes_cpu" links to target "OpenMP::OpenMP_CXX" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:33 (add_executable)


CMake Error at CMakeLists.txt:42 (_add_executable):
  Target "example_deep_belief_net_cpu" links to target "OpenMP::OpenMP_CXX"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  machine_learning/CMakeLists.txt:17 (add_executable)

```

OS: ubuntu 16
Tried with cmake 3.5 and 3.9.

Perhaps a find openmp is missing ?
Kind

**Comment by 9prady9** [comment] 2018-01-23 05:32
@WilliamTambellini 

I did a clean build on Ubuntu 16.04 few hours back and I didn't have any issues with OpenMP being not found. My machine uses CMake 3.5.1 that I got from apt package manager. We have [FindOpenMP.cmake](https://github.com/arrayfire/arrayfire/blob/master/CMakeModules/FindOpenMP.cmake) script in the CMakeModules path of ArrayFire repository and it is [included properly in the root CMake file](https://github.com/arrayfire/arrayfire/blob/master/CMakeLists.txt#L26). May be your OpenMP is installed in a non-standard path ?

**Comment by WilliamTambellini** [comment] 2018-01-23 20:26
Thanks.
- I ve checked and libgomp is installed in the standard ubuntu location: /usr/lib/x86_64-linux-gnu/libgomp.so.1 
- I did nt copy the examples : I m just trying to build the the examples from a .sh/.run AF installer (arrayfire-no-gl-3.6.0-beta1.sh), which extracts files in (cwd)/share/ArrayFire/examples
In the /share/ArrayFire/cmake/ cmake files, where are you searching for openmp ?
W.

**Comment by 9prady9** [comment] 2018-01-24 04:05
Yes, that is the location where I found the `libgomp.so.1` file on my machine as well. 

That could be because there is no `FindOpenMP.cmake` file under `examples\CMakeModules` which is installed to `share\ArrayFire\examples`.  None of the examples directly link to OpenMP. I wonder why examples are looking for the OpenMP target, I will look into it.

**Comment by umar456** [comment] 2018-01-24 04:09
I think the problem is with the installer and the arrayfire-config generated by cmake. @9prady9 try to install the library in a docker container and see if you run into the same issue when you try to build the examples.

**Comment by 9prady9** [comment] 2018-01-24 04:18
I generated the installer using master HEAD and don't get openmp errors on regular machine. I have to try it on docker and see what happens there.

**Comment by 9prady9** [comment] 2018-01-24 07:38
I generated the installer using master HEAD and don't get openmp errors on regular machine. I have to try it on docker and see what happens there.

**Comment by 9prady9** [comment] 2018-01-24 12:09
I didn't get such errors with docker either.

@WilliamTambellini Please share some details of the Linux distribution you are using and CMake version.

**Comment by 9prady9** [comment] 2018-05-08 13:08
v3.6 is out, @WilliamTambellini can you please check if you can reproduce the problem with v3.6 and reopen if the problem persists. Closing the issue for now.

**Closed by 9prady9** 2018-05-08 13:08 UTC
