### ISSUE TITLE
wiki isn't available, redirects to project root

### ISSUE THREAD

**Issue by kriswuollett** [arrayfire/arrayfire#2648] opened 2019-09-28 20:24 UTC
Can't see build instructions easily since https://github.com/arrayfire/arrayfire/wiki redirects to https://github.com/arrayfire/arrayfire.

**Comment by 9prady9** [comment] 2019-09-29 05:26
That is very odd, I don't think we changed anything on github. @arrayfire/core-devel Any idea what is going on ?

**Comment by 9prady9** [comment] 2019-09-29 09:15
@kriswuollett I found that `wikis` was disabled among features for this repository. Not sure why that happened. I am pretty sure our team didn't do it. I have re-enabled it and the wiki is online again.

Closing since the problem is resolved. Thanks once again for reporting this!

**Closed by 9prady9** 2019-09-29 09:15 UTC
