### ISSUE TITLE
Build afcpu with oneMKL

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#3149] opened 2021-06-17 17:46 UTC
As today the afcpu backend can be built using either:
- the (closed source) Intel MKL libs (USE_CPU_MKL) or 
- the open CBLAS libs

https://github.com/arrayfire/arrayfire/blob/9738a3164faf2eecd3703d70003eac65c09b8213/src/backend/cpu/CMakeLists.txt#L307

A third type of compilation could perhaps now be considered using oneMKL:
https://github.com/oneapi-src/oneMKL

Description
===========
What problems are you trying to solve?  
- not relying on closed source libs
- speed up over open source CBLAS 
- minimize the size of libafcpu.so
- (hopefully) better support for intel GPUs

To be discussed.

**Comment by 9prady9** [comment] 2021-06-18 16:30
@WilliamTambellini This has already been taken care of. oneMKL works out of the box with our current FindMKL(master branch) cmake module. Have you tried building using oneMKL ? our windows CI uses oneMKL and I have been testing and using oneMKL only for the past few months

Closing this as duplicate of #3117 

If you face any issues compiling using oneMKL, we are happy to look into it. You have to use the same `USE_*_MKL` flags for oneMKL also.

**Closed by 9prady9** 2021-06-18 16:30 UTC
Labels: duplicate
