### ISSUE TITLE
RNG quality with OpenCL

### ISSUE THREAD

**Issue by rstub** [arrayfire/arrayfire#2007] opened 2017-12-04 22:45 UTC
As part of https://github.com/RInstitute/rcpparrayfire I am trying to advertise ArrayFire's capability of producing random numbers real fast. But before doing so I wanted to check the RNGs and ran into problems when doing chi^2 tests with lots of random numbers. The original analysis used R in some parts, but I have recoded it in C++ here:
```C++
#include <iostream>
#include <iomanip>
#include <cassert>

#include <arrayfire.h>

// normalized chi^2 statistic for uniform distribution
// multiply with number of samples to get chi^2 statistic
float uchi2(af::array input) {
    assert(input.isvector());
    double expected = 1.0 / input.elements();
    af::array diff = input - expected;
    return af::sum<float>((diff * diff) / expected);
}

int main(int argc, char ** argv) {
    int backend = argc > 1 ? atoi(argv[1]) : 0;
    af::setBackend(static_cast<af::Backend>(backend));
    int device = argc > 2 ? atoi(argv[2]) : 0;
    af::setDevice(device);
    af::info();

    double samples = 1e8;
    int steps = 300;
    int bins = 100;

    af::array total_hist = af::constant(0, bins, f32);
    af::array step_hist = af::constant(0, bins, f32);

    af::setDefaultRandomEngineType(AF_RANDOM_ENGINE_PHILOX);
    //af::setDefaultRandomEngineType(AF_RANDOM_ENGINE_THREEFRY);
    //af::setDefaultRandomEngineType(AF_RANDOM_ENGINE_MERSENNE);
    std::cout << std::setw(4) << "step"
              << std::setw(7) << "chi2_i"
              << std::setw(7) << "chi2_t"
              << std::setprecision(2) << std::fixed << std::endl;
    for(int i = 0; i < steps; ++i) {
        step_hist = af::histogram(af::randu(samples), bins, 0.0, 1.0) / samples;
        total_hist = (total_hist * i + step_hist) / (i + 1);
        std::cout << std::setw(4) << i
                  << std::setw(7) << uchi2(step_hist) * samples
                  << std::setw(7) << uchi2(total_hist) * samples * (i +1)
                  << std::endl;
    }
}
```
Here I am drawing 10^8 random numbers, calculate a histogram for them and determine the chi^2 statistic. I do this 500 times, collecting the individual histograms to form a total histogram, for which chi^2 statistic is also computed. [side note:  I am using this unusual chi^2 for normalized distribution since I am getting some strange but probably unrelated errors when using a more straight forward implementation.]

If I run the program with PHILOX or THREEFRY on the OpenCL backend, I get typically something like this:
```
$ ./chi2 0 2
ArrayFire v3.5.1 (OpenCL, 64-bit Linux, build 0a675e8)
-0- INTEL: Intel(R) HD Graphics, 12367 MB
-1- BEIGNET: Intel(R) HD Graphics Skylake ULT GT2, 4096 MB
[2] INTEL: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 15469 MB
step chi2_i chi2_t
   0 119.23 119.23
   1 101.52 115.02
   2 117.74 126.43
   3  89.05 113.38
   4  91.91 108.98
   5 113.97 104.43
   6 126.62  97.98
   7 111.21  88.87
[...]
 292 107.63 187.05
 293  84.17 186.90
 294  88.01 185.81
 295  79.39 185.76
 296  83.14 187.53
 297  86.37 188.46
 298 101.42 188.98
 299  95.11 190.88
```
In the beginning, both the individual and the total chi^2 are within the expected range (roughly 65 to 140 for 99 degrees of freedom), but at around step 200, the total chi^2 begins to rise reaching values that clearly indicate that the distribution is no longer uniform.

This does not happen if I use PHILOX or THREEFRY on the CPU backend or with MERSENNE on the OpenCL or CPU backend.

**Comment by pavanky** [comment] 2017-12-04 23:06
@rstub Thanks for reporting this. Do you mind contributing a test that will catch these issues in the future ? I can try to use your test as a reference to debug / fix the issue.

**Comment by rstub** [comment] 2017-12-05 18:08
I have given this a shot and this is what I came up with as addition to `test/random.cpp`:
```C++
template <typename T>
T chi2_statistic(array input, array expected) {
    expected *= af::sum<T>(input) / af::sum<T>(expected);
    array diff = input - expected;
    return af::sum<T>((diff * diff) / expected);
}

template <typename T>
void testRandomEngineUniformChi2(randomEngineType type)
{
    if (noDoubleTests<T>()) return;
    af::dtype ty = (af::dtype)af::dtype_traits<T>::af_type;

    int elem = 256*1024*1024;
    int steps = 32;
    int bins = 100;

    array total_hist = af::constant(0.0, bins, ty);
    array expected = af::constant(1.0/bins, bins, ty);

    af::randomEngine r(type, 0);

    // R> qchisq(c(5e-6, 1 - 5e-6), 99)
    // [1]  48.68125 173.87456
    T lower = 48.68125;
    T upper = 173.87456;

    bool prev_step = true;
    bool prev_total = true;
    for (int i = 0; i < steps; ++i) {
        array step_hist = af::histogram(af::randu(elem, ty, r), bins, 0.0, 1.0);
	T step_chi2 = chi2_statistic<T>(step_hist, expected);
	bool step = step_chi2 > lower && step_chi2 < upper;
	ASSERT_TRUE(step || prev_step);
	prev_step = step;

	total_hist += step_hist;
	T total_chi2 = chi2_statistic<T>(total_hist, expected);
	bool total = total_chi2 > lower && total_chi2 < upper;
	ASSERT_TRUE(total || prev_total);
	prev_total = total;
    }
}

TYPED_TEST(RandomEngine, philoxRandomEngineUniformChi2)
{
    testRandomEngineUniformChi2<TypeParam>(AF_RANDOM_ENGINE_PHILOX_4X32_10);
}

TYPED_TEST(RandomEngine, threefryRandomEngineUniformChi2)
{
    testRandomEngineUniformChi2<TypeParam>(AF_RANDOM_ENGINE_THREEFRY_2X32_16);
}

TYPED_TEST(RandomEngine, mersenneRandomEngineUniformChi2)
{
    testRandomEngineUniformChi2<TypeParam>(AF_RANDOM_ENGINE_MERSENNE_GP11213);
}
```

This produces some test failures right on CPU:

```
[  FAILED  ] RandomEngine/0.philoxRandomEngineUniformChi2, where TypeParam = float (154362 ms)
[  FAILED  ] RandomEngine/0.threefryRandomEngineUniformChi2, where TypeParam = float (67125 ms)
[  FAILED  ] RandomEngine/1.philoxRandomEngineUniformChi2, where TypeParam = double (359295 ms)
[  FAILED  ] RandomEngine/1.threefryRandomEngineUniformChi2, where TypeParam = double (128109 ms)
[  FAILED  ] RandomEngine/1.mersenneRandomEngineUniformChi2, where TypeParam = double (17634 ms)
```
and OpenCL:
```
[  FAILED  ] RandomEngine/0.philoxRandomEngineUniformChi2, where TypeParam = float (12659 ms)
[  FAILED  ] RandomEngine/1.philoxRandomEngineUniformChi2, where TypeParam = double (16309 ms)
[  FAILED  ] RandomEngine/1.threefryRandomEngineUniformChi2, where TypeParam = double (9510 ms)
```

So it works in principle, but there are several problems:
* Runtime: random_cpu takes 890 s on my machine, more than 600 s due to these new tests. And that is with some tests failing early.
* The failure conditions are fragile. In principle one should accept a larger range of chi^2 values together with more steps, possibly with different initial seeds. But this would increase runtime even more.
* As a consequence of the fragile conditions, the failure for MERSENNE with `double`on CPU is probably a false positive.
* One should also test `randn`, but that would probably double the runtime.
* I am not sure why PHILOX and THREEFRY are now also failing on CPU.

Overall, I think it is best to do a proper testing of the RNGs together with some well established set of tests. It seems to be particularly easy to test with PractRand, c.f. http://www.pcg-random.org/posts/how-to-test-with-practrand.html. But not within the unit tests, since a full test can take several days.

**Comment by pavanky** [comment] 2017-12-05 18:56
@umar456 What do you think of adding tests that we run infrequently ?

**Comment by umar456** [comment] 2017-12-05 20:50
I think that's a good idea. These types of tests should be done nightly.

**Comment by rstub** [comment] 2017-12-06 15:02
I think I have found the reason for this. For some reasons PHILOX and THREEFRY have a period of only 2^32. Consider:
```C++
#include <iostream>

#include <arrayfire.h>
#include <af/traits.hpp>

template <typename T>
void testPeriod(af::randomEngineType type) {
    af::dtype ty = (af::dtype)af::dtype_traits<T>::af_type;

    uint elem = 1024*1024;
    uint steps = 4*1024;
    af::randomEngine r(type, 0);

    af::array first = af::randu(elem, ty, r);

    for (int i = 0; i < steps; ++i) {
        af::array step = af::randu(elem, ty, r);
	if (af::allTrue<bool>(first == step)) {
	    std::cout << "FAILURE after " << i * elem << " draws" << std::endl;
	}
    }
}

int main(int argc, char ** argv) {
    int backend = argc > 1 ? atoi(argv[1]) : 0;
    af::setBackend(static_cast<af::Backend>(backend));
    int device = argc > 2 ? atoi(argv[2]) : 0;
    af::setDevice(device);
    af::info();

    std::cout << "PHILOX<float>" << std::endl;
    testPeriod<float>(AF_RANDOM_ENGINE_PHILOX);
    std::cout << "THREEFRY<float>" << std::endl;
    testPeriod<float>(AF_RANDOM_ENGINE_THREEFRY);
    std::cout << "MERSENNE<float>" << std::endl;
    testPeriod<float>(AF_RANDOM_ENGINE_MERSENNE);

    if (af::isDoubleAvailable(device)) {
      std::cout << "PHILOX<double>" << std::endl;
      testPeriod<float>(AF_RANDOM_ENGINE_PHILOX);
      std::cout << "THREEFRY<double>" << std::endl;
      testPeriod<float>(AF_RANDOM_ENGINE_THREEFRY);
      std::cout << "MERSENNE<double>" << std::endl;
      testPeriod<float>(AF_RANDOM_ENGINE_MERSENNE);
    }
}
```

Output on my machine:
```
ArrayFire v3.5.1 (OpenCL, 64-bit Linux, build 0a675e8)
[0] INTEL: Intel(R) HD Graphics, 12367 MB
-1- BEIGNET: Intel(R) HD Graphics Skylake ULT GT2, 4096 MB
-2- INTEL: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 15469 MB
PHILOX<float>
FAILURE after 4293918720 draws
THREEFRY<float>
FAILURE after 4293918720 draws
MERSENNE<float>
PHILOX<double>
FAILURE after 4293918720 draws
THREEFRY<double>
FAILURE after 4293918720 draws
MERSENNE<double>
```

**Comment by rstub** [comment] 2017-12-06 17:12
I think I have found the reason for this. For some reasons PHILOX and THREEFRY have a period of only 2^32. Consider:
```C++
#include <iostream>

#include <arrayfire.h>
#include <af/traits.hpp>

template <typename T>
void testPeriod(af::randomEngineType type) {
    af::dtype ty = (af::dtype)af::dtype_traits<T>::af_type;

    uint elem = 1024*1024;
    uint steps = 4*1024;
    af::randomEngine r(type, 0);

    af::array first = af::randu(elem, ty, r);

    for (int i = 0; i < steps; ++i) {
        af::array step = af::randu(elem, ty, r);
	if (af::allTrue<bool>(first == step)) {
	    std::cout << "FAILURE after " << i * elem << " draws" << std::endl;
	}
    }
}

int main(int argc, char ** argv) {
    int backend = argc > 1 ? atoi(argv[1]) : 0;
    af::setBackend(static_cast<af::Backend>(backend));
    int device = argc > 2 ? atoi(argv[2]) : 0;
    af::setDevice(device);
    af::info();

    std::cout << "PHILOX<float>" << std::endl;
    testPeriod<float>(AF_RANDOM_ENGINE_PHILOX);
    std::cout << "THREEFRY<float>" << std::endl;
    testPeriod<float>(AF_RANDOM_ENGINE_THREEFRY);
    std::cout << "MERSENNE<float>" << std::endl;
    testPeriod<float>(AF_RANDOM_ENGINE_MERSENNE);

    if (af::isDoubleAvailable(device)) {
      std::cout << "PHILOX<double>" << std::endl;
      testPeriod<float>(AF_RANDOM_ENGINE_PHILOX);
      std::cout << "THREEFRY<double>" << std::endl;
      testPeriod<float>(AF_RANDOM_ENGINE_THREEFRY);
      std::cout << "MERSENNE<double>" << std::endl;
      testPeriod<float>(AF_RANDOM_ENGINE_MERSENNE);
    }
}
```

Output on my machine:
```
ArrayFire v3.5.1 (OpenCL, 64-bit Linux, build 0a675e8)
[0] INTEL: Intel(R) HD Graphics, 12367 MB
-1- BEIGNET: Intel(R) HD Graphics Skylake ULT GT2, 4096 MB
-2- INTEL: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 15469 MB
PHILOX<float>
FAILURE after 4293918720 draws
THREEFRY<float>
FAILURE after 4293918720 draws
MERSENNE<float>
PHILOX<double>
FAILURE after 4293918720 draws
THREEFRY<double>
FAILURE after 4293918720 draws
MERSENNE<double>
```

**Comment by pavanky** [comment] 2017-12-06 17:18
@rstub Thanks for diggging into this. Is the cpu backend also failing after the same amount of draws?

**Comment by rstub** [comment] 2017-12-06 17:30
@pavanky Yes:
```
ArrayFire v3.5.1 (CPU, 64-bit Linux, build 0a675e8)
[0] Intel: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 15469 MB, Max threads(4) 
PHILOX<float>
FAILURE after 4293918720 draws
THREEFRY<float>
FAILURE after 4293918720 draws
MERSENNE<float>
PHILOX<double>
FAILURE after 4293918720 draws
THREEFRY<double>
FAILURE after 4293918720 draws
MERSENNE<double>
```
BTW, I have not tried to understand this from the code, but I am really curious how that happens. From reading the Random123 paper on today's commute I have the impression that both PHILOX and THREEFRY variants use 4 32bit integers as counters. If one increases only one of them, then it is easy to get repeating numbers after 2^32 steps. But each step should give 4 32bit numbers as output. So I would have expected a period of 4 x 2^32.

**Comment by pavanky** [comment] 2017-12-06 17:40
@rstub I'll check the codebase later today to see what the issue is :)

**Comment by rstub** [comment] 2017-12-07 22:35
I think I am able to provide some answers. The period of 2^32 comes from two places. 

* While a 64 bit counter is used, it is converted to 32 bit before being passed on to the CBRNG: 
https://github.com/arrayfire/arrayfire/blob/master/src/backend/cpu/kernel/random_engine.hpp#L100-L105 and https://github.com/arrayfire/arrayfire/blob/master/src/backend/cpu/kernel/random_engine.hpp#L118-L123
* The counter is increased by the number of elements (https://github.com/arrayfire/arrayfire/blob/master/src/backend/cpu/random_engine.cpp#L27 and https://github.com/arrayfire/arrayfire/blob/master/src/backend/cpu/random_engine.cpp#L36) without correction for the number of random numbers produced per counter (4 for PHILOX and 2 for THREEFRY).

Indeed, this "minimally invasive" patch removes the PHILOX and THREEFRY failures for the chi^2 test on the CPU backend:

```
diff --git a/src/backend/cpu/kernel/random_engine.hpp b/src/backend/cpu/kernel/random_engine.hpp
index 304eb8e2..51419d80 100644
--- a/src/backend/cpu/kernel/random_engine.hpp
+++ b/src/backend/cpu/kernel/random_engine.hpp
@@ -101,8 +101,10 @@ namespace kernel
     {
         uint hi = seed>>32;
         uint lo = seed;
-        uint key[2] = {(uint)counter, hi};
-        uint ctr[4] = {(uint)counter, 0, 0, lo};
+        uint hic = counter>>32;
+        uint loc = counter;
+        uint key[2] = {hic, hi};
+        uint ctr[4] = {loc, 0, 0, lo};
 
         int reset = (4*sizeof(uint))/sizeof(T);
         for (int i = 0; i < (int)elements; i += reset) {
@@ -119,8 +121,10 @@ namespace kernel
     {
         uint hi = seed>>32;
         uint lo = seed;
-        uint key[2] = {(uint)counter, hi};
-        uint ctr[2] = {(uint)counter, lo};
+        uint hic = counter>>32;
+        uint loc = counter;
+        uint key[2] = {hic, hi};
+        uint ctr[2] = {loc, lo};
         uint val[2];
 
         int reset = (2*sizeof(uint))/sizeof(T);
```

However, there are more open questions:
* Why is part of `seed` used for `key` and part for `ctr`? I would have expected `seed` to go into `key` only.
* Why is `ctr` for PHILOX never increased in the loop, while for THREEFRY `ctr[0]` and `key[0]` are increased?
* PHILOX 4x32 uses 128 bit for counting and therefore could have a period of 4 x 2^128. Why is only one 64 bit number used?

**Comment by pavanky** [comment] 2017-12-08 00:02
@rstub There was some misunderstand on my part when I originally wrote the philox implementation for opencl based on older version of Random123 a few years ago. 

The engineer who followed up on it used my code base as a starting point which seems to have caused the issue. The code shown here is much more reasonable: https://github.com/DEShawResearch/Random123-Boost/tree/master/boost/random. I will make the corrections asap. 

Once again thanks for digging into this.

**Comment by rstub** [comment] 2018-02-13 17:30
Any news on this issue?

**Comment by pavanky** [comment] 2018-02-13 18:47
Sorry I haven't had time to look into it yet :(

**Comment by rstub** [comment] 2018-04-10 13:00
I might have time to expand on my minimal patch above. Any chance to get this into version 3.6.0 as *partial* solution?

**Comment by umar456** [comment] 2018-04-10 14:46
@rstub We can get this in as a partial solution. This is a non-breaking change so this can even go into a patch release. We are planning on releasing 3.6 within the next couple of days or so. When do you think you can submit a patch for this?

**Comment by rstub** [comment] 2018-04-10 16:08
@umar456 I will spend some time on this today and tomorrow. Let's see if something usable comes from that.

**Comment by christophe-murphy** [comment] 2024-09-11 23:57
Looks like this has been resolved with the linked merges, closing.

**Closed by christophe-murphy** 2024-09-11 23:57 UTC
Labels: OpenCL
