### ISSUE TITLE
Can't build on MacOsX 10.9.5 - libafopencl.dylib

### ISSUE THREAD

**Issue by ssstuvz** [arrayfire/arrayfire#377] opened 2015-02-13 14:31 UTC
Hi, 
I did all the steps outlined in Readme for installing for Mac OS. Instead of `homebrew` I am using `macports`.

On the step when I try to build arrayfire I get the following error:
`code
Linking CXX shared library libafopencl.dylib
clang: warning: argument unused during compilation: '-pthread'
[ 52%] Built target afopencl
make: *** [all] Error 2
`

I have no idea what is wrong.

**Comment by umar456** [comment] 2015-02-16 21:19
Can you make a gist snippet of the output of the compilation and post the link? This does not give us enough information about the cause of the error.

**Comment by ssstuvz** [comment] 2015-02-18 15:55
My mac crashed yesterday so I had to reinstall the system completely and out of the sudden everything compiled. Probably one of the libraries was an old install. However, it looks like I am doing something wrong. From the documentation:
```bash
$ cd /path/to/dir/arrayfire
$ mkdir build && cd build
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_CUDA=ON -DBUILD_OPENCL=ON # Enables building all 3 backends
$ make -j8   # or number of threads of your choosing
```
I don't get any `makefile` in the directory `build`, so I have to do `cd .. && make -j8`. Is there a typo somewhere in documentation?

**Comment by pavanky** [comment] 2015-02-18 16:04
@ssstuvz 

Did you by any chance run cmake before creating the build directory ?

**Comment by ssstuvz** [comment] 2015-02-18 16:11
@pavanky 
No, did exactly what was written in the documentation.

**Comment by pavanky** [comment] 2015-02-18 16:14
Can you try to reproduce this in a new checkout of ArrayFire ? If a directory called "build" already exists, then there might be problems when following these steps.

We can continue the discussion, but I am closing the issue because the original issue has been resolved.

**Closed by pavanky** 2015-02-18 16:14 UTC
Labels: build, OSX

**Comment by ssstuvz** [comment] 2015-02-18 16:30
There might be a typo in documentation when discussing `ccmake`. It should be `ccmake ..` instead of `ccmake .`

**Comment by pavanky** [comment] 2015-02-18 16:32
@ssstuvz If you are already inside build directory, it should be `ccmake ..`
