### ISSUE TITLE
Array based indexing in 2D array

### ISSUE THREAD

**Issue by hakttari** [arrayfire/arrayfire#314] opened 2015-01-08 09:25 UTC
Recently added feature of array based indexing is cool, but I ran into a problem with the following code. Please help.

array a = randu(5, 1, f32);
array b = where(a < 0.5);
a(b) = 1.0f;	// WORKING as it does in AF2.0
array c = randu(5, 5, f32);
c(b, 1) = 1.0f; // ERROR in AF3.0, but working in AF2.0

**Comment by pavanky** [comment] 2015-01-08 11:26
@hakttari I have mentioned this in other issues you brought this up. For now, you can use the following code as a work around.

```
array cond = (a < 0.5);
array tmp = c(span, 1);
c(span, 1) =  (1 - cond) * tmp + cond;
```

**Comment by pavanky** [comment] 2015-01-08 21:04
Indexing is partially implemented so far but this issue is essentially a duplicate of #245

**Closed by pavanky** 2015-01-08 21:04 UTC
