### ISSUE TITLE
Use multiple ArrayFire backends in the same program

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#946] opened 2015-08-12 22:44 UTC
I'd really like to be able to use multiple ArrayFire backends in the same program, and transfer arrays between them.

I have a use case where I have a very large array - much more than 4 GB so it kills my graphics card.  However I only do intense calculations on a subset of that data. It seems to me the large array is better suited to be managed by the CPU backend (where it is free to use as much memory as my RAM has), and the subsetted data is suited to be pushed to the GPU and be managed by the CUDA backend.

So what I'd like to do is create the larger array on the CPU backend, do an indexing operation to get my subset array, then somehow transfer that smaller array to the GPU to be managed by the CUDA backend. Any operations I do on the large array should be handled by the CPU backend, and any operations I do on the smaller array (that has been transferred to the GPU) should be handled by the CUDA backend.

**Comment by pavanky** [comment] 2015-08-12 22:49
This is a duplicate of https://github.com/arrayfire/arrayfire/issues/232

**Closed by pavanky** 2015-08-12 22:49 UTC

**Comment by pavanky** [comment] 2015-09-13 12:51
This is now present in devel branch as a new backend library that loads other backends at runtime.
