### ISSUE TITLE
build 3.9 for vs2022 error when build jasper

### ISSUE THREAD

**Issue by wududu123** [arrayfire/arrayfire#3574] opened 2024-07-19 09:10 UTC
build error when build jasper .

Description
===========
I check the out file all error such as:
vcruntime_c11_stdatomic.h(36): error C2061: 语法错误: 标识符“atomic_bool”
I found answer,
https://github.com/microsoft/vcpkg/pull/36192.
But how can I modify the jasper's CMakeLists.txt
It always do
-- Cleaning sources...
-- Extracting source... 

Error Log
---------
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j25

Build Environment
Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe

**Comment by edwinsolisf** [comment] 2024-08-05 20:08
This is likely an upstream problem with vcpkg. I was not able to replicate it with ArrayFire 3.9.0. Try `git pull` with vcpkg to update the packages before using vcpkg toolchain to build ArrayFire. I'm closing this issue, feel free to reopen it if you find the issue is coming from ArrayFire.

**Comment by jacobgrass** [comment] 2024-08-16 02:00
I had this same issue trying to build AF on windows. It was mitigated by removing the vcpkg baseline. However, I have been unable to build AF. Are there any updated build instructions?

**Comment by jacobgrass** [comment] 2024-08-16 16:09
Thanks for the reply Edwin!

I followed the build instructions [here](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Windows), are they outdated? I have been working on building the source all of this week, to no avail unfortunately.  I did end up getting a project to generate by changing the built in baseline in the vcpkg.json to:

`"builtin-baseline": "9a6da16845eca8d6ed70be416c1acbd206894c7f"`

However, the generated project was unable to build with many linker issues. I think following the steps in the build instructions have confused the linker with different versions?

Switching back to v3.9, the build command you listed fails with 

```
Installing 137/149 jasper[core,default-features,opengl]:x64-windows@4.0.0#2...
Building jasper[core,default-features,opengl]:x64-windows@4.0.0#2...
D:\admin\source\repos\arrayfire\CMakeModules\vcpkg\vcpkg-triplets\x64-windows.cmake: info: loaded overlay triplet from here
D:\vcpkg\buildtrees\versioning_\versions\jasper\d7f51c26899ba9433a5a3ab92fc5b5887d5c764c: info: installing overlay port from here
-- Using cached jasper-software-jasper-402d096b39f4f618ad9e6ff2b4fc1b5eb260a2e4.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/jasper/src/5eb260a2e4-ca02e25be6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/jasper-software-jasper-402d096b39f4f618ad9e6ff2b4fc1b5eb260a2e4.tar.gz
-- Applying patch no_stdc_check.patch
-- Applying patch fix-library-name.patch
-- Using source at D:/vcpkg/buildtrees/jasper/src/5eb260a2e4-ca02e25be6.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j29
    Working Directory: D:/vcpkg/buildtrees/jasper/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\jasper\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  D:/admin/source/repos/arrayfire/build/build/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  D:/admin/source/repos/arrayfire/build/build/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  buildtrees/versioning_/versions/jasper/d7f51c26899ba9433a5a3ab92fc5b5887d5c764c/portfile.cmake:38 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)


error: building jasper:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle jasper:x64-windows: 12 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+jasper
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[jasper]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fadmin%2Fsource%2Frepos%2Farrayfire%2Fbuild%2Fbuild%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md

-- Running vcpkg install - failed
CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (message):
  vcpkg install failed.  See logs for more information:
  D:\admin\source\repos\arrayfire\build\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:18 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by jacobgrass** [comment] 2024-08-16 16:30
I changed the built in baseline because of this issue:
https://github.com/microsoft/vcpkg/issues/38192

Unfortunately I just cleared vcpkg. I was planning to remove the manually installed dependencies and rebuild. I also noticed I have CUDA 12.6. Do I need to downgrade?

**Comment by edwinsolisf** [comment] 2024-08-16 16:43
Regarding the CUDA 12.6, you may apply this [pull request](https://github.com/arrayfire/arrayfire/pull/3586) and it should work

**Comment by jacobgrass** [comment] 2024-08-16 17:35
Thanks Edwin! I think I will try to build in linux instead for now.

**Comment by edwinsolisf** [comment] 2024-08-23 16:16
@jacobgrass @wududu123  I have posted a fix for the jasper build problem. If you are able to test it, let me know if you find any issues with it still.

**Closed** 2024-08-30 00:31 UTC
Labels: build

**Comment by brfire** [comment] 2024-10-28 03:21
Thanks for fixing this, I had gotten stuck on it a couple times.
