### ISSUE TITLE
SVD and multiple matmul calls interfere with each other? Multiple SVD calls not allowed?

### ISSUE THREAD

**Issue by rennis250** [arrayfire/arrayfire#1746] opened 2017-03-24 12:48 UTC
Dear all,

I'm currently trying to diagnose some problems that I am having with the Rust bindings to ArrayFire. It seems part of my troubles are coming from ArrayFire itself. I have the following C++ test:

```c++
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

int main(int argc, char *argv[]) {
  try {
    int device = argc > 1 ? atoi(argv[1]) : 0;
    af::setDevice(device);
    af::info();

    dim_t samples = 800;
    dim_t bands = 400;
    dim_t adsline = 400;

    af::array d = af::randu(samples, bands, adsline, f32);
    af::array d2 = reorder(d, 0, 2, 1, 3);
    af::array d3 = moddims(d2, (samples * adsline), bands, 1, 1);

    af::array m = mean(d3, 0);
    d3 = d3 - tile(m, (samples * adsline), 1, 1, 1);
    af::array in = reorder(d3, 1, 0, 2, 3);

    array u;
    array s_vec;
    array vt;
    svd(u, s_vec, vt, in);

    array uu = u(span, seq(0, 9));
    array s_mat = diag(s_vec(seq(0, 9)), 0, false);
    array pc = matmul(uu, s_mat);
    array hp = matmul(pc, vt(seq(0, 9), span)); // STOPS WORKING HERE!
  } catch (af::exception &e) {
    fprintf(stderr, "%s\n", e.what());
    throw;
  }

  return 0;
}
```

If I run this, then the second ```matmul``` stalls and starts eating up a lot of memory. I have tested that two successive ```matmul``` calls do not cause the problem. This problem happens _after_ a call to ```svd```, whether it be the inplace version of not. If you instead chain the final two ```matmul``` calls into one ```matmul``` call, then the computations carry out as expected and program finishes. However, in Rust, you cannot overload functions like this.

For info, my test computer is a Mac laptop with 8GB of RAM. The ArrayFire details are the following:

```
ArrayFire v3.4.2 (CPU, 64-bit Mac OSX, build 2da9967)
[0] Intel: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz, 8192 MB, Max threads(4)
```

In the case of Rust, I am using Rust 1.16.0 with the latest arrayfire-rust crate from crates.io.

**Comment by rennis250** [comment] 2017-03-24 13:24
In addition, if I try using svd multiple times in the same block of code, then the program halts and consumes excessive amounts of memory after the second iteration (on a laptop with 8GB of RAM) or after the 5th iteration (on a machine with 256GB of RAM). Example code that does not work on the laptop:

```c++
#include <arrayfire.h>
#include <cstdio>
#include <cstdlib>

using namespace af;

int main(int argc, char *argv[]) {
  try {
    int device = argc > 1 ? atoi(argv[1]) : 0;
    af::setDevice(device);
    af::info();

    dim_t w = 400;
    dim_t h = 800 * 53;

    af::array d = af::randu(w, h, f32);
    af::array e = af::randu(w, h, f32);

    array u;
    array s;
    array vt;

    std::cout << "before svd - 1" << std::endl;
    svd(u, s, vt, d);
    std::cout << "after svd - 1" << std::endl;

    std::cout << "before svd - 2" << std::endl;
    svd(u, s, vt, e);
    std::cout << "after svd - 2" << std::endl;

    array uu = u(span, seq(0, 9));
    array s_mat = diag(s(seq(0, 9)), 0, false);
    array pc = matmul(uu, s_mat);
    array hp = matmul(pc, vt(seq(0, 9), span));
  } catch (af::exception &e) {
    fprintf(stderr, "%s\n", e.what());
    throw;
  }

  return 0;
}
```

This investigation was prompted by the similar issue for the Rust crate: https://github.com/arrayfire/arrayfire-rust/issues/123

**Comment by 9prady9** [comment] 2020-07-06 11:07
Trying to revive the debugging associated with this issue I noticed that the code snippet from original description fails with out of memory exception always no matter the backend. Second snippet runs fine on CPU backend. Note that I didn't notice any stalls. Perhaps, upstream has fixed the problem - I am not sure though.

From the initial looks of it, It seems like the memory requirement of the sizes involved here is quite high. I have to check the sizes and upstream's scratch space requirements to confirm that theory. 

PS. Jotting down the progress here.

**Comment by 9prady9** [comment] 2020-07-06 13:14
It seems like the problem size is too huge. Given below is the program output from CPU backend that finished successfully.
```
./build/examples/helloworld/helloworld_cpu 
ArrayFire v3.8.0 (CPU, 64-bit Linux, build b5eb73c2a)
[0] AMD: AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8GAF Memory at ../examples/helloworld/helloworld.cpp:61: before svd 1
Allocated [ Bytes | Buffers ] = [ 135680000 | 2 ]
In Use    [ Bytes | Buffers ] = [ 135680000 | 2 ]
AF Memory at ../examples/helloworld/helloworld.cpp:63: after svd 1
Allocated [ Bytes | Buffers ] = [ 7395202048 | 6 ]
In Use    [ Bytes | Buffers ] = [ 7327362048 | 5 ] 
AF Memory at ../examples/helloworld/helloworld.cpp:65: before svd 2
Allocated [ Bytes | Buffers ] = [ 7395202048 | 6 ]
In Use    [ Bytes | Buffers ] = [ 7327362048 | 5 ]
AF Memory at ../examples/helloworld/helloworld.cpp:67: after svd 2
Allocated [ Bytes | Buffers ] = [ 14586884096 | 9 ]
In Use    [ Bytes | Buffers ] = [ 7327362048 | 5 ]
AF Memory at ../examples/helloworld/helloworld.cpp:72: at end
Allocated [ Bytes | Buffers ] = [ 14586901504 | 11 ]
In Use    [ Bytes | Buffers ] = [ 7395203072 | 7 ]
```
Note the mem info output `after svd 1`, that's roughly 7GB allocations within ArrayFire without including scratch space used by upstream if there is any.  For the next svd, that space doubles making it 14GB. It should have failed with out of memory error on a 8GB laptop, not sure why it was stalled. On my CPU with 32GB ram, the program completed normally.

Given these memory requirements, I wouldn't expect this problem size to run on my GPU which has only 3GB memory and it didn't even for svd1.

@umar456 @pavanky Do you have suggestions on how to proceed further with this issue ? I can try on a GPU which has much larger RAM, but I don't see any reason why it would stall instead of failing with out of memory exception.

**Comment by 9prady9** [comment] 2020-07-20 06:22
A quick update: I don't see any notes in earlier comment w.r.t valgrind runs, hence updating. Valgrind doesn't show any leaks w.r.t svd on CPU implementation.

**Comment by 9prady9** [comment] 2021-05-04 09:29
Another debug session update: I haven't been able to reproduce this across different CUDA toolkits or in OpenCL/CPU backend so far. Closing this due to the same. @rennis250 Please try the latest ArrayFire stable release, 3.8.0, If you are still facing the problem with latest ArrayFire stable release, feel free to reopen the issue.

**Closed by 9prady9** 2021-05-04 09:29 UTC
Labels: bug, needs-more-info
