### ISSUE TITLE
OpenCL linkage error

### ISSUE THREAD

**Issue by mboisson** [arrayfire/arrayfire#2272] opened 2018-08-10 12:29 UTC
Hi,
I am configuring arrayfire with OpenCL provided by Cuda, i.e. 
`-DOPENCL_LIBRARIES:FILEPATH=/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/cuda/9.0.176/lib64/libOpenCL.so` 

The configure runs fine. However, late in the build process, I get these errors : 
`[ 93%] Linking CXX executable cholesky_opencl
cd /dev/shm/mboisson/avx2/ArrayFire/3.6.1/iimklc-2016.4.90/easybuild_obj/examples/lin_algebra && /cvmfs/soft.computecanada.ca/nix/store/pvb2n3an22sm5mi5gvz8s81ijyd7j675-cmake-cursesUI-qt4UI-3.8.2/bin/    cmake -E cmake_link_script CMakeFiles/cholesky_opencl.dir/link.txt --verbose=1
/tmp/eb-5OyHrB/tmpwhueev/icpc  -O2 -xCore-AVX2 -ftz -fp-speculation=safe -fp-model source -O3 -DNDEBUG  -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/cuda/9.0.176/      lib64 -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/icc/2016.4.258/lib/intel64 -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/11.3.4.258/lib -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/11.3.4.258/mkl/lib/intel64 -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/imkl/11.3.4.258/lib -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/   Compiler/intel2016.4/boost/1.60.0/lib -L/cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/intel2016.4/fftw/3.3.6/lib -rdynamic CMakeFiles/cholesky_opencl.dir/cholesky.cpp.o  -o           cholesky_opencl -Wl,-rpath,/dev/shm/mboisson/avx2/ArrayFire/3.6.1/iimklc-2016.4.90/easybuild_obj/src/backend/opencl ` 

```../../src/backend/opencl/libafopencl.so.3.6.1
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<cl_double2>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<char>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<long long>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<int>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<float>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<unsigned short>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<cl_float2>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<unsigned char>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<double>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<unsigned int>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<short>::getNode()'
../../src/backend/opencl/libafopencl.so.3.6.1: undefined reference to `opencl::Array<unsigned long long>::getNode()'
make[2]: *** [examples/lin_algebra/CMakeFiles/cholesky_opencl.dir/build.make:99: examples/lin_algebra/cholesky_opencl] Error 1
make[2]: Leaving directory '/dev/shm/mboisson/avx2/ArrayFire/3.6.1/iimklc-2016.4.90/easybuild_obj'
make[1]: *** [CMakeFiles/Makefile2:6328: examples/lin_algebra/CMakeFiles/cholesky_opencl.dir/all] Error 2
``` 

Looking at the link line, it does not seem like `libOpenCL.so` is being linked against, while it probably should if it expects to find OpenCL references ?

Thanks,

Maxime

**Comment by mboisson** [comment] 2018-08-10 12:31
This looks a lot like https://github.com/arrayfire/arrayfire/issues/1255, which is supposedly fixed, but I'm encountering it...

**Comment by mboisson** [comment] 2018-08-22 13:31
Anyone got an idea regarding this one ?

**Comment by umar456** [comment] 2018-08-22 16:09
Sorry. I thought you had closed this issue. I am not sure what is going on here and I am not able to reproduce it. What compiler/toolchain are you using?

**Comment by mboisson** [comment] 2018-08-22 17:51
Here is out cmake line : 
```
cmake /dev/shm/mboisson/avx2/ArrayFire/3.6.1/iimklc-2016.4.90/arrayfire-full-3.6.1/ -DCMAKE_INSTALL_PREFIX=/home/mboisson/.local/easybuild/software/2017/avx2/CUDA/intel2016.4/cuda9.0/arrayfire/3.6.1 -DCMAKE_C_COMPILER='icc' -DCMAKE_Fortran_FLAGS='-O2 -xCore-AVX2 -ftz -fp-speculation=safe -fp-model  source' -DCMAKE_CXX_FLAGS='-O2 -xCore-AVX2 -ftz -fp-speculation=safe -fp-model source' -DCMAKE_CXX_COMPILER='icpc' -DCMAKE_Fortran_COMPILER='ifort' -DCMAKE_C_FLAGS='-O2 -xCore-AVX2 -ftz -fp-speculation=safe -fp-model source' -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DUSE_CPU_MKL:BOOL=ON -DUSE_OPENCL_MKL:BOOL=ON -DMKL_THREAD_LAYER='Intel OpenMP' -  DBUILD_TESTING=OFF  -DOpenCL_LIBRARY=$CUDA_HOME/lib64/libOpenCL.so -DCUDA_architecture_build_targets="3.0;3.2;3.5;3.7;5.0;5.2;5.3;6.0;6.1;6.2;7.0"
``` 

The resulting CMakeCache.txt is here : https://gist.github.com/mboisson/7bc53e016a86cf7a5798ac12cc3b335b

**Comment by 9prady9** [comment] 2020-07-16 09:19
I was able to reproduce this on opencl backend with icc. Looking into it.

**Closed** 2020-07-17 14:13 UTC
Labels: bug, build
