### ISSUE TITLE
Add support for indexing sparse array

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2054] opened 2018-02-12 18:51 UTC
Good morning all
This is probably just an enhancement request in order to add support for indexing sparse arrays in order to extract a sparse sub block from a sparse array : 
if the sparse matrix is:
```
 0 0 0
 0 9 0
 0 0 0
 0 0 9
```
then 
mysparseArray(af:seq(0,1), af::seq(0,1)) 
should contain (ideally still in sparse format):
```
 0 0
 0 9
```
With 3.5.1 this exception is thrown when trying to : 
af::exception: ArrayFire Exception (Invalid input argument:202):
In function const ArrayInfo& getInfo(af_array, bool, bool)
In file src/api/c/array.cpp:30
Invalid argument at index 0
Expected: info->isSparse() == false
In function af::array::array_proxy::operator af::array()
In file src/api/cpp/array.cpp:719
 
@umar456 : could you confirm this is not a bug, just not implemented ?
Kind

**Comment by 9prady9** [comment] 2018-07-11 07:03
Duplicate of https://github.com/arrayfire/arrayfire/issues/1859

**Closed by 9prady9** 2018-07-11 07:03 UTC
Labels: feature
