### ISSUE TITLE
opencl sort_by_key and sort_index failing intermittently

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#995] opened 2015-09-11 17:10 UTC
uncomment the following tests after the issues is fixed:
```
diff --git a/test/sort_by_key.cpp b/test/sort_by_key.cpp
index 4f817aa..35bbc97 100644
--- a/test/sort_by_key.cpp
+++ b/test/sort_by_key.cpp
@@ -115,9 +115,10 @@ void sortTest(string pTestFile, const bool dir, const unsigned resultIdx0, const
     SORT_INIT(Sort10x10True,  sort_by_key_2D,    true,  0, 1);
     SORT_INIT(Sort10x10False, sort_by_key_2D,    false, 2, 3);
     SORT_INIT(Sort1000True,   sort_by_key_1000,  true,  0, 1);
-    SORT_INIT(Sort1000False,  sort_by_key_1000,  false, 2, 3);
     SORT_INIT(SortMedTrue,    sort_by_key_med,   true,  0, 1);
-    SORT_INIT(SortMedFalse,   sort_by_key_med,   false, 2, 3);
+    // FIXME: below two tests are disabled temporarily until issue#995 is fixed
+    //SORT_INIT(Sort1000False,  sort_by_key_1000,  false, 2, 3);
+    //SORT_INIT(SortMedFalse,   sort_by_key_med,   false, 2, 3);
     // Takes too much time in current implementation. Enable when everything is parallel
     //SORT_INIT(SortLargeTrue,  sort_by_key_large, true,  0, 1);
     //SORT_INIT(SortLargeFalse, sort_by_key_large, false, 2, 3);
diff --git a/test/sort_index.cpp b/test/sort_index.cpp
index f429626..1f503a7 100644
--- a/test/sort_index.cpp
+++ b/test/sort_index.cpp
@@ -116,9 +116,10 @@ void sortTest(string pTestFile, const bool dir, const unsigned resultIdx0, const
     SORT_INIT(Sort10x10True,  sort_10x10, true,  0, 1);
     SORT_INIT(Sort10x10False, sort_10x10, false, 2, 3);
     SORT_INIT(Sort1000True,   sort_1000,  true,  0, 1);
-    SORT_INIT(Sort1000False,  sort_1000,  false, 2, 3);
     SORT_INIT(SortMedTrue,    sort_med1,  true,  0, 1);
-    SORT_INIT(SortMedFalse,   sort_med1,  false, 2, 3);
+    // FIXME: below two tests are disabled temporarily until issue#995 is fixed
+    //SORT_INIT(Sort1000False,  sort_1000,  false, 2, 3);
+    //SORT_INIT(SortMedFalse,   sort_med1,  false, 2, 3);
     // Takes too much time in current implementation. Enable when everything is parallel
     //SORT_INIT(SortMed5True,   sort_med,   true,  0, 1);
     //SORT_INIT(SortMed5False,  sort_med,   false, 2, 3);

```

**Comment by shehzan10** [comment] 2016-01-09 04:33
I tested this after #1202 and can't reproduce this any more. Can anyone else check too?

**Comment by 9prady9** [comment] 2016-01-09 06:45
@shehzan10 will check and let you know.

**Comment by 9prady9** [comment] 2016-01-09 07:11
@shehzan10 The tests passed fine on my machine which has NVIDIA GT650M, but we should test this on some AMD GPU.

**Comment by shehzan10** [comment] 2016-01-10 05:04
I confirmed with multiple runs on both Intel and AMD  devices, and Linux and Windows that this is no longer happening with the PR #1202. 

@pavanky if you can test this and verify, then we'll mark it as resolved in #1202 and uncomment the disabled tests from this issue.

**Comment by pavanky** [comment] 2016-01-10 05:12
@shehzan10 uncomment the tests in the PR. Let jenkins run the tests.

**Comment by shehzan10** [comment] 2016-01-10 05:15
I tested it manually on Window-02 (AMD machine), Linux-03 (AMD) and both ran fine. Ill send the commit tomorrow.

**Closed** 2016-01-14 01:36 UTC
Labels: bug
