### ISSUE TITLE
Batched dot and matrixmul operation

### ISSUE THREAD

**Issue by Botev** [arrayfire/arrayfire#1171] opened 2015-12-16 21:28 UTC
It would be very nice if there are batched version of these two BLAS operations, doesn't really matter on which dimension the batch would be. Note that for the MM this means that the inputs will be 3D Tensors.

**Comment by pavanky** [comment] 2015-12-16 21:46
Isn't batched `dot` just a matrix multiply ? I understand the need for batched matrix multiply though.

**Comment by pavanky** [comment] 2015-12-16 21:47
BTW this is a duplicate of #483

**Closed by pavanky** 2015-12-16 21:47 UTC

**Comment by Botev** [comment] 2015-12-16 21:50
You are correct, maybe reatracted it to only batched MM.
