### ISSUE TITLE
Interop with OpenCL problem

### ISSUE THREAD

**Issue by avilchess** [arrayfire/arrayfire#2091] opened 2018-03-19 16:58 UTC
Hi guys,

I'm having troubles while developing a custom OpenCL kernel with Arrayfire. On one hand, I followd the next tutorial (http://arrayfire.org/docs/interop_opencl.htm), However, the step 3, see below, is producing a **Bus Error: 10**.
```c
// 3. Obtain cl_mem references to af::array objects
    cl_mem * d_A = A.device<cl_mem>();
    cl_mem * d_B = B.device<cl_mem>();
```
On the other hand, I found another example that provides a different solution to it, (https://github.com/pavanky/arrayfire_examples/blob/master/opencl/simple.cpp). This second procedure does not fail at this point, as it uses the type **float**.
```c
// 3. Obtain cl_mem references to af::array objects
    float * d_A = A.device<float>();
    float * d_B = B.device<float>();
```
However, It fails when setting the kernel arguments and produces a **Segmentation fault: 11**:
```c
// Set input parameters for the kernel
    err |= clSetKernelArg(kernel, arg++, sizeof(cl_mem), &d_y);
    err |= clSetKernelArg(kernel, arg++, sizeof(cl_mem), &d_x);
    err |= clSetKernelArg(kernel, arg++, sizeof(int   ), &num);
````

Any clue around these problems?
Thanks in advance,

**Comment by 9prady9** [comment] 2018-03-30 13:04
@avilchess I have tried the code sample we have in our documentation and it executed fine on my machine. I am using Arch Linux with a GTX 1060 GPU. Can you please share the information of that system on which you tried to do this and the OpenCL device you are using.

I believe the second alternative example source you mentioned is from old v2 arrayfire and it may not completely apply to v3.

**Comment by mlloreda** [comment] 2018-04-06 17:07
@avilchess I also wasn't able to reproduce the issues on macOS.

**Comment by avilchess** [comment] 2018-04-15 10:10
Hi Guys,

First, thanks for answering. I tried to execute the previous code on a MacBook Pro with a MacOs 10.13.4, this machine features an AMD Radeon Pro 560, with OpenCL 1.2. 
My feeling is that I can´t use the cl_mem type to instantiate the following function template  cl_mem * d_B = B.device<cl_mem>();
Based on your previous messages, I imagine that you have no problems with that, so shall I do/check any step before (like setting backend or so)?

**Comment by 9prady9** [comment] 2018-09-18 06:34
@avilchess Whats the update on your end ? If this is no longer an issue, please close the issue.

**Comment by 9prady9** [comment] 2018-09-25 05:57
Closing due to inactivity.

**Closed by 9prady9** 2018-09-25 05:57 UTC
Labels: OpenCL, unconfirmed
