### ISSUE TITLE
[Build] Error on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [arrayfire/arrayfire#3084] opened 2021-02-03 13:12 UTC
current GitHub master
cmake -DCMAKE_BUILD_TYPE=Release -DAF_BUILD_CUDA=OFF ..
make fails with 
... 
[ 38%] Linking CXX executable assign_unified
cd /data/jw/arrayfire/build/test && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_assign_unified.dir/link.txt --verbose=1
/usr/bin/c++ -O2 -DNDEBUG CMakeFiles/test_assign_unified.dir/assign.cpp.o CMakeFiles/arrayfire_test.dir/arrayfire_test.cpp.o -o assign_unified  -Wl,-rpath,/data/jw/arrayfire/build/test/gtest/googlemock/gtest:/data/jw/arrayfire/build/src/api/unified gtest/googlemock/gtest/libgtest.so ../src/api/unified/libaf.so.3.8.0 mmio/libmmio.a -lpthread
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target test_assign_unified
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_float
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_int
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_half
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_uintl
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_ushort
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_short
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_double
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_uchar
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_intl
make[2]: Leaving directory '/data/jw/arrayfire/build'
[ 38%] Built target opencl_sort_by_key_char
make[1]: Leaving directory '/data/jw/arrayfire/build'
make: *** [Makefile:182: all] Error 2
[jw@cn06 build]$

**Comment by 9prady9** [comment] 2021-02-04 10:43
@LutzWeischerFujitsu I can't make out the errors, can you please share the whole log, perhaps capture it into a file and share the file here.

Please run using single thread so that compilation error would be easy to spot.

**Comment by LutzWeischerFujitsu** [comment] 2021-02-04 15:17
Pradeep, stuti, that was a good hint. There is a -m64 compiler option, which disturbes. 
[arrayfire-build-log.txt](https://github.com/arrayfire/arrayfire/files/5926648/arrayfire-build-log.txt)

**Comment by 9prady9** [comment] 2021-02-08 05:12
I personally haven't tried on Fedora 33, but I did try building ArrayFire's CPU backend on a Raspberry Pi and it compiled fine. We don't specifically add this `m64` flag in our CMake, but I think it gets added based on the compiler that CMake picks and the target platform on which build is taking place.

I haven't tried OpenCL on ARM platform yet. I can try on my raspberry and see how that goes. The error seems to come from `clFFT` upstream. Unfortunately, it isn't maintained by original authors any more. We have a fork that we keep for future purposes but we haven't added any significant new features to our fork. If it is a simple fix, we will take a look into it definitely.

**Comment by 9prady9** [comment] 2021-02-17 10:31
I was able to reproduce the problem on Aarch64 using Pi 4. I am looking into it.

**Comment by 9prady9** [comment] 2021-02-17 11:21
@LutzWeischerFujitsu You need the following diff to compile clFFT successfully.
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ee2600b..e196952 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -220,8 +220,13 @@ elseif( CMAKE_COMPILER_IS_GNUCXX )
        endif( )
 
        if( BUILD64 )
-               set( CMAKE_CXX_FLAGS "-m64 ${CMAKE_CXX_FLAGS}" )
-               set( CMAKE_C_FLAGS "-m64 ${CMAKE_C_FLAGS}" )
+        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
+                   set( CMAKE_CXX_FLAGS "-march=armv8-a ${CMAKE_CXX_FLAGS}" )
+                   set( CMAKE_C_FLAGS "-march=armv8-a ${CMAKE_C_FLAGS}" )
+        else()
+                   set( CMAKE_CXX_FLAGS "-m64 ${CMAKE_CXX_FLAGS}" )
+                   set( CMAKE_C_FLAGS "-m64 ${CMAKE_C_FLAGS}" )
+        endif()
        else( )
                set( CMAKE_CXX_FLAGS "-m32 ${CMAKE_CXX_FLAGS}" )
                set( CMAKE_C_FLAGS "-m32 ${CMAKE_C_FLAGS}" )
```
I was able to build OpenCL backend successfully once clFFT was fixed with above patch. Note the cmake version I used was 3.16.

Using POCL, I was able to run helloworld example too but it seemed slower than native CPU backend (Note OpenCL was targeting the same CPU just via OpenCL). If you have vendor implementation for the hardware you want to target using OpenCL, you should be able to use OpenCL backend as well. Worst case scenario, you can at least prototype using POCL.

**Comment by LutzWeischerFujitsu** [comment] 2021-02-17 11:33
Thanks. Please let me know when a new working master is released.

**Comment by 9prady9** [comment] 2021-02-22 14:24
@LutzWeischerFujitsu I have patched our clFFT fork with the fix - https://github.com/arrayfire/clFFT/commit/5a1db8c3af850d34cfae8f4ce8f387873ecb8a69

It should be available via the next fix release. You should automatically receive release announcement as soon as we publish on GitHub.

Closing this since the bug in upstream has been fixed.

**Closed by 9prady9** 2021-02-22 14:24 UTC
Labels: build, question

**Comment by LutzWeischerFujitsu** [comment] 2021-04-09 09:44
:-), works now. Thanks.

**Comment by BA8F0D39** [comment] 2021-04-09 20:25
@LutzWeischerFujitsu 

99% of arrayfire functions work on POCL but the functions that have the name "bykey" don't work that well.
