### ISSUE TITLE
Problem with pow on Datatype c64

### ISSUE THREAD

**Issue by CaptainPaule** [arrayfire/arrayfire#1762] opened 2017-04-19 12:00 UTC
Hey Folks, 

look at the following code snippet

    af::array zeros = af::constant(af::cdouble(0.,0.), 1, 5, c64);
    af::array results = af::pow(zeros, 2.);
    af_print(results);

the output is:

results
[1 5 1 1]
   Offset: 0
   Strides: [1 1 5 5]
         (-nan,-nan)          (-nan,-nan)          (-nan,-nan)          (-nan,-nan)          (-nan,-nan) 

It is clear that the pow operation do nothing with the array zeros. Maybe this in an issue in the angle calculation, but i dont know.

Greetings

**Comment by pavolmarak** [comment] 2017-04-19 22:00
@CaptainPaule Hello,

the solution you posted works the same for me, ending up with with NaNs. I do not know what is the expected result but I guess you expect array `results` to have 0 in all 5 positions.

**Goal:** to raise complex numbers [0+0i, 0+0i,0+0i,0+0i,0+0i]  to the power of 2

The only way that works for me is to create two identical arrays containg these complex and multiplying them.

1.  Create two arrays representing real and imaginary parts of these complex numbers:

```cpp
    af::array real_parts = af::constant(0.,1,5,f64);
    af::array imag_parts = af::constant(0.,1,5,f64);
```

2.  Create array of complex numbers out from real and imaginary parts:

```cpp
af::array zeros = af::complex(real_parts,imag_parts);
```

3.  Multiply to obtain power of 2

```cpp
af::array results = zeros*zeros;
```

And display and the result is:

```
[1 5 1 1]
         (0.0000,0.0000)          (0.0000,0.0000)          (0.0000,0.0000)          (0.0000,0.0000)          (0.0000,0.0000) 

Is this what you wanted?
```

**Comment by pavanky** [comment] 2017-04-19 22:10
I think the issue is with the way `af::pow(x, v)` is implemented currently for complex numbers. It performs `exp(v * log(x))` which results in NaN because `log(x)` is NaN.

This can be fixed by going to polar form.

**Comment by pavanky** [comment] 2017-04-20 20:24
@CaptainPaule for now, can you try the following work around ?

```
array my_pow(array arr, double pow)
{
    array mag = af::pow(af::abs(arr), pow);
    array angle = af::arg(arr) * pow;
    return af::complex(af::cos(angle), af::sin(angle));
}
```
This will compile to a single kernel launch so you don't have to worry about the performance.

**Closed** 2017-04-22 04:11 UTC
Labels: bug
