### ISSUE TITLE
Meanshift failing intermittently

### ISSUE THREAD

**Issue by umar456** [arrayfire/arrayfire#565] opened 2015-04-06 01:08 UTC
the af_meanshift function fails intermittently with very large values as the output. I can reproduce it on the k20c after a few tries. Here is the build where it fails: 
http://ci.arrayfire.org/job/arrayfire-linux-coveralls/28/console

**Comment by pavanky** [comment] 2015-04-06 01:43
The gpu may be in a faulty state. We have a long running process that is not terminated on that machine. I have not been able to reproduce the problem eslewhere.

**Comment by umar456** [comment] 2015-04-06 03:05
Perhaps, but it looks like its only failing on that one function. Maybe we can do a restart tomorrow morning and find out

**Comment by 9prady9** [comment] 2015-04-06 15:01
@umar456 `meanshift_cuda` didn't fail in today's morning run. I couldn't reproduce the problem on my machine as well. This could be because of what @pavanky suggested. However, i shall keep an eye on the test runs of this week and see if the problem resurfaces.

**Comment by umar456** [comment] 2015-04-06 16:37
I was able to reproduce this problem on that machine after a reboot. I wonder if the card is the problem because it says its 80% utilized and there are no processes running on that machine.

**Comment by umar456** [comment] 2015-04-06 19:18
Still failing

**Comment by 9prady9** [comment] 2015-04-06 19:20
@umar456 I just ran it multiple times on all three devices and it ran fine.

**Comment by 9prady9** [comment] 2015-04-06 20:51
Was able to reproduce it now. My stupidity, i was running OpenCL backend and was thinking it is CUDA. I was fooled by the CUDA devices on OpenCL backend.

**Comment by 9prady9** [comment] 2015-05-05 18:11
Fixed by #642

**Closed by 9prady9** 2015-05-05 18:11 UTC
Labels: bug
