### ISSUE TITLE
blas opencl test failed in debug mode with AMD CPU implementation

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#967] opened 2015-08-24 16:39 UTC
`blas_opencl` test failed on my machine(i5-4690k, AMD R9 290 DualX) - it was clean build from scratch. All the other tests passed. 

Did blas from opencl backend undergo any changes ?

Note: The blas_opencl tests seg faults while running MultiGPUSquare_CPP test.

**Comment by 9prady9** [comment] 2015-08-24 16:58
This could very well may be an issue only with my machine, opencl backend is reporting two machines with ID 0 twice. 

Tried running `info_opencl` test on one of the build machine with AMD card in it, same error - same device reported multiple times with same device id.

**Comment by 9prady9** [comment] 2015-08-24 17:02
#964 had a change that is related to this, but the issue still seems to be not fixed.

**Comment by pavanky** [comment] 2015-08-24 18:51
#964 and #963 are resolved. Look at the tests: 
http://ci.arrayfire.org/job/arrayfire-linux-test/branch/devel/899/console

Make sure you built cleanly from devel.

**Comment by 9prady9** [comment] 2015-08-24 21:54
Both of my trials were clean builds from devel. To make sure that it is not just my machine, i tried it on one of the build machine with AMD GPU on it (I have already mentioned this in one of the above comments).

**Comment by pavanky** [comment] 2015-08-24 21:55
This is not failing on jenkins. I am not sure what you are testing.

**Comment by pavanky** [comment] 2015-08-24 22:05
This is output of info_opencl on our AMD build machine:

```
$ ./test/info_opencl
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Info/0, where TypeParam = float
[ RUN      ] Info/0.All
ERROR: GLFW wasn't able to initalize
ArrayFire v3.1.0 (OpenCL, 64-bit Linux, build af7681f)
[0] AMD     : Tahiti
-1- AMD     : Tahiti
-2- AMD     : Genuine Intel(R) CPU  @ 2.60GHz
ArrayFire v3.1.0 (OpenCL, 64-bit Linux, build af7681f)
-0- AMD     : Tahiti
[1] AMD     : Tahiti
-2- AMD     : Genuine Intel(R) CPU  @ 2.60GHz
ArrayFire v3.1.0 (OpenCL, 64-bit Linux, build af7681f)
-0- AMD     : Tahiti
-1- AMD     : Tahiti
[2] AMD     : Genuine Intel(R) CPU  @ 2.60GHz
[       OK ] Info/0.All (764 ms)
[----------] 1 test from Info/0 (764 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (764 ms total)
[  PASSED  ] 1 test.
```

This is the output of blas_opencl
```
Running main() from gtest_main.cc
[==========] Running 48 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from MatrixMultiply/0, where TypeParam = float
[ RUN      ] MatrixMultiply/0.Square
[       OK ] MatrixMultiply/0.Square (1355 ms)
[ RUN      ] MatrixMultiply/0.NonSquare
[       OK ] MatrixMultiply/0.NonSquare (669 ms)
[ RUN      ] MatrixMultiply/0.SquareVector
[       OK ] MatrixMultiply/0.SquareVector (429 ms)
[ RUN      ] MatrixMultiply/0.RectangleVector
[       OK ] MatrixMultiply/0.RectangleVector (421 ms)
[ RUN      ] MatrixMultiply/0.Square_CPP
[       OK ] MatrixMultiply/0.Square_CPP (0 ms)
[ RUN      ] MatrixMultiply/0.NonSquare_CPP
[       OK ] MatrixMultiply/0.NonSquare_CPP (1 ms)
[ RUN      ] MatrixMultiply/0.SquareVector_CPP
[       OK ] MatrixMultiply/0.SquareVector_CPP (0 ms)
[ RUN      ] MatrixMultiply/0.RectangleVector_CPP
[       OK ] MatrixMultiply/0.RectangleVector_CPP (1 ms)
[ RUN      ] MatrixMultiply/0.MultiGPUSquare_CPP
[       OK ] MatrixMultiply/0.MultiGPUSquare_CPP (1533 ms)
[ RUN      ] MatrixMultiply/0.MultiGPUNonSquare_CPP
[       OK ] MatrixMultiply/0.MultiGPUNonSquare_CPP (1087 ms)
[ RUN      ] MatrixMultiply/0.MultiGPUSquareVector_CPP
[       OK ] MatrixMultiply/0.MultiGPUSquareVector_CPP (841 ms)
[ RUN      ] MatrixMultiply/0.MultiGPURectangleVector_CPP
[       OK ] MatrixMultiply/0.MultiGPURectangleVector_CPP (785 ms)
[----------] 12 tests from MatrixMultiply/0 (7124 ms total)

[----------] 12 tests from MatrixMultiply/1, where TypeParam = af::af_cfloat
[ RUN      ] MatrixMultiply/1.Square
[       OK ] MatrixMultiply/1.Square (735 ms)
[ RUN      ] MatrixMultiply/1.NonSquare
[       OK ] MatrixMultiply/1.NonSquare (511 ms)
[ RUN      ] MatrixMultiply/1.SquareVector
[       OK ] MatrixMultiply/1.SquareVector (434 ms)
[ RUN      ] MatrixMultiply/1.RectangleVector
[       OK ] MatrixMultiply/1.RectangleVector (362 ms)
[ RUN      ] MatrixMultiply/1.Square_CPP
[       OK ] MatrixMultiply/1.Square_CPP (0 ms)
[ RUN      ] MatrixMultiply/1.NonSquare_CPP
[       OK ] MatrixMultiply/1.NonSquare_CPP (1 ms)
[ RUN      ] MatrixMultiply/1.SquareVector_CPP
[       OK ] MatrixMultiply/1.SquareVector_CPP (0 ms)
[ RUN      ] MatrixMultiply/1.RectangleVector_CPP
[       OK ] MatrixMultiply/1.RectangleVector_CPP (0 ms)
[ RUN      ] MatrixMultiply/1.MultiGPUSquare_CPP
[       OK ] MatrixMultiply/1.MultiGPUSquare_CPP (1917 ms)
[ RUN      ] MatrixMultiply/1.MultiGPUNonSquare_CPP
[       OK ] MatrixMultiply/1.MultiGPUNonSquare_CPP (1349 ms)
[ RUN      ] MatrixMultiply/1.MultiGPUSquareVector_CPP
[       OK ] MatrixMultiply/1.MultiGPUSquareVector_CPP (982 ms)
[ RUN      ] MatrixMultiply/1.MultiGPURectangleVector_CPP
[       OK ] MatrixMultiply/1.MultiGPURectangleVector_CPP (886 ms)
[----------] 12 tests from MatrixMultiply/1 (7178 ms total)

[----------] 12 tests from MatrixMultiply/2, where TypeParam = double
[ RUN      ] MatrixMultiply/2.Square
[       OK ] MatrixMultiply/2.Square (408 ms)
[ RUN      ] MatrixMultiply/2.NonSquare
[       OK ] MatrixMultiply/2.NonSquare (305 ms)
[ RUN      ] MatrixMultiply/2.SquareVector
[       OK ] MatrixMultiply/2.SquareVector (323 ms)
[ RUN      ] MatrixMultiply/2.RectangleVector
[       OK ] MatrixMultiply/2.RectangleVector (304 ms)
[ RUN      ] MatrixMultiply/2.Square_CPP
[       OK ] MatrixMultiply/2.Square_CPP (1 ms)
[ RUN      ] MatrixMultiply/2.NonSquare_CPP
[       OK ] MatrixMultiply/2.NonSquare_CPP (0 ms)
[ RUN      ] MatrixMultiply/2.SquareVector_CPP
[       OK ] MatrixMultiply/2.SquareVector_CPP (0 ms)
[ RUN      ] MatrixMultiply/2.RectangleVector_CPP
[       OK ] MatrixMultiply/2.RectangleVector_CPP (7 ms)
[ RUN      ] MatrixMultiply/2.MultiGPUSquare_CPP
[       OK ] MatrixMultiply/2.MultiGPUSquare_CPP (1156 ms)
[ RUN      ] MatrixMultiply/2.MultiGPUNonSquare_CPP
[       OK ] MatrixMultiply/2.MultiGPUNonSquare_CPP (878 ms)
[ RUN      ] MatrixMultiply/2.MultiGPUSquareVector_CPP
[       OK ] MatrixMultiply/2.MultiGPUSquareVector_CPP (787 ms)
[ RUN      ] MatrixMultiply/2.MultiGPURectangleVector_CPP
[       OK ] MatrixMultiply/2.MultiGPURectangleVector_CPP (727 ms)
[----------] 12 tests from MatrixMultiply/2 (4896 ms total)

[----------] 12 tests from MatrixMultiply/3, where TypeParam = af::af_cdouble
[ RUN      ] MatrixMultiply/3.Square
[       OK ] MatrixMultiply/3.Square (537 ms)
[ RUN      ] MatrixMultiply/3.NonSquare
[       OK ] MatrixMultiply/3.NonSquare (314 ms)
[ RUN      ] MatrixMultiply/3.SquareVector
[       OK ] MatrixMultiply/3.SquareVector (356 ms)
[ RUN      ] MatrixMultiply/3.RectangleVector
[       OK ] MatrixMultiply/3.RectangleVector (225 ms)
[ RUN      ] MatrixMultiply/3.Square_CPP
[       OK ] MatrixMultiply/3.Square_CPP (0 ms)
[ RUN      ] MatrixMultiply/3.NonSquare_CPP
[       OK ] MatrixMultiply/3.NonSquare_CPP (1 ms)
[ RUN      ] MatrixMultiply/3.SquareVector_CPP
[       OK ] MatrixMultiply/3.SquareVector_CPP (0 ms)
[ RUN      ] MatrixMultiply/3.RectangleVector_CPP
[       OK ] MatrixMultiply/3.RectangleVector_CPP (6 ms)
[ RUN      ] MatrixMultiply/3.MultiGPUSquare_CPP
[       OK ] MatrixMultiply/3.MultiGPUSquare_CPP (1296 ms)
[ RUN      ] MatrixMultiply/3.MultiGPUNonSquare_CPP
[       OK ] MatrixMultiply/3.MultiGPUNonSquare_CPP (1258 ms)
[ RUN      ] MatrixMultiply/3.MultiGPUSquareVector_CPP
[       OK ] MatrixMultiply/3.MultiGPUSquareVector_CPP (914 ms)
[ RUN      ] MatrixMultiply/3.MultiGPURectangleVector_CPP
[       OK ] MatrixMultiply/3.MultiGPURectangleVector_CPP (580 ms)
[----------] 12 tests from MatrixMultiply/3 (5488 ms total)

[----------] Global test environment tear-down
[==========] 48 tests from 4 test cases ran. (24686 ms total)
[  PASSED  ] 48 tests.
```

**Comment by 9prady9** [comment] 2015-08-24 22:05
i did not change anything to test anything specifically. `blas_opencl` failed on my machine when i did `make test`. While debugging that, i ran `info_opencl` test, which showed incorrect information about the devices on the machine. 

I am just running `info_opencl` & `blas_opencl` from the tests we have. However, i think this incorrect device information is happening only on the machines with AMD GPU only (@shehzan10 was getting correct output for `info` function call).

**Comment by pavanky** [comment] 2015-08-24 22:06
@9prady9 I have been testing this on AMD machines all day. Why can't you simply post a sample output ?

**Comment by 9prady9** [comment] 2015-08-24 22:35
i noticed this in debug mode build, not release mode. too late to mention that, but forgot to mention it earlier.

**Comment by shehzan10** [comment] 2016-02-17 18:42
Can you check this with the clBLAS updates that were added into devel?

**Comment by pavanky** [comment] 2016-02-17 18:44
Still an issue in debug mode.

**Comment by pavanky** [comment] 2016-09-14 17:32
Closing it since it is not a bug in release mode and affects only one architecture.

**Closed by pavanky** 2016-09-14 17:32 UTC
Labels: bug, wontfix
