### ISSUE TITLE
Concurrent transfer and processing

### ISSUE THREAD

**Issue by AndyP-APSensing** [arrayfire/arrayfire#3109] opened 2021-03-15 16:15 UTC
I'm trying to concurrently transfer the next block of data to the GPU (using cudaMemcpyAsync) while the next block of memory is being processed with arrayfire code.  However, when viewing the output with the nvidia visual profilter, it shows that the transfer is happening first followed by the arrayfire compute.

When arrayfire is first called, does it run a cudaDeviceSynchronise which would potentially stop my transfers?  If this is the case, is there a way to set arrayfire so it uses a cudaStreamSynchronise with arrayfire's own stream and I can control the device synchronise external to the arrayfire code?

**Comment by 9prady9** [comment] 2021-03-16 04:29
@AndyP-APSensing ArrayFire's API is asynchronous by design. We have one stream that is not `0` for each CUDA device.  All commands that are enqueued to the same stream run in order. For concurrent transfer and execution, you would need an additional CUDA stream. You would have to use CUDA API to create this additional stream for the same device ArrayFire is using and use that stream for copying data using `cudaMemcpyAsync`. For learning about CUDA-interop, please have a look at our tutorial - https://arrayfire.org/docs/interop_cuda.htm

You would need to use `getNativeId()` to get active CUDA device id, then use that id with CUDA API to create set the context, creating additional stream etc.

**Comment by 9prady9** [comment] 2021-03-22 05:25
@AndyP-APSensing Please close the issue if the question has been addressed.

**Closed** 2021-03-22 09:58 UTC
Labels: question
