### ISSUE TITLE
MKL not found when linking with libaf

### ISSUE THREAD

**Issue by rstub** [arrayfire/arrayfire#2372] opened 2018-12-14 21:38 UTC
As discussed [on slack](https://arrayfire-org.slack.com/archives/C6M9AEJTB/p1537938276000100): 

Using a docker image created by this Dockerfile:

```
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
    r-base-dev \
    r-cran-codetools \
    r-cran-rcpp \
    curl \
    libglfw3 \
    libgl1-mesa-glx \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN curl -o arrayfire-installer.sh  http://arrayfire.s3.amazonaws.com/3.6.2/ArrayFire-v3.6.2_Linux_x86_64.sh \
 && sh arrayfire-installer.sh --skip-license --exclude-subdir --prefix=/usr/local \
 && rm arrayfire-installer.sh \
 && ldconfig /usr/local/lib64

RUN Rscript -e 'install.packages("RcppArrayFire", repo = "https://www.daqana.org/drat/")' \
 && rm -rf /tmp/*
```

One can start `R` and run a simple script:

```
library(RcppArrayFire)
set.seed(42)
n <- 100000
p <- 40
X <- matrix(rnorm(n*p), ncol = p)
y <- X %*% c(rep(0.5, p)) + rnorm(n)
modelAF <- fastLmPure(X, y)
```

Result:

> Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

On slack it was suggested to use `LD_PRELOAD="/usr/local/lib64/libmkl_core.so:/usr/local/lib64/libtbb.so.2:/usr/local/lib64/libmkl_tbb_thread.so" R` as workaround. This does work, but is of course inconvenient.

**Comment by 9prady9** [comment] 2018-12-17 06:39
What are the paths listed in your ld config files ?

**Comment by umar456** [comment] 2018-12-17 13:35
@9prady9 The problem is that MKL dlopens its own libraries that need the libmkl_core libs to be part of the global namespace. I think the solution is to directly link these libs to libaf.so even though its not using it directly. The other option is the use the RTLD_GLOBAL flag to load libafcpu which is normally not recommended.

**Comment by rstub** [comment] 2018-12-19 10:19
@9prady9 The Docker container has no directories listed for ldconfig. But due to the explicit `ldconfig /usr/local/lib64` call all libraries in their are known:

```
root@32ebbd1d487e:/# ldconfig --print-cache | grep local
	libtbb.so.2 (libc6,x86-64) => /usr/local/lib64/libtbb.so.2
	libnvrtc.so.10.0 (libc6,x86-64) => /usr/local/lib64/libnvrtc.so.10.0
	libnvrtc-builtins.so.10.0 (libc6,x86-64) => /usr/local/lib64/libnvrtc-builtins.so.10.0
	libmkl_tbb_thread.so (libc6,x86-64) => /usr/local/lib64/libmkl_tbb_thread.so
	libmkl_mc3.so (libc6,x86-64) => /usr/local/lib64/libmkl_mc3.so
	libmkl_mc.so (libc6,x86-64) => /usr/local/lib64/libmkl_mc.so
	libmkl_intel_lp64.so (libc6,x86-64) => /usr/local/lib64/libmkl_intel_lp64.so
	libmkl_def.so (libc6,x86-64) => /usr/local/lib64/libmkl_def.so
	libmkl_core.so (libc6,x86-64) => /usr/local/lib64/libmkl_core.so
	libmkl_avx512.so (libc6,x86-64) => /usr/local/lib64/libmkl_avx512.so
	libmkl_avx2.so (libc6,x86-64) => /usr/local/lib64/libmkl_avx2.so
	libmkl_avx.so (libc6,x86-64) => /usr/local/lib64/libmkl_avx.so
	libglbinding.so.2 (libc6,x86-64) => /usr/local/lib64/libglbinding.so.2
	libforge.so.1 (libc6,x86-64) => /usr/local/lib64/libforge.so.1
	libforge.so (libc6,x86-64) => /usr/local/lib64/libforge.so
	libcusparse.so.10.0 (libc6,x86-64) => /usr/local/lib64/libcusparse.so.10.0
	libcusolver.so.10.0 (libc6,x86-64) => /usr/local/lib64/libcusolver.so.10.0
	libcufft.so.10.0 (libc6,x86-64) => /usr/local/lib64/libcufft.so.10.0
	libcublas.so.10.0 (libc6,x86-64) => /usr/local/lib64/libcublas.so.10.0
	libafopencl.so.3 (libc6,x86-64) => /usr/local/lib64/libafopencl.so.3
	libafopencl.so (libc6,x86-64) => /usr/local/lib64/libafopencl.so
	libafcuda.so.3 (libc6,x86-64) => /usr/local/lib64/libafcuda.so.3
	libafcuda.so (libc6,x86-64) => /usr/local/lib64/libafcuda.so
	libafcpu.so.3 (libc6,x86-64) => /usr/local/lib64/libafcpu.so.3
	libafcpu.so (libc6,x86-64) => /usr/local/lib64/libafcpu.so
	libaf.so.3 (libc6,x86-64) => /usr/local/lib64/libaf.so.3
	libaf.so (libc6,x86-64) => /usr/local/lib64/libaf.so
	libOpenCL.so.1 (libc6,x86-64) => /usr/local/lib64/libOpenCL.so.1
```

**Comment by 9prady9** [comment] 2018-12-19 11:10
We probably will try the solution @umar456 suggested - linking mkl libs with unified library. That should fix the problem.

We will update the issue once the fix is in master.

**Comment by rstub** [comment] 2019-07-03 10:17
Any update on this? I have updated the Dockerfile to use AF v3.6.4 on Ubuntu 19.04 and had to change to `export LD_PRELOAD="/usr/local/lib64/libmkl_core.so:/usr/local/lib64/libmkl_gnu_thread.so"`:

```
FROM ubuntu:19.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
    r-base-dev \
    r-cran-codetools \
    r-cran-rcpp \
    curl \
    libglfw3 \
    libgl1-mesa-glx \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN curl -o arrayfire-installer.sh  http://arrayfire.s3.amazonaws.com/3.6.4/ArrayFire-v3.6.4_Linux_x86_64.sh \
 && sh arrayfire-installer.sh --skip-license --exclude-subdir --prefix=/usr/local \
 && rm arrayfire-installer.sh \
 && ldconfig /usr/local/lib64

RUN Rscript -e 'install.packages("RcppArrayFire", repo = "https://www.daqana.org/drat/")' \
 && rm -rf /tmp/*
```

**Comment by 9prady9** [comment] 2020-04-23 11:46
@umar456 Is this still a problem ?

**Comment by umar456** [comment] 2020-04-24 03:08
This is fixed in master.

**Closed by umar456** 2020-04-24 03:08 UTC
Labels: build, question
