### ISSUE TITLE
System Image viewer showing black image for float tiff images saved by saveImageNative

### ISSUE THREAD

**Issue by nikkadim** [arrayfire/arrayfire#1940] opened 2017-10-03 03:25 UTC
arrayfire v.3.5.1 Release
```
af::setBackend(AF_BACKEND_CUDA);
//af::setBackend(AF_BACKEND_CPU);
array img = loadimage("Test1_000000.tif",false);
array mask = constant(1.f, 19, 19);
int maxI = (int)max<unsigned char>(img);
int minI = (int)min<unsigned char>(img);
img = (img -minI)/(maxI-minI);
img = 254 -img;
img = (erode(img, mask));
img = 254 -img;

img = erode(img, mask);	
saveImageNative("outt.tif", img);

```
Original:
![test1_000000](https://user-images.githubusercontent.com/152394/31108679-b6cc398a-a7c8-11e7-8685-67102820071b.png)

AF_BACKEND_CPU
![outt_cpu](https://user-images.githubusercontent.com/152394/31108647-9716391a-a7c8-11e7-89c9-7fd7b999be71.png)
AF_BACKEND_CUDA (8.0)
![outt_cuda](https://user-images.githubusercontent.com/152394/31108651-9b3de31c-a7c8-11e7-96bb-9c37e7c5e32b.png)

**Comment by 9prady9** [comment] 2017-10-03 05:13
@nikkadim by default loadimage returns f32 array, so doing max/min on f32 array with unsigned char as template parameter is first issue in above code. The other issue I did find is that if the output extension is tif(which should be able to store f32 data), the output is coming out as empty black image. I shall look into that.

As a workaround for you, the following code works fine for my on my machine, please try it out.
```cpp
        af::setBackend(AF_BACKEND_CUDA);
        //af::setBackend(AF_BACKEND_CPU);
        array img = loadImage("test.png", false);

        array mask = constant(1.f, 19, 19);
        float maxI = max<float>(img);
        float minI = min<float>(img);

        img = (img -minI)/(maxI-minI);
        img = 254 -img;

        img = erode(img, mask);
        img = 254 - img;

        saveImageNative("out.png", (255*img).as(u8));
```

**Comment by 9prady9** [comment] 2017-10-03 05:38
@nikkadim I did a quick test of reloading the floating point tiff image back into ArrayFire using `loadImageNative` and it displayed fine. I believe the black image you are seeing is due to the lack of functionality in the image viewer you are using to view the image. Note that GIMP also didn't display this image right. I had to use a package called `nip2` on my ubuntu 16.04 machine to view this image.

After I installed nip2, I was able to view the image properly after doing the below
```
The image may be too dark or too light, click View / Toolbar / Display
Control to add a couple of sliders to the window. The left one sets the
scale (it's log), the right the offset.
```

Here's the output of nip2
![screenshot from 2017-10-03 11-02-57](https://user-images.githubusercontent.com/3270458/31111327-ddd64338-a82a-11e7-9f16-3c31e21d5f76.png)

Since this is not an issue with code, I will close the issue. I am also renaming the title of the issue to the following for future users who face similar issue.
"Image viewer showing black image for float tiff images"

**Comment by nikkadim** [comment] 2017-10-03 14:23
Thanks for your answer.

Here is what I'm getting with your code:

```
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GTX 465, 1024 MB, CUDA Compute 2.0
ArrayFire Exception (Internal error:998):
In function void cuda::kernel::reduce_first_launcher<Ti, To, op>(cuda::Param<To>, cuda::CParam<Ti>, unsigned int, unsigned int, unsigned int, bool, double)
In file src\backend\cuda\kernel/reduce.hpp:325
CUDA Error (8): invalid device function


In function float __cdecl af::max<float>(const class af::array &)
In file src\api\cpp\reduce.cpp:148

```

**Comment by 9prady9** [comment] 2017-10-03 14:29
I tried it on Linux machine with CUDA 3.0 card. I see that you are using 2.0 card, it could be probably because of that. Can try running the program again after setting the environment variable AF_PRINT_ERRORS=1.

**Comment by nikkadim** [comment] 2017-10-03 14:31
@9prady9 yep, you are right it's a Compute 2.0 card and  NVIDIA deprecated their support in CUDA 8.0 and will be dropping support from CUDA 8.5 :(

**Comment by nikkadim** [comment] 2017-10-03 17:25
@9prady9  I found a new GPU with Compute 6.1 (GTX1070),  ran your code, load image to Imagej (https://imagej.nih.gov/ij/) which is capable to deal with 32-bit images) but it's still shows it's black (zeroes!)

```
int main(int argc, char** argv)
{

    try {

	af::setBackend(AF_BACKEND_CUDA);
	af::info();
	//af::setBackend(AF_BACKEND_CPU);
        array img = loadImage("Test1_000000.tif", false);	
        array mask = constant(1.f, 19, 19);
        float maxI = max<float>(img);
        float minI = min<float>(img);

        img = (img -minI)/(maxI-minI);
        img = 254 -img;

        img = erode(img, mask);
        img = 254 - img;
		
        saveImageNative("out32.tif", img);//(255*img).as(u8));
	saveImageNative("out.tif", (255*img).as(u8));
    } catch (af::exception& e) {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }
    return 0;
}
```

Images:
![8](https://user-images.githubusercontent.com/152394/31138896-f1f9afc2-a83d-11e7-9921-c0f63d1adeaf.png)
![32](https://user-images.githubusercontent.com/152394/31138895-f1e73748-a83d-11e7-82a4-c6e3c2c75ba2.png)

Thanks!

PS: Works just fine with AF_BACKEND_CPU

**Comment by 9prady9** [comment] 2017-10-03 17:57
@nikkadim 

I used the code you pasted in your recent comment and generated both `out.tif` and `out32.tif`. `out.tif` was readily displayed by regular image viewer on GNOME since it is a 8-bit unsigned char image. However, I needed to use imagemagick(tried some other tool other than nip2 that is image processing related) to view the image and it is clearly visible.

Following is the imagemagick command I used to display the file
`display -size 1672x1495 -depth 32 -define quantum:format=floating-point out32.tif`

I am not really sure what is going on your end, can you displaying your output images with imagemagick using the above mentioned command.

Also, why does the CUDA driver version say 9000 ?? in the af::info string printed by your program. What driver is this ?

Also, please make sure you are compiling the code for latest compute code 6.1 instead of 2.0 which was for your earlier code.

**Comment by nikkadim** [comment] 2017-10-03 19:30
@9prady9  that is interesting, have you been able to display that way out32.tif which I've attached?

Ok, I  found Ubuntu machine with _imagemagick_ on it and used _display_ to load out32.tif - black (all zeros)!
![32](https://user-images.githubusercontent.com/152394/31144766-b44fb92a-a84f-11e7-83d3-33831dd84e0d.png)

This I what I'm getting from  af::info:
```
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 9000
[0] GeForce GTX 1070, 8192 MB, CUDA Compute 6.1
```
After I changed the GPU card i installed the latest NVidia driver v.385.69 which is likely has CUDA driver 9.000, but this is not an issue, this program does the same and on other Windows PC. Again for CPU it calculates right.

What did you mean compile code with Compute 6.1?  I used ArrayFire 3.5.1  libs which dynamically determine what Compute version on hardware, am I wrong?

**Comment by 9prady9** [comment] 2017-10-03 20:49
@nikkadim The out32.tif you provided doesn't display properly - all back.

Ignore my comment about 3.5.1, I was under the impression that you built the code from source.

I believe this may be due to the fact that ArrayFire's installer you get from the website was built with compute versions "30;35;37;50;52;60". We missed adding 6.1 for 3.5.1 release installers. I think this is the reason you are seeing black outputs everywhere.

We will update the 3.5.1 installers with added support for 6.1 soon. Sorry about the inconvenience.

**Comment by nikkadim** [comment] 2017-10-04 00:18
Thank you for you help @9prady9 , I appreciate it!

Have only one concern, if this is due to compute version, why _dilate_ function gives appropriate results? Thanks!

**Comment by 9prady9** [comment] 2017-10-04 04:17
This is not a consistent error we have noticed across all functions. I have
experienced this recently with raw cuda code as well. One of my colleagues
has also experienced similar issue using ArrayFire with GTX 1080 - next kin
of 1070. Based on all the reasons, I said MAY be this is similar to the
errors we are seeing with compute version mismatch. Also,  we haven't
touched image load/store functions for a while. We will let you know here
once we have updated the installers on our website and you can test the
code again.

**Comment by nikkadim** [comment] 2017-10-04 13:26
Thank you @9prady9, will wait updated installer!

**Comment by 9prady9** [comment] 2017-10-04 13:53
Hi, I just got word from my colleague that installers have been updated.
Can you please try the new one and check if you are still facing the
problem.

**Comment by nikkadim** [comment] 2017-10-04 14:58
Sure, from regular link: https://arrayfire.com/download/?

**Comment by 9prady9** [comment] 2017-10-04 15:11
Yes

**Comment by nikkadim** [comment] 2017-10-04 15:29
Looks the same.
Modified code, added print for min/max before and after _erode_ call:
```
int main(int argc, char** argv)
{

    try {

	af::setBackend(AF_BACKEND_CUDA);
        //af::setBackend(AF_BACKEND_CPU);
       	af::info();

        array img = loadImage("Test1_000000.tif", false);	
        array mask = constant(1, 19, 19);
		
        // calc min/max
        float maxI = max<float>(img);
        float minI = min<float>(img);
        printf("Before:\n\tMaximum in array: %f\n", maxI);
	printf("\tMinimum in array: %f\n", minI);

        // apply filter
        img = (img -minI)/(maxI-minI);
        img = 254 -img;
	img = erode(img, mask);
        img = 254 - img;

	// recalc min/max	
	maxI = max<float>(img);
        minI = min<float>(img);
	printf("After:\n\tMaximum in array: %f\n", maxI);
	printf("\tMinimum in array: %f\n", minI);
	
        saveImageNative("out32.tif", img);
	saveImageNative("out.tif", (img).as(u8));

    } catch (af::exception& e) {
        fprintf(stderr, "%s\n", e.what());
        throw;
    }
    return 0;
}
```
output:
```
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 9000
[0] GeForce GTX 1070, 8192 MB, CUDA Compute 6.1
Before:
        Maximum in array: 255.000000
        Minimum in array: 0.000000
After:
        Maximum in array: -1.#INF00
        Minimum in array: -1.#INF00
```

Should be build number differ? It's the same as yesterday.

**Comment by nikkadim** [comment] 2017-10-04 16:00
Found NVidia TITAN X with Compute 5.2:

```
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 8000
[0] GeForce GTX TITAN X, 12288 MB, CUDA Compute 5.2
Before:
        Maximum in array: 255.000000
        Minimum in array: 0.000000
After:
        Maximum in array: -1.#INF00
        Minimum in array: -1.#INF00
```

**Comment by mlloreda** [comment] 2017-10-04 16:31
@nikkadim The build number should be the same - the only difference between the installers are the compute versions.

**Comment by nikkadim** [comment] 2017-10-04 21:22
@9prady9  @mlloreda 
I looks like this issue related to #1546 

Made a similar test:

```

		array in = constant(0, 4, 4);
		in(1, 1, 0, 0) = 1;
		in(1, 2, 0, 0) = 1;
		print("in", in);
		array filter = af::constant(1, 2, 2);
		print("filter", filter);
		array out = erode(in, filter);
		print("erode", out);
		array out2 = dilate(in, filter);
		print("dilate", out2);
```

output:
```
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 9000
[0] GeForce GTX 1070, 8192 MB, CUDA Compute 6.1
in
[4 4 1 1]
    0.0000     0.0000     0.0000     0.0000
    0.0000     1.0000     1.0000     0.0000
    0.0000     0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000

filter
[2 2 1 1]
    1.0000     1.0000
    1.0000     1.0000

erode
[4 4 1 1]
       inf        inf        inf        inf
       inf        inf        inf        inf
       inf        inf        inf        inf
       inf        inf        inf        inf

dilate
[4 4 1 1]
      -inf     0.0000     1.0000     1.0000
    0.0000     0.0000     1.0000     1.0000
    0.0000     1.0000     1.0000     1.0000
    0.0000     0.0000     0.0000     0.0000
```

but then I changed filters call sequence:

```
		array in = constant(0, 4, 4);
		in(1, 1, 0, 0) = 1;
		in(1, 2, 0, 0) = 1;
		print("in", in);
		array filter = af::constant(1, 2, 2);
		print("filter", filter);
		array out2 = dilate(in, filter);
		print("dilate", out2);
		array out = erode(in, filter);
		print("erode", out);
```

and output looks about right:

```
ArrayFire v3.5.1 (CUDA, 64-bit Windows, build 0a675e8)
Platform: CUDA Toolkit 8, Driver: CUDA Driver Version: 9000
[0] GeForce GTX 1070, 8192 MB, CUDA Compute 6.1
in
[4 4 1 1]
    0.0000     0.0000     0.0000     0.0000
    0.0000     1.0000     1.0000     0.0000
    0.0000     0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000

filter
[2 2 1 1]
    1.0000     1.0000
    1.0000     1.0000

dilate
[4 4 1 1]
      -inf     0.0000     1.0000     1.0000
    0.0000     0.0000     1.0000     1.0000
    0.0000     1.0000     1.0000     1.0000
    0.0000     0.0000     0.0000     0.0000

erode
[4 4 1 1]
       inf     0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000
```

**Comment by 9prady9** [comment] 2017-10-05 04:49
@nikkadim We are able to reproduce the issue on our end with snippet you shared in your latest comment. We are looking into it.

**Comment by pavanky** [comment] 2017-10-05 05:18
@nikkadim The latest code only seems to be an issue for even sized filters. But you seem to be using odd sized kernels in the original code.. It could potentially be multiple issues..

**Comment by nikkadim** [comment] 2017-10-09 19:50
Could you suggest any workaround until 3.5.2?

**Comment by 9prady9** [comment] 2017-10-10 10:21
@nikkadim Which problem are you referring to - black images while saving them to disk ? or some values being infinities ?

**Comment by nikkadim** [comment] 2017-10-10 20:06
@9prady9 actual values after filtering.

**Comment by 9prady9** [comment] 2017-10-11 06:11
For a fix in filtering(erode/dilate), I am afraid you have to wait for the 3.5.2 release - no ETA on that as of now. 

If you want to build ArrayFire yourself, you can follow the instructions [here on wiki](https://github.com/arrayfire/arrayfire/wiki) and you can apply the patch from (this github PR](https://github.com/arrayfire/arrayfire/pull/1944). If you do try this route, please let us know if you face any issues and we can help you out.

**Closed** 2017-12-29 15:39 UTC
Labels: bug, CUDA, OpenCL
