### ISSUE TITLE
Linear Algebra is disabled on OpenCL

### ISSUE THREAD

**Issue by Brainiarc7** [arrayfire/arrayfire#1419] opened 2016-05-17 06:37 UTC
Hello there,

I'm currently running an Arrayfire benchmark on some new hardware and I'm coming across this error:

ArrayFire Exception (Function not configured to build:302):
In function cholesky
In file src/backend/opencl/cholesky.cpp:92
Linear Algebra is disabled on OpenCL

In function int af::cholesky(af::array&, const af::array&, bool)
In file src/api/cpp/lapack.cpp:86

Is there a way I can configure Arrayfire to enable this feature or is it disabled intentionally?

Thanks and regards,

Brainiarc7

**Comment by pavanky** [comment] 2016-05-17 10:47
@Brainiarc7 Linear algebra is disabled if CPU backend or OpenCL backend can not find `liblapacke` library on Linux.

**Comment by Brainiarc7** [comment] 2016-05-17 12:36
Hello,

I have already installed liblapacke on Ubuntu as instructed on the wiki.

Currently running Ubuntu 16.04

**Comment by shehzan10** [comment] 2016-05-17 13:31
Did you install liblapack too?

Can you paste the output of `cmake -LA | grep -i lapack` and `cmake -LA | grep -i blas`.

**Comment by shehzan10** [comment] 2016-05-17 18:13
Can you edit `CMakeModules/FindLAPACKE.cmake` and before the last `MARK_AS_ADVANCED`, add:

```
MESSAGE("LAPACKE_ROOT_DIR   :   ${LAPACKE_ROOT_DIR}")
MESSAGE("LAPACK_INCLUDES    :   ${LAPACK_INCLUDES}")
MESSAGE("LAPACKE_INCLUDES   :   ${LAPACKE_INCLUDES}")
MESSAGE("LAPACKE_INCLUDE_DIR:   ${LAPACKE_INCLUDE_DIR}")
MESSAGE("LAPACK_LIB         :   ${LAPACK_LIB}")
MESSAGE("LAPACKE_LIB        :   ${LAPACKE_LIB}")
MESSAGE("LAPACK_LIBRARIES   :   ${LAPACK_LIBRARIES}")
```

**Comment by Brainiarc7** [comment] 2016-05-18 00:32
Here you go:

LAPACKE_ROOT_DIR   :   
LAPACK_INCLUDES    :   
LAPACKE_INCLUDES   :   /usr/include
LAPACKE_INCLUDE_DIR:   
LAPACK_LIB         :   
LAPACKE_LIB        :   /usr/lib/liblapacke.so;/usr/lib/liblapack.so;/usr/lib/libblas.so
LAPACK_LIBRARIES   :   
CMake Warning at src/backend/cpu/CMakeLists.txt:75 (MESSAGE):
  LAPACK not found.  Functionality will be disabled

**Comment by shehzan10** [comment] 2016-05-18 00:44
I'm not entirely sure whether you set those manually.
If one of `LAPACKE_LIB` or `LAPACK_LIB` are not defined, then `LAPACK_LIBRARIES` is not defined ([source](https://github.com/arrayfire/arrayfire/blob/devel/CMakeModules/FindLAPACKE.cmake#L146)) - and `LAPACK_LIBRARIES` are required by the argument handler.

So if you are defining those manually, you are better of defining `LAPACK_LIBRARIES` and `LAPACK_INCLUDE_DIR`.

**Comment by marbre** [comment] 2016-05-18 08:37
I have a similar issue while trying to upgrade the Gentoo ebuild to arrayfire 3.3.2:

```
-- Found LAPACKE: /usr/lib64/libreflapacke.so;/usr/lib64/libptlapack.so;/usr/lib64/libptcblas.so;/usr/lib64/libptf77blas.so  
-- Could NOT find LAPACK (missing:  LAPACK_LIBRARIES) 
CMake Warning at src/backend/cpu/CMakeLists.txt:71 (MESSAGE):
  LAPACK not found.  Functionality will be disabled
```

The changes pushed with commit d4fb656e09dd89994ae65bf643cfefe2f58f3f47 to `CMakeModules/FindLAPACKE.cmake` cause the problem. `LAPACKE_LIB` is set, but since `LAPACK_LIB` is not, `LAPACK_LIBRARIES` is finally not set.

**Comment by 9prady9** [comment] 2016-05-18 11:20
@marbre & @Brainiarc7 
 We have been able to reproduce this issue on our end and we are looking into it.

**Comment by 9prady9** [comment] 2016-05-18 12:08
@marbre and @Brainiarc7 
As a temporary work around, please try the following patch to arrayfire source and see if that fixes your issue.

```diff
diff --git a/CMakeModules/FindLAPACKE.cmake b/CMakeModules/FindLAPACKE.cmake
index 9251ee9..ad919c1 100644
--- a/CMakeModules/FindLAPACKE.cmake
+++ b/CMakeModules/FindLAPACKE.cmake
@@ -45,6 +45,12 @@ IF(PC_LAPACKE_FOUND)
       IF (NOT ${PC_LIB}_LIBRARY)
         MESSAGE(FATAL_ERROR "Something is wrong in your pkg-config file - lib ${PC_LIB} not found in ${PC_LAPACKE_LIBRARY_DIRS}")
       ENDIF (NOT ${PC_LIB}_LIBRARY)
+
+      STRING(TOUPPER ${PC_LIB} TRGT_NAME)
+      IF (${TRGT_NAME} STREQUAL "LAPACK")
+          SET(LAPACK_LIB ${${PC_LIB}_LIBRARY})
+      ENDIF()
+
       LIST(APPEND LAPACKE_LIB ${${PC_LIB}_LIBRARY})
     ENDFOREACH(PC_LIB)
```

**Comment by marbre** [comment] 2016-05-18 12:16
@9prady9 Thanks for taking care. Unfortunately, the patch does not fix the problem on Gentoo.

**Comment by Brainiarc7** [comment] 2016-05-18 13:30
Alright, I'll test this patch and provide feedback.

**Comment by shehzan10** [comment] 2016-05-18 13:57
@marbre the commit you reference is fine. The problem really is that the LAPACK_LIB is not being found because (I think) lapacke is being found using package config and never goes to the else part that actually sets the libraries.

I think the package config part is whats making it not work for @Brainiarc7 too.

The solution for this would be to exclude the `LAPACKE_LIB AND LAPACK_LIB` condition if it used package config.

PS. You can confirm the package config part by putting `MESSAGE("In PkgConfig Section")` and a different message in the else part. This should narrow it down.

**Comment by shehzan10** [comment] 2016-05-18 14:02
Try this patch
```
-IF(LAPACKE_LIB AND LAPACK_LIB)
+IF(PC_LAPACKE_FOUND OR (LAPACKE_LIB AND LAPACK_LIB))
```

**Comment by Brainiarc7** [comment] 2016-05-18 14:12
Will test.

The first build run is still in progress.

**Comment by marbre** [comment] 2016-05-18 14:16
@shehzan10 You are absolutely right, LAPACKE is found by pkgconfig. My first comment on this issue might not have been detailed enough. `SET(LAPACK_LIBRARIES ${LAPACKE_LIB} ${LAPACK_LIB})` was executed unconditionally before commit d4fb656e09dd89994ae65bf643cfefe2f58f3f47, which I wanted to point out.

Your patch solves the problem. I just did not realized that the condition might be change in that a simple way. Thank you for the quick reply.

**Comment by shehzan10** [comment] 2016-05-18 14:17
Thanks for the update. I'll push the patch.

**Comment by Brainiarc7** [comment] 2016-05-18 14:39
Hello there, 

The patch seems to have corrected the problem.

I can now run LAPACK's Cholesky OpenCL routines with the benchmark utility, thanks.
Will let you know if any other feature test fails :-)

**Comment by Brainiarc7** [comment] 2016-05-23 13:45
Marking issue as closed as it has been solved by an issued patch.

**Comment by pavanky** [comment] 2016-05-23 13:59
@Brainiarc7 This will be closed when the patch is merged into devel.

**Comment by Brainiarc7** [comment] 2016-05-23 14:01
Alright, thanks for the notification.

**Closed** 2016-05-23 19:15 UTC
Labels: bug, build, CPU, OpenCL
