### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by munnybearz** [arrayfire/arrayfire#1993] opened 2017-11-16 09:50 UTC
Hi guys,

Building the latest Arrayfire master on EC2 g3.4xlarge Ubuntu 16.04 with the latest nvidia drivers and CUDA 9. The unit test fast_cuda and orb_cuda fails. All other cpu and cuda tests pass (except meanshift_cpu which took 15+ minutes so I killed it out of impatiance).

        Start  54: fast_cpu
 54/229 Test  #54: fast_cpu .........................   Passed    0.17 sec
        Start  55: fast_cuda
 55/229 Test  #55: fast_cuda ........................***Failed    3.04 sec

        Start 144: orb_cpu
144/229 Test #144: orb_cpu ..........................   Passed    1.15 sec
        Start 145: orb_cuda
145/229 Test #145: orb_cuda .........................***Failed    2.07 sec

**Comment by meister87** [comment] 2017-11-21 14:57
Checked out the current version today:
Build it and got a large number of failing tests.

> The following tests FAILED:
	  1 - approx1_cpu (SEGFAULT)
	  2 - approx1_cuda (SEGFAULT)
	  3 - approx1_opencl (SEGFAULT)
	  4 - approx2_cpu (SEGFAULT)
	  5 - approx2_cuda (SEGFAULT)
	  6 - approx2_opencl (SEGFAULT)
	 10 - assign_cpu (SEGFAULT)
	 11 - assign_cuda (SEGFAULT)
	 12 - assign_opencl (SEGFAULT)
	 23 - bilateral_cpu (SEGFAULT)
	 24 - bilateral_cuda (SEGFAULT)
	 25 - bilateral_opencl (SEGFAULT)
	 29 - blas_cpu (SEGFAULT)
	 30 - blas_cuda (SEGFAULT)
	 31 - blas_opencl (SEGFAULT)
	 32 - canny_cpu (SEGFAULT)
	 33 - canny_cuda (SEGFAULT)
	 34 - canny_opencl (SEGFAULT)
	 53 - convolve_cpu (SEGFAULT)
	 54 - convolve_cuda (SEGFAULT)
	 55 - convolve_opencl (SEGFAULT)
	 56 - corrcoef_cpu (SEGFAULT)
	 57 - corrcoef_cuda (SEGFAULT)
	 58 - corrcoef_opencl (SEGFAULT)
	 59 - covariance_cpu (SEGFAULT)
	 60 - covariance_cuda (SEGFAULT)
	 61 - covariance_opencl (SEGFAULT)
	 65 - diff1_cpu (SEGFAULT)
	 66 - diff1_cuda (SEGFAULT)
	 67 - diff1_opencl (SEGFAULT)
	 68 - diff2_cpu (SEGFAULT)
	 69 - diff2_cuda (SEGFAULT)
	 70 - diff2_opencl (SEGFAULT)
	 74 - dot_cpu (SEGFAULT)
	 75 - dot_cuda (SEGFAULT)
	 76 - dot_opencl (SEGFAULT)
	 80 - fast_cpu (SEGFAULT)
	 81 - fast_cuda (SEGFAULT)
	 82 - fast_opencl (SEGFAULT)
	 83 - fft_cpu (SEGFAULT)
	 84 - fft_cuda (SEGFAULT)
	 85 - fft_opencl (SEGFAULT)
	 92 - fftconvolve_cpu (SEGFAULT)
	 93 - fftconvolve_cuda (SEGFAULT)
	 94 - fftconvolve_opencl (SEGFAULT)
	101 - gaussiankernel_cpu (SEGFAULT)
	102 - gaussiankernel_cuda (SEGFAULT)
	103 - gaussiankernel_opencl (SEGFAULT)
	104 - gen_assign_cpu (SEGFAULT)
	105 - gen_assign_cuda (SEGFAULT)
	106 - gen_assign_opencl (SEGFAULT)
	107 - gen_index_cpu (SEGFAULT)
	108 - gen_index_cuda (SEGFAULT)
	109 - gen_index_opencl (SEGFAULT)
	116 - gradient_cpu (SEGFAULT)
	117 - gradient_cuda (SEGFAULT)
	118 - gradient_opencl (SEGFAULT)
	122 - hamming_cpu (SEGFAULT)
	123 - hamming_cuda (SEGFAULT)
	124 - hamming_opencl (SEGFAULT)
	125 - harris_cpu (SEGFAULT)
	126 - harris_cuda (SEGFAULT)
	127 - harris_opencl (SEGFAULT)
	128 - histogram_cpu (SEGFAULT)
	129 - histogram_cuda (SEGFAULT)
	130 - histogram_opencl (SEGFAULT)
	131 - homography_cpu (SEGFAULT)
	132 - homography_cuda (SEGFAULT)
	133 - homography_opencl (SEGFAULT)
	134 - hsv_rgb_cpu (SEGFAULT)
	135 - hsv_rgb_cuda (SEGFAULT)
	136 - hsv_rgb_opencl (SEGFAULT)
	137 - iir_cpu (SEGFAULT)
	138 - iir_cuda (SEGFAULT)
	139 - iir_opencl (SEGFAULT)
	140 - imageio_cpu (SEGFAULT)
	141 - imageio_cuda (SEGFAULT)
	142 - imageio_opencl (SEGFAULT)
	143 - index_cpu (SEGFAULT)
	144 - index_cuda (SEGFAULT)
	145 - index_opencl (SEGFAULT)
	153 - inverse_dense_cuda (Failed)
	164 - join_cpu (SEGFAULT)
	165 - join_cuda (SEGFAULT)
	166 - join_opencl (SEGFAULT)
	167 - lu_dense_cpu (SEGFAULT)
	168 - lu_dense_cuda (SEGFAULT)
	169 - lu_dense_opencl (SEGFAULT)
	173 - match_template_cpu (SEGFAULT)
	174 - match_template_cuda (SEGFAULT)
	175 - match_template_opencl (SEGFAULT)
	182 - mean_cpu (SEGFAULT)
	183 - mean_cuda (SEGFAULT)
	184 - mean_opencl (SEGFAULT)
	185 - meanshift_cpu (Failed)
	186 - meanshift_cuda (Failed)
	187 - meanshift_opencl (Failed)
	188 - medfilt_cpu (SEGFAULT)
	189 - medfilt_cuda (SEGFAULT)
	190 - medfilt_opencl (SEGFAULT)
	203 - moddims_cpu (SEGFAULT)
	204 - moddims_cuda (SEGFAULT)
	205 - moddims_opencl (SEGFAULT)
	206 - moments_cpu (SEGFAULT)
	207 - moments_cuda (SEGFAULT)
	208 - moments_opencl (SEGFAULT)
	209 - morph_cpu (SEGFAULT)
	210 - morph_cuda (SEGFAULT)
	211 - morph_opencl (SEGFAULT)
	212 - nearest_neighbour_cpu (SEGFAULT)
	213 - nearest_neighbour_cuda (SEGFAULT)
	214 - nearest_neighbour_opencl (SEGFAULT)
	218 - orb_cpu (SEGFAULT)
	219 - orb_cuda (SEGFAULT)
	220 - orb_opencl (SEGFAULT)
	221 - qr_dense_cpu (SEGFAULT)
	222 - qr_dense_cuda (SEGFAULT)
	223 - qr_dense_opencl (SEGFAULT)
	230 - rank_dense_cpu (SEGFAULT)
	231 - rank_dense_cuda (SEGFAULT)
	232 - rank_dense_opencl (SEGFAULT)
	233 - reduce_cpu (SEGFAULT)
	234 - reduce_cuda (SEGFAULT)
	235 - reduce_opencl (SEGFAULT)
	236 - regions_cpu (SEGFAULT)
	237 - regions_cuda (SEGFAULT)
	238 - regions_opencl (SEGFAULT)
	239 - reorder_cpu (SEGFAULT)
	240 - reorder_cuda (SEGFAULT)
	241 - reorder_opencl (SEGFAULT)
	245 - resize_cpu (SEGFAULT)
	246 - resize_cuda (SEGFAULT)
	247 - resize_opencl (SEGFAULT)
	248 - rotate_cpu (SEGFAULT)
	249 - rotate_cuda (SEGFAULT)
	250 - rotate_opencl (SEGFAULT)
	251 - rotate_linear_cpu (SEGFAULT)
	252 - rotate_linear_cuda (SEGFAULT)
	253 - rotate_linear_opencl (SEGFAULT)
	257 - scan_cpu (SEGFAULT)
	258 - scan_cuda (SEGFAULT)
	259 - scan_opencl (SEGFAULT)
	266 - set_cpu (Failed)
	267 - set_cuda (Failed)
	268 - set_opencl (Failed)
	269 - shift_cpu (SEGFAULT)
	270 - shift_cuda (SEGFAULT)
	271 - shift_opencl (SEGFAULT)
	272 - sobel_cpu (SEGFAULT)
	273 - sobel_cuda (SEGFAULT)
	274 - sobel_opencl (SEGFAULT)
	276 - solve_dense_cuda (Failed)
	277 - solve_dense_opencl (Failed)
	278 - sort_cpu (SEGFAULT)
	279 - sort_cuda (SEGFAULT)
	280 - sort_opencl (SEGFAULT)
	281 - sort_by_key_cpu (SEGFAULT)
	282 - sort_by_key_cuda (SEGFAULT)
	283 - sort_by_key_opencl (SEGFAULT)
	284 - sort_index_cpu (SEGFAULT)
	285 - sort_index_cuda (SEGFAULT)
	286 - sort_index_opencl (SEGFAULT)
	292 - sparse_arith_opencl (OTHER_FAULT)
	296 - stdev_cpu (SEGFAULT)
	297 - stdev_cuda (SEGFAULT)
	298 - stdev_opencl (SEGFAULT)
	299 - susan_cpu (Failed)
	300 - susan_cuda (Failed)
	301 - susan_opencl (Failed)
	305 - threading_cpu (SEGFAULT)
	306 - threading_cuda (SEGFAULT)
	307 - threading_opencl (SEGFAULT)
	308 - tile_cpu (SEGFAULT)
	309 - tile_cuda (SEGFAULT)
	310 - tile_opencl (SEGFAULT)
	311 - transform_cpu (SEGFAULT)
	312 - transform_cuda (SEGFAULT)
	313 - transform_opencl (SEGFAULT)
	314 - transform_coordinates_cpu (SEGFAULT)
	315 - transform_coordinates_cuda (SEGFAULT)
	316 - transform_coordinates_opencl (SEGFAULT)
	317 - translate_cpu (SEGFAULT)
	318 - translate_cuda (SEGFAULT)
	319 - translate_opencl (SEGFAULT)
	320 - transpose_cpu (SEGFAULT)
	321 - transpose_cuda (SEGFAULT)
	322 - transpose_opencl (SEGFAULT)
	329 - unwrap_cpu (SEGFAULT)
	330 - unwrap_cuda (SEGFAULT)
	331 - unwrap_opencl (SEGFAULT)
	332 - var_cpu (Failed)
	333 - var_cuda (Failed)
	334 - var_opencl (Failed)
	335 - where_cpu (SEGFAULT)
	336 - where_cuda (SEGFAULT)
	337 - where_opencl (SEGFAULT)
	344 - ycbcr_rgb_cpu (SEGFAULT)
	345 - ycbcr_rgb_cuda (SEGFAULT)
	346 - ycbcr_rgb_opencl (SEGFAULT)

Most tests failed based on segfaults.
Unfortunately, I did not know why

**Comment by 9prady9** [comment] 2017-11-22 04:18
@munnybearz I can't say EC2 instance but I use a normal installation of Ubuntu 16.04(Elementary OS) with CUDA 7.5(with driver 384.90) on current master branch and tests work as expected. What is the driver version you have ?

Can you do `export AF_PRINT_ERRORS=1` and run an individual test(any test, info_opencl or info_cuda are the simplest) and share the output shown by those tests.

**Comment by meister87** [comment] 2017-11-22 10:19
Hi,
Thanks for the hint. most of the segfaults were caused by missing test data.
After including the test data most test cases successfully pass.

Some fail because of timeouts of the GPU.
Considering the timeouts, there is some strang behaviour of my machine.
Sometimes not only the execution of the test is killed, but also my complete desktop crashes.

For the other tests, I attached the  output of the single runs:

> Running main() from gtest_main.cc
> [==========] Running 13 tests from 7 test cases.
> [----------] Global test environment set-up.
> [----------] 2 tests from FloatFAST/0, where TypeParam = float
> [ RUN      ] FloatFAST/0.square
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 241
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 3
> 
> [  FAILED  ] FloatFAST/0.square, where TypeParam = float (866 ms)
> [ RUN      ] FloatFAST/0.square_nonmax
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FloatFAST/0.square_nonmax, where TypeParam = float (5 ms)
> [----------] 2 tests from FloatFAST/0 (872 ms total)
> 
> [----------] 2 tests from FloatFAST/1, where TypeParam = double
> [ RUN      ] FloatFAST/1.square
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 241
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 3
> 
> [  FAILED  ] FloatFAST/1.square, where TypeParam = double (5 ms)
> [ RUN      ] FloatFAST/1.square_nonmax
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FloatFAST/1.square_nonmax, where TypeParam = double (5 ms)
> [----------] 2 tests from FloatFAST/1 (10 ms total)
> 
> [----------] 2 tests from FixedFAST/0, where TypeParam = int
> [ RUN      ] FixedFAST/0.square
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 241
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 3
> 
> [  FAILED  ] FixedFAST/0.square, where TypeParam = int (5 ms)
> [ RUN      ] FixedFAST/0.square_nonmax
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FixedFAST/0.square_nonmax, where TypeParam = int (5 ms)
> [----------] 2 tests from FixedFAST/0 (10 ms total)
> 
> [----------] 2 tests from FixedFAST/1, where TypeParam = unsigned int
> [ RUN      ] FixedFAST/1.square
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 241
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 3
> 
> [  FAILED  ] FixedFAST/1.square, where TypeParam = unsigned int (4 ms)
> [ RUN      ] FixedFAST/1.square_nonmax
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FixedFAST/1.square_nonmax, where TypeParam = unsigned int (5 ms)
> [----------] 2 tests from FixedFAST/1 (10 ms total)
> 
> [----------] 2 tests from FixedFAST/2, where TypeParam = short
> [ RUN      ] FixedFAST/2.square
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 241
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 3
> 
> [  FAILED  ] FixedFAST/2.square, where TypeParam = short (4 ms)
> [ RUN      ] FixedFAST/2.square_nonmax
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FixedFAST/2.square_nonmax, where TypeParam = short (6 ms)
> [----------] 2 tests from FixedFAST/2 (10 ms total)
> 
> [----------] 2 tests from FixedFAST/3, where TypeParam = unsigned short
> [ RUN      ] FixedFAST/3.square
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 241
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 3
> 
> [  FAILED  ] FixedFAST/3.square, where TypeParam = unsigned short (5 ms)
> [ RUN      ] FixedFAST/3.square_nonmax
> /home/ameister/repositories/arrayfire/test/fast.cpp:134: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FixedFAST/3.square_nonmax, where TypeParam = unsigned short (5 ms)
> [----------] 2 tests from FixedFAST/3 (10 ms total)
> 
> [----------] 1 test from FloatFAST
> [ RUN      ] FloatFAST.CPP
> /home/ameister/repositories/arrayfire/test/fast.cpp:214: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 399
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 1
> 
> [  FAILED  ] FloatFAST.CPP (4 ms)
> [----------] 1 test from FloatFAST (4 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 13 tests from 7 test cases ran. (926 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 13 tests, listed below:
> [  FAILED  ] FloatFAST/0.square, where TypeParam = float
> [  FAILED  ] FloatFAST/0.square_nonmax, where TypeParam = float
> [  FAILED  ] FloatFAST/1.square, where TypeParam = double
> [  FAILED  ] FloatFAST/1.square_nonmax, where TypeParam = double
> [  FAILED  ] FixedFAST/0.square, where TypeParam = int
> [  FAILED  ] FixedFAST/0.square_nonmax, where TypeParam = int
> [  FAILED  ] FixedFAST/1.square, where TypeParam = unsigned int
> [  FAILED  ] FixedFAST/1.square_nonmax, where TypeParam = unsigned int
> [  FAILED  ] FixedFAST/2.square, where TypeParam = short
> [  FAILED  ] FixedFAST/2.square_nonmax, where TypeParam = short
> [  FAILED  ] FixedFAST/3.square, where TypeParam = unsigned short
> [  FAILED  ] FixedFAST/3.square_nonmax, where TypeParam = unsigned short
> [  FAILED  ] FloatFAST.CPP
> 
> 13 FAILED TESTS
> 
> Running main() from gtest_main.cc
> [==========] Running 5 tests from 3 test cases.
> [----------] Global test environment set-up.
> [----------] 2 tests from ORB/0, where TypeParam = float
> [ RUN      ] ORB/0.Square
> /home/ameister/repositories/arrayfire/test/orb.cpp:203: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 0
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 0
> 
> [  FAILED  ] ORB/0.Square, where TypeParam = float (832 ms)
> [ RUN      ] ORB/0.Lena
> /home/ameister/repositories/arrayfire/test/orb.cpp:204: Failure
> Expected equality of these values:
>   out_feat[elIter].f[1]
>     Which is: 411
>   gold_feat[elIter].f[1]
>     Which is: 423
> at: 0
> 
> [  FAILED  ] ORB/0.Lena, where TypeParam = float (19 ms)
> [----------] 2 tests from ORB/0 (852 ms total)
> 
> [----------] 2 tests from ORB/1, where TypeParam = double
> [ RUN      ] ORB/1.Square
> /home/ameister/repositories/arrayfire/test/orb.cpp:203: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 0
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 0
> 
> [  FAILED  ] ORB/1.Square, where TypeParam = double (8 ms)
> [ RUN      ] ORB/1.Lena
> /home/ameister/repositories/arrayfire/test/orb.cpp:204: Failure
> Expected equality of these values:
>   out_feat[elIter].f[1]
>     Which is: 419
>   gold_feat[elIter].f[1]
>     Which is: 423
> at: 0
> 
> [  FAILED  ] ORB/1.Lena, where TypeParam = double (25 ms)
> [----------] 2 tests from ORB/1 (34 ms total)
> 
> [----------] 1 test from ORB
> [ RUN      ] ORB.CPP
> /home/ameister/repositories/arrayfire/test/orb.cpp:294: Failure
> Expected equality of these values:
>   out_feat[elIter].f[0]
>     Which is: 0
>   gold_feat[elIter].f[0]
>     Which is: 240
> at: 0
> 
> [  FAILED  ] ORB.CPP (7 ms)
> [----------] 1 test from ORB (7 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 5 tests from 3 test cases ran. (894 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 5 tests, listed below:
> [  FAILED  ] ORB/0.Square, where TypeParam = float
> [  FAILED  ] ORB/0.Lena, where TypeParam = float
> [  FAILED  ] ORB/1.Square, where TypeParam = double
> [  FAILED  ] ORB/1.Lena, where TypeParam = double
> [  FAILED  ] ORB.CPP
> 
>  5 FAILED TESTS
> 
> [----------] 4 tests from QR/3, where TypeParam = af::af_cdouble
> [ RUN      ] QR/3.RectangularLarge0
> /home/ameister/repositories/arrayfire/test/qr_dense.cpp:110: Failure
> The difference between 0 and af::max<double>(af::abs(real(re - in))) is 1.9320362071438069, which exceeds eps, where
> 0 evaluates to 0,
> af::max<double>(af::abs(real(re - in))) evaluates to 1.9320362071438069, and
> eps evaluates to 1.0000000000000001e-05.
> [  FAILED  ] QR/3.RectangularLarge0, where TypeParam = af::af_cdouble (1518 ms)
> [ RUN      ] QR/3.RectangularMultipleOfTwoLarge0
> [       OK ] QR/3.RectangularMultipleOfTwoLarge0 (759 ms)
> [ RUN      ] QR/3.RectangularLarge1
> [       OK ] QR/3.RectangularLarge1 (2374 ms)
> [ RUN      ] QR/3.RectangularMultipleOfTwoLarge1
> [       OK ] QR/3.RectangularMultipleOfTwoLarge1 (433 ms)
> [----------] 4 tests from QR/3 (5084 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 17 tests from 5 test cases ran. (13501 ms total)
> [  PASSED  ] 16 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] QR/3.RectangularLarge0, where TypeParam = af::af_cdouble
> 
> 
> 22 FAILED TESTS
> [ RUN      ] Solve/3.LeastSquaresOverDetermined
> /home/ameister/repositories/arrayfire/test/solve_common.hpp:59: Failure
> The difference between 0 and af::sum<typename af::dtype_traits<T>::base_type>(af::abs(real(B0 - B1))) / (m * k) is 1.9012503669890457, which exceeds eps, where
> 0 evaluates to 0,
> af::sum<typename af::dtype_traits<T>::base_type>(af::abs(real(B0 - B1))) / (m * k) evaluates to 1.9012503669890457, and
> eps evaluates to 1.0000000000000001e-05.
> [  FAILED  ] Solve/3.LeastSquaresOverDetermined, where TypeParam = af::af_cdouble (32 ms)
> [----------] 24 tests from Solve/3 (19937 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 96 tests from 4 test cases ran. (37790 ms total)
> [  PASSED  ] 95 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] Solve/3.LeastSquaresOverDetermined, where TypeParam = af::af_cdouble
> 
>  1 FAILED TEST

For these tests, the execution seems to be fine, but not the correct result seems to be returned.

Furthermore, I still have some test crashing based on segfaults.
Unfortunately, no further messages are provided

> [ RUN      ] Harris/0.lena_0_3
> Speicherzugriffsfehler (Speicherabzug geschrieben)
> [ RUN      ] Homography/0.Tux_RANSAC
> Speicherzugriffsfehler (Speicherabzug geschrieben)
> [RUN      ] ORB/0.Lena
> Speicherzugriffsfehler (Speicherabzug geschrieben)
> [ RUN      ] SortByKey/0.Sort0True
> *** stack smashing detected ***: ./sort_by_key_opencl terminated
> Abgebrochen (Speicherabzug geschrieben)
> [ RUN      ] SortIndex/0.Sort10x10False
> Speicherzugriffsfehler (Speicherabzug geschrieben)
> [ RUN      ] SPARSE_ARITH.float_MUL_10_10
> *** stack smashing detected ***: ./sparse_arith_opencl terminated
> Abgebrochen (Speicherabzug geschrieben)

While executing some tests also the following warning popped up sometimes.
> Warning:  Program terminating, but clFFT resources not freed.
> Please consider explicitly calling clfftTeardown( ).

Unfortunately, I cannot map the warning to a specific test case, because I pipelined the output to a file

**Comment by 9prady9** [comment] 2017-11-22 10:40
You can safely ignore the clFFT warnings.

What GPU are you running these tests on ? Also please give driver version. Is it windows you are working on ?

**Comment by meister87** [comment] 2017-11-22 11:14
I executed the tests on a system with Ubuntu 16.04, Geforce GTX 960M, with the driver 384.90 (nvidia-384)

**Comment by 9prady9** [comment] 2017-11-22 13:14
I am using same OS & driver with GT 650M. All the tests passed fine on my machine. I wonder if it is because it is a Maxwell card. @umar456 What do you think? Do we have any "M" versions of Maxwell arch in-house ?

**Comment by 9prady9** [comment] 2017-12-01 12:43
@munnybearz Can you please share your driver details.

**Comment by munnybearz** [comment] 2017-12-17 11:44
@9prady9 info_cuda gives me:

> ArrayFire v3.6.0 (CUDA, 64-bit Linux, build 360b0d6)
> Platform: CUDA Toolkit 9, Driver: 384.90
> [0] Tesla M60, 7614 MB, CUDA Compute 5.2

btw this issue is a lower priority from my side as I haven't been using EC2 much recently

**Comment by 9prady9** [comment] 2017-12-17 11:56
@munnybearz I believe these failures are addressed in PR https://github.com/arrayfire/arrayfire/pull/2019 Fast and Orb and doesn't fail with CUDA 9 anymore on our build servers. Please verify it on your end as well. Closing the issue for now. Feel free to reopen if you are still seeing the problem on master after PR 2019.

**Closed by 9prady9** 2017-12-17 11:56 UTC
