### ISSUE TITLE
bug:  scalar + vector behaviour is wrong

### ISSUE THREAD

**Issue by Pascal-J** [arrayfire/arrayfire#1022] opened 2015-09-25 02:00 UTC
The correct behaviour for scalar + vector should be:  (J code)

      7 7 7 7 7 + i.5
    7 8 9 10 11
      7 + i.5
    7 8 9 10 11

arrayfire gets the vector + vector equivalent version right, but for the scalar + vector:

      'J a_base_ =. Achk i.5' inl <'afopencl'
    0 1 2 3 4
      'J b_base_ =. Achk 7' inl <'afopencl'
    7
      'JR a_base_ add~ b_base_ ' inl <'afopencl'  NB. tilde inverts lhs and rhs
    7 1 9 3 11
      'JR a_base_ add b_base_ ' inl <'afopencl'
    7 1 9 3 11

Note that the 7 (b_base_) is an array of size 1.  Is there a different constructor for a scalar?

Preferable to the above behaviour would be returning an error, if array of size and dim 1 is not a scalar.

Note: While I don't understand what batch mode does, setting it to false, does raise an error on this operation.

**Comment by umar456** [comment] 2015-09-25 11:13
I am not sure how you implemented the `add` function but I think the issue is popping up because you need to use the constant function to create the `b_base_` array that has the same size as the `a_base_` array. `constant` is a JIT function so memory will not be allocated and the operation will be performed as expected. You can look at the C++ binding's [`operator+`](https://github.com/arrayfire/arrayfire/blob/devel/src/api/cpp/array.cpp#L895) function to reference how to perform this operation.

**Comment by Pascal-J** [comment] 2015-09-25 14:57
interesting approach.  From the function signatures for constant, they are vectors (or higher dimensioned) arrays.  The behaviour of a scalar array when applied to a vector (with a basic  function (rank 0 functions such as + - * exp div mod) is to (should) behave as though it is auto expanded into a "constant".

I haven't looked at behaviour of constant yet, and if it does this, that is quite cool.  You can add the same constant to a vector or table, and it is JIT reshaped to produce the right result under add, mul etc?

If that is the case, then the decision to use create array vs. constant is simply whether you want to embrace or avoid this JIT behaviour?  That is either a cool feature, or a feature request.

there is still a bug in that with batch mode = 1, nonsense is returned with arrays created directly with create array.

**Comment by 9prady9** [comment] 2015-09-25 15:42
@Pascal-J 

I have tested the following snippets on current master and both of them seem to work fine on CPU, OpenCL backends. 

First snippet uses `af_create_array` and the later `af_constant` to create the `af_array`'s.
```
const dim_t d0[] = {1};
const float da0[] = {3.0};
af_array a = 0;
af_create_array(&a, da0, 1, d0, f32);
af_print_array(a);

const dim_t d1[] = {4};
const float da1[] = {0.0, 1.0, 2.0, 3.0};
af_array b = 0;
af_create_array(&b, da1, 1, d1, f32);
af_print_array(b);
  
af_array c = 0;
af_add(&c, a, b, true);
af_print_array(c);
```

```
const dim_t d0[] = {1};
af_array a = 0;
af_constant(&a, 3.0, 1, {1}, f32);
af_print_array(a);

const dim_t d1[] = {4};
af_array b = 0;
af_constant(&b, 1.0, 1, {4}, f32);
af_print_array(b);

af_array c = 0;
af_add(&c, a, b, true);
af_print_array(c);
```

Can you please check if you are using the latest release(3.1.1).

**Comment by Pascal-J** [comment] 2015-09-25 16:21
I am using 3.1.1.  The difference in my test is that my cover function for array_create (A) uses s64 as data type.  Both 7 and 0 1 2 3 4 below are s64.

The specific nonsense result of 7 1 9 3 11 (from 7 + 0 1 2 3 4) has a pattern to it, the result is 7 0 7 0 7 + 0 1 2 3 4 .  That looks to me as though there is a mistaken expansion that takes the 64bit number 7 as 2 32 bit numbers 7 0.

**Comment by 9prady9** [comment] 2015-09-25 16:38
Yes, i noticed the pattern of even indices with wrong values. Will check the code with `s64` now.

**Comment by 9prady9** [comment] 2015-09-25 16:57
I have just tried the above snippets by changing the data to be `s64` and the snippets gave correct results on my end.

**Comment by pavanky** [comment] 2015-09-26 15:29
@Pascal-J Please try to write the same code in C and see if the bug exists. We can not debug J code on our end. If the code works fine in C but fails in J, the problem lies  in the J wrapper rather than C. 

This is the reason I asked you to create a new repo for the J wrapper because that would be more appropriate place to discuss issues like this. 

It looks like @9prady9 tried the code snippet in C and is unable to reproduce the error. I am closing the issue unless a C code snippet reproduces the problem.

**Closed by pavanky** 2015-09-26 15:29 UTC
