### ISSUE TITLE
spdlog-utests not build although ENABLE_TESTING is set to on

### ISSUE THREAD

**Issue by StefanBruens** [arrayfire/arrayfire#2685] opened 2019-12-04 00:02 UTC
As `extern/spdlog` has `EXCLUDE_FROM_ALL` set, spdlog-utests is not build.

When the testsuite is run via `ctest`, spdlog-utest is picked up as a target (as CMake decends into the directory and `enable_testing()` is set), but obviously it can not run it.

**Comment by 9prady9** [comment] 2019-12-04 12:57
I am unable to grasp the cause of concern to be honest.

Do we need to build tests for spdlog while building ArrayFire unit tests ? The answer is no, we don't want to. Hence they are turned off in https://github.com/arrayfire/arrayfire/blob/master/CMakeLists.txt#L140

**Comment by StefanBruens** [comment] 2019-12-04 13:22
And here its is turned on again:
https://github.com/gabime/spdlog/blob/caff7296b162d97e44d6a1cc039adf689cfc02b3/CMakeLists.txt#L28-L31

**Comment by 9prady9** [comment] 2019-12-04 13:29
True, but `add_subdirectory` call on tests folder under spdlog is only done if `SPDLOG_BUILD_TESTING` is set to `ON` - lines 46-48

**Comment by StefanBruens** [comment] 2019-12-04 13:32
Why don't you try it?
```
cmake -DENABLE_TESTING
make all
ctest
```
ENABLE_TESTING turns on SPDLOG_BUILD_TESTING using `cmake_dependent_option`, read the linked fragment.

**Comment by 9prady9** [comment] 2019-12-04 13:35
I do run `ctest` when running all tests, I didn't see spdlog tests being run so far. Infact, our ci jobs run ctest, I am not sure why it being enabled in your tests. What version of cmake are you using ?

**Comment by StefanBruens** [comment] 2019-12-04 14:28
cmake/ctest 3.15.5

**Comment by StefanBruens** [comment] 2019-12-04 14:30
try `cmake help | grep spdlog`. If spdlog-utests appears it is part of the targets, which can only happen when `spdlog/test/CMakeLists.txt` has been processed.

**Comment by 9prady9** [comment] 2019-12-04 14:38
The following is what I see
```
cmake --build . --target help | grep spdlog
extern/spdlog/install/strip: phony
extern/spdlog/install: phony
extern/spdlog/list_install_components: phony
extern/spdlog/rebuild_cache: phony
extern/spdlog/edit_cache: phony
extern/spdlog/package: phony
extern/spdlog/install/local: phony
extern/spdlog/package_source: phony
extern/spdlog/test: phony
spdlog_headers_for_ide: phony
```
I don't see `spdlog-utests` as expected. Try upgrading cmake to 3.16, perhaps it is a bug in cmake and they fixed - I am not sure - I use cmake 3.16, I don't see what you are seeing on your system.

Are you using master branch or v3.6.4 tag ?

**Comment by StefanBruens** [comment] 2019-12-04 14:43
should have been
```
cmake -DENABLE_TESTING=ON
make help | grep spdlog
```

This is arrayfire 3.6.4. (release tarball)
Same happens with cmake 3.16.0

**Comment by 9prady9** [comment] 2019-12-04 14:54
Thats fine, I have tests enabled on my development work trees - I didn't copy paste your command exactly. I don't see utests target on neither master nor v3.6.4. Can you please try our latest master branch.

If you still see utests target even then, we would appreciate if you can create a simple `Dockerfile` that can help recreate the issue on our end reliably as I am unable to on my end at the moment.

**Comment by kriswuollett** [comment] 2020-02-02 00:00
I encounter the `spdlog-utests` issue too with CMake 3.16.3 and the 3.6.4 release tarball. I do notice warnings about policies `CMP0063` and `CMP0077`. Perhaps it is the behavior change and not necessarily a bug on the part of CMake?

I've tried various ways to work around this issue. I don't set any testing-related variables with CMake:

```shellscript
CXXFLAGS=-DOS_LNX cmake -S [...]/src -B [...]/build \
    -DCUDA_TOOLKIT_ROOT_DIR=[...] \
    -DCMAKE_PREFIX_PATH="[...]" \
    -DCMAKE_INSTALL_PREFIX=[...] \
    -DCMAKE_BUILD_TYPE=Release \
    -DAF_BUILD_CPU=OFF \
    -DAF_BUILD_OPENCL=OFF \
    -DAF_BUILD_EXAMPLES=OFF
```

This works properly for me and includes running of `spdlog-utests`:

```shellscript
make -C ${tmp_dir}/build spdlog-utests \
    && make -C ${tmp_dir}/build \
    && sudo ldconfig \
    && make -C ${tmp_dir}/build test
```

This causes a build error, but removes `spdlog-utests` from `ctest`:

```shellscript
make -C ${tmp_dir}/build

# Somehow invokes CMake again, but then fails since spdlog-utests target is removed
make -C ${tmp_dir}/build spdlog-utests

# Runs all tests (spdlog-utests not mentioned)
sudo ldconfig \
    && make -C ${tmp_dir}/build test
```

**Comment by 9prady9** [comment] 2020-02-02 07:06
@kriswuollett Have you tried with latest master branch ?

**Comment by 9prady9** [comment] 2020-02-03 06:47
@kriswuollett @StefanBruens Recently, we [modified the set command for variable to spdlog testing](https://github.com/arrayfire/arrayfire/blob/master/CMakeLists.txt#L157). That removes quite a few spdlog targets from our project's target list. Please try the latest master and let us know how it goes.

Having said that, I still don't observe the exact behavior you guys are experiencing - I don't see any utests target neither in 3.6.4 nor master. 

Also, `ENABLE_TESTING` is not the right cmake variable to enable/disable testing. It is `BUILD_TESTING`, this was the keyword in 3.6.4 and even in latest master branch. Even, spdlog CMake file also uses the same keyword.

@kriswuollett May I know couple of things. 1) why you are doing ldconfig between test runs ? 2) Do you have to manually set OS_LNX variable on your system ? If so, please share the system info.

**Comment by kriswuollett** [comment] 2020-02-03 15:10
@9prady9, sorry didn't get a chance to test yet. I'm running on Ubuntu 18.04.3 LTS with the binary release of CMake installed in `/usr/local/cmake-3.16.3` without the system CMake package installed. I'll try out latest master again, I was skipping it due to a downstream library's tests failing at latest from the variance bias parameter change.

I ran across the `ldconfig` instruction in https://github.com/arrayfire/arrayfire/issues/2618#issuecomment-523822348 because I was trying to figure out why the tests were segfaulting. It probably was due to me building/removing libraries at the system level. I assume it isn't necessary from a clean install.

The `OS_LNX` variable was picked up when reading https://github.com/arrayfire/arrayfire/issues/2373#issuecomment-453890467 since I thought I had a similar issue the last time I was building ArrayFire (a few months ago).

**Comment by kriswuollett** [comment] 2020-02-05 14:42
At master latest I do not have `spdlog-utests` issue. However for the `ldconfig` side issue I did need to run it on a fresh install of Ubuntu and just installing prerequisites noted below, otherwise a handful of tests fail:

* Ubuntu 18.04.4 LTS (newly installed)
* CMake 3.16.3 installed in `/usr/local`
* Installed all recommended / OpenBLAS packages in the [Linux install wiki (current revision)](https://github.com/arrayfire/arrayfire/wiki/Build-Instructions-for-Linux/cda4af51217c6e560653589e3d42d29f62f707b1)
* ArrayFire `2a2d6ff52c7f66dec24caa15a0ee5e9ef1cef1f2` (2020-02-04)
* cuda-drivers 440.33.01-1 package, CUDA 10.1 via `cuda_10.1.243_418.87.00_linux.run` (toolkit & samples only)
* CMake command:

```shellscript
cmake -S [...]/src -B [...]/build \
        -DCUDA_TOOLKIT_ROOT_DIR=[...] \
        -DCMAKE_PREFIX_PATH="[...]" \
        -DCMAKE_INSTALL_PREFIX="[...]" \
        -DCMAKE_BUILD_TYPE=Release \
        -DAF_BUILD_CPU=ON \
        -DAF_BUILD_CUDA=ON \
        -DAF_BUILD_OPENCL=ON \
        -DAF_BUILD_FORGE=ON \
        -DAF_BUILD_EXAMPLES=ON \
        -DBUILD_TESTING=ON
```

**Comment by 9prady9** [comment] 2020-02-05 16:54
@kriswuollett That is good. About the ldconfig problem, not sure if that would cause segfaults - the program should complain about missing shared library object if one is missing. If your program is seg-faulting, then it must be something else. Since you are building from arrayfire source, what does the gdb backtrace look like when the program seg faults ?

**Comment by 9prady9** [comment] 2020-04-08 12:51
Closing since the original issue related to `spdlog-utests` is resolved. @kriswuollett If you are still having issues with ldconfig, please create a new issue with all relevant info - kindly try out the latest release v3.7.1

**Closed by 9prady9** 2020-04-08 12:51 UTC
