### ISSUE TITLE
createWindow segfault on OSX 

### ISSUE THREAD

**Issue by dmjio** [arrayfire/arrayfire#2546] opened 2019-06-19 15:07 UTC
Attempting to create a new window on OSX Darwin segfaults. Installed arrayfire into `/opt/arrayfire` using automated install instructions for OSX.

```c
void test_window () {                                                                                                                                                                        
  af_window window;                                                                                                                                                                          
  af_create_window(&window, 100, 100, "foo");                                                                                                                                                
  af_show(window);                                                                                                                                                                           
} 
```
result:

```
[nix-shell:~/Desktop/arrayfire]$ dist/build/main/main
Segmentation fault: 11
```

Specs: 
  - ArrayFire `3.6.4`

![image](https://user-images.githubusercontent.com/875324/59777115-06dc1080-9282-11e9-8f9b-9abab5d8258f.png)

**Comment by dmjio** [comment] 2019-06-24 14:52
This was my fault, I did not `brew install sdl glfw fontconfig`, etc. Will close once a window is shown...

**Comment by 9prady9** [comment] 2019-06-24 14:59
@dmjio `sdl` is not needed. It is an alternative window toolkit backend for forge. The version of forge used by ArrayFire uses glfw.

**Comment by 9prady9** [comment] 2019-06-24 15:00
Closing since it is not a bug.

**Closed by 9prady9** 2019-06-24 15:00 UTC
