### ISSUE TITLE
Build failure on 32-bit Intel IA32

### ISSUE THREAD

**Issue by andreasbaumann** [arrayfire/arrayfire#2161] opened 2018-05-24 12:02 UTC
```
[  8%] Building CXX object src/backend/cpu/CMakeFiles/afcpu.dir/__/__/api/c/homography.cpp.o
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:33:25: error: non-constant-expression 
cannot be narrowed from type 'unsigned int' to 'dim_t' (aka 'int') in initializer list [-Wc++11-narrowing
]
    dim_t rdims[] = {4, d * 256};
                        ^~~~~~~
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:33:25: note: insert an explicit cast t
o silence this issue
    dim_t rdims[] = {4, d * 256};
                        ^~~~~~~
                        static_cast<dim_t>( )
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:33:25: error: non-constant-expression 
cannot be narrowed from type 'unsigned int' to 'dim_t' (aka 'int') in initializer list [-Wc++11-narrowing
]
    dim_t rdims[] = {4, d * 256};
                        ^~~~~~~
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:83:23: note: in instantiation of funct
ion template specialization 'homography<float>' requested here
            case f32: homography<float >(outH, outInl, x_src, y_src, x_dst, y_dst, htype, inlier_thr, ite
rations);  break;
                      ^
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:33:25: note: insert an explicit cast t
o silence this issue
    dim_t rdims[] = {4, d * 256};
                        ^~~~~~~
                        static_cast<dim_t>( )
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:33:25: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'dim_t' (aka 'int') in initializer list [-Wc++11-narrowing]
    dim_t rdims[] = {4, d * 256};
                        ^~~~~~~
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:84:23: note: in instantiation of function template specialization 'homography<double>' requested here
            case f64: homography<double>(outH, outInl, x_src, y_src, x_dst, y_dst, htype, inlier_thr, iterations);  break;
                      ^
/build/arrayfire/src/arrayfire-full-3.6.0/src/api/c/homography.cpp:33:25: note: insert an explicit cast to silence this issue
    dim_t rdims[] = {4, d * 256};
                        ^~~~~~~
                        static_cast<dim_t>( )
3 errors generated.
make[2]: *** [src/backend/cpu/CMakeFiles/afcpu.dir/build.make:1558: src/backend/cpu/CMakeFiles/afcpu.dir/__/__/api/c/homography.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1213: src/backend/cpu/CMakeFiles/afcpu.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

Is anything but 64-bit Intel supported (also for instance ARM)?

**Comment by 9prady9** [comment] 2018-05-24 13:54
We neither test/build on 32bit architecture nor claim 32bit support. 64bit on the other hand, you should be able to build on any brand, Intel or AMD or anything else - most of our ci jobs uses Intel and AMD. We do test and build on tegra platform which I believe falls under 64bit ARM category. Having said that, I don't think this is related to arch-bit support. Which compiler are you using and which version ? Are you enabling any experimental features and additional flags?

If the above mentioned error is the only one you are having, then you should be able to build after adding some explicit casts in the lines causing the problem - although I am not sure how many such implicit narrow-down statements are present in the current base. It could be just few edits or not.

**Comment by 9prady9** [comment] 2018-05-24 14:05
One more thing, when you are building CUDA backend please make sure to change the `CUDA_HOST_COMPILER` cmake variable to gcc 6 or something that CUDA toolkit supports. I don't think gcc 8/7 are supported.

**Comment by andreasbaumann** [comment] 2018-05-27 07:35
Thanks for all the tips and explanations.

I patched the dim_t casts in https://github.com/archlinux32/packages/tree/master/community/arrayfire.

I also removed testing against OpenCL hardware (i don't own any).

I was able to build and run the CPU tests just fine.

**Comment by 9prady9** [comment] 2018-05-27 08:37
Glad to hear that you were able to fix it with very few edits.

Please do note that at the moment our CPU backend is mainly available for quick prototyping and testing without having to compile CUDA/OpenCL backend which usually takes more time than it's CPU counterpart. We do plan to improve CPU backend performance, although I can't give any specific ETA on that.

I am closing the issue for now as the issue is about an unsupported bit architecture and you are able to build the project with just couple of edits.

**Closed by 9prady9** 2018-05-27 08:37 UTC
