### ISSUE TITLE
Four tests fail | CUDA Backend

### ISSUE THREAD

**Issue by SYnchronYSe** [arrayfire/arrayfire#2534] opened 2019-06-11 09:12 UTC
Hi. I have built AF from source on CUDA backend. Four of my tests failed in the 'make-test' process:

```
98% tests passed, 4 tests failed out of 242

Total Test time (real) = 962.31 sec

The following tests FAILED:
	59 - test_fft_cpu (Failed)
       108 - test_inverse_dense_cuda (Failed)
       155 - test_pinverse_cpu (Failed)
       194 - test_solve_dense_cuda (OTHER_FAULT)
ArrayFire v3.7.0 (CUDA, 64-bit Linux, build c889f36)
Platform: CUDA Toolkit 10.0, Driver: 418.67
[0] GeForce GT 710, 1994 MB, CUDA Compute 3.5
```

When I ran the tests separately, I got the following outputs: 

1. fft_cpu:
```
[==========] 108 tests from 18 test cases ran. (6645 ms total)
[  PASSED  ] 104 tests.
[  FAILED  ] 4 tests, listed below:

arrayfire/test/fft.cpp:835: Failure
VALUE DIFFERS at (0):
Viewing slice (0:5), dims are (513 1 1 1) strides: (1 513 513 513)
                             [0]                     1                     2                     3                    4                    5
     a: {  [(2.06753, -1.09211)] (0.911799, -0.435133) (0.129386, -0.486553) (0.0477646, -1.67922)  (2.08726, -1.79226)  (2.02713, -1.20387) }
a_copy: { [(0.192561, 0.309704)]  (0.996691, 0.487537)  (0.124361, 0.520023)  (0.347054, 0.608346) (0.940295, 0.445576) (0.410995, 0.391992) }
[  FAILED  ] InputsND/FFTC2R.Complex32ToRInputsPreserved/d0_513_d1_1_d2_1_d3_1_even_norm_0_5, where GetParam() = 48-byte object <01-02 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 E0-3F>
[  FAILED  ] InputsND/FFTC2R.Complex32ToRInputsPreserved/d0_1025_d1_1_d2_1_d3_1_even_norm_0_5, where GetParam() = 48-byte object <01-04 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 E0-3F>
[  FAILED  ] InputsND/FFTC2R.Complex64ToRInputsPreserved/d0_513_d1_1_d2_1_d3_1_even_norm_0_5, where GetParam() = 48-byte object <01-02 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 E0-3F>
[  FAILED  ] InputsND/FFTC2R.Complex64ToRInputsPreserved/d0_1025_d1_1_d2_1_d3_1_even_norm_0_5, where GetParam() = 48-byte object <01-04 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 E0-3F>
```

2. inverse_dense_cuda:

```
[==========] 8 tests from 4 test cases ran. (14776 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 7 tests, listed below:

unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function To cuda::kernel::reduce_all(cuda::CParam<T>, bool, double) [with Ti = float; To = float; af_op_t op = (af_op_t)18u]
In file src/backend/cuda/kernel/reduce.hpp:383
CUDA Error (6): the launch timed out and was terminated

In function T af::max(const af::array&) [with T = float]
In file src/api/cpp/reduce.cpp:129" thrown in the test body.
[  FAILED  ] Inverse/0.SquareMultiplePowerOfTwo, where TypeParam = float

unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function void* cuda::MemoryManager::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:149
CUDA Error (6): the launch timed out and was terminated


In function void {anonymous}::initDataArray(void**, const void*, af::dtype, af::source, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:103" thrown in the test body.
[  FAILED  ] Inverse/1.Square, where TypeParam = af::af_cfloat
[  FAILED  ] Inverse/1.SquareMultiplePowerOfTwo, where TypeParam = af::af_cfloat
[  FAILED  ] Inverse/2.Square, where TypeParam = double
[  FAILED  ] Inverse/2.SquareMultiplePowerOfTwo, where TypeParam = double
[  FAILED  ] Inverse/3.Square, where TypeParam = af::af_cdouble
[  FAILED  ] Inverse/3.SquareMultiplePowerOfTwo, where TypeParam = af::af_cdouble
```
(other 6 failed tests were showing similar error messages.)

3. pinverse_cpu:

```
[==========] 38 tests from 5 test cases ran. (11200 ms total)
[  PASSED  ] 37 tests.
[  FAILED  ] 1 test, listed below:
arrayfire/test/pinverse.cpp:161: Failure
VALUE DIFFERS at (1, 1):
Viewing slice (0:6, 1), dims are (640 480 1 1) strides: (1 640 307200 307200)
                       0                 [1]                 2                 3                 4                 5                 6
out: { (561.941 960.709) [(755.826 604.878)] (943.971 262.068) (703.521 256.705) (830.814 12.1375) (450.494 242.139) (352.784 40.7271) }
 in: { (561.941 960.709) [(755.826 604.878)] (943.971 262.068) (703.521 256.705) (830.814 12.1375) (450.494 242.139) (352.784 40.7271) }
  Actual diff: 1.57401469398159e-10
Expected diff: 1.4201166631533368e-10
[  FAILED  ] Pinverse/3.Large, where TypeParam = af::af_cdouble
```
(This one seems okay, as as the error is of order e-11.)

4. solve_dense_cuda:

```
[ RUN      ] Solve/0.SquareMultipleOfTwoLarge
unknown file: Failure
C++ exception with description "ArrayFire Exception (Internal error:998):
In function To cuda::kernel::reduce_all(cuda::CParam<T>, bool, double) [with Ti = float; To = float; af_op_t op = (af_op_t)0u]
In file src/backend/cuda/kernel/reduce.hpp:383
CUDA Error (6): the launch timed out and was terminated


In function T af::sum(const af::array&) [with T = float]
In file src/api/cpp/reduce.cpp:126" thrown in the test body.
[  FAILED  ] Solve/0.SquareMultipleOfTwoLarge, where TypeParam = float (8397 ms)
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function void* cuda::MemoryManager::nativeAlloc(size_t)
In file src/backend/cuda/memory.cpp:149
CUDA Error (6): the launch timed out and was terminated


In function void {anonymous}::initDataArray(void**, const void*, af::dtype, af::source, dim_t, dim_t, dim_t, dim_t)
In file src/api/cpp/array.cpp:103
Aborted (core dumped)
```

Please help me know what gone wrong.

**Comment by 9prady9** [comment] 2019-06-11 09:22
`fft_cpu` bug has already been fixed on master with https://github.com/arrayfire/arrayfire/commit/d910b1c218e5b081fdb23605c516efcbbb16a68e - Please pull latest master

The line `src/backend/cuda/memory.cpp:149` is a `cudaMalloc` call and I think your device ran out of memory. Have you checked your nvidia card's memory usage ? `watch nvidia-smi` (on linux) should show you realtime usage of your GPU.

**Comment by SYnchronYSe** [comment] 2019-06-11 11:47
Thanks. I rebuilt it. Now the last three errors remain. I did 'watch nvidia-smi', but it always stayed in 400-600MB, out of 1993MB.  I even tried 'nvidia-smi -l 1' to watch gpu usage every 1 second. It froze for 4-5 seconds, then printed all the timestamps at once, but none of them were out of memory. Is it possible that the memory overload occurs within 1 second, such that nvidia-smi couldn't capture it?

**Comment by 9prady9** [comment] 2019-06-11 13:05
`test_pinverse_cpu` value difference is acceptable in my opinion given that it is on the order of 10^-11.

We will need some time to reproduce the issue on similar device.

Since you are building from source, can you also please try upgrading CUDA to 10.1 and driver to latest possible.

**Comment by SYnchronYSe** [comment] 2019-06-11 13:08
I'll try with latest CUDA and drivers and revert. Thanks.

**Closed** 2019-06-11 15:28 UTC

**Comment by SYnchronYSe** [comment] 2019-06-30 18:16
I just tested it on a different machine with the following config: 

RAM 4gb
Graphics Nvidia GeForce 920M 2GB
CPU Intel core i3-5005U, 2GHz x 4
Ubuntu 18.04 64bit
Nvidia driver v418.67
Nvidia cuda 10.1

All the tests passed successfully.

**Comment by 9prady9** [comment] 2019-07-08 14:07
@SYnchronYSe I have 430.26 driver and the tests pass using CUDA 10.1. Can you please update the driver to 430.26 for 920M and verify if the tests still fail ?

**Comment by SYnchronYSe** [comment] 2019-07-08 16:42
@9prady9

I'll try it and update you by 10th July.
