### ISSUE TITLE
Exception with OpenCL

### ISSUE THREAD

**Issue by KoldoRamirez** [arrayfire/arrayfire#549] opened 2015-03-30 07:18 UTC
Hello all

Running the simplest programs with afOpenCL.lib I get exception when the program is ended. No problem when using afCPU.lib.

The most basic program is:
``` C++
    try {
		setDevice(0);
		info();
		array a = randu(4,5,2);
    } catch (af::exception& e) {
		printf("Error: %s\n", e.what());
    }
```
Output is:
```
ArrayFire v3.0.beta (OpenCL, 64-bit Windows, build a4a26ce)
[0] INTEL   : Intel(R) HD Graphics 4000
-1- INTEL   : Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
-2- Experimental OpenCL 2.0 CPU Only Platform: Intel(R) Core(TM) i5-3320M CPU @
2.60GHz
```
Exception is:
```
Unhandled exception at 0x000007FED84CBDA1 (igdrcl64.dll) in helloworld_debug.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```
Running full helloworld.cpp demo, exception is slightly different:
```
Unhandled exception at 0x0000000076CBF279 (ntdll.dll) in helloworld_debug.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

**Comment by shehzan10** [comment] 2015-03-30 14:11
Can you please check if this happens in Release mode too?

**Comment by KoldoRamirez** [comment] 2015-03-31 06:52
Hello Shehzan

In Release mode, the exception is very similar:
```
Unhandled exception at 0x000007FEDC1DBDA1 (igdrcl64.dll) in helloworld.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

**Comment by KoldoRamirez** [comment] 2015-04-01 06:24
My system is WIndows 7 64 bits, MSC12 compiler, and ArrayFire binaries have been downloaded on March, 27th.

**Comment by shehzan10** [comment] 2015-04-01 14:00
Thanks for that info.
We are aware of this issue happening on some systems where the program runs correctly all the way through but gives that error right before closing.
We're looking into it and should give an update once we have some concrete info on it.

**Comment by KoldoRamirez** [comment] 2015-04-01 14:02
Thank you. If you want any additional information or check from my side please tell me.

**Comment by 9prady9** [comment] 2015-05-06 19:25
@KoldoRamirez Can you please download the latest nightly and check if the problem is still present.

**Comment by KoldoRamirez** [comment] 2015-05-07 07:41
Hello 9prady9

I have just downloaded the binaries and tried the sample.

Linking afOpenCL and calling deviceprop() and isDoubleAvailable() my system reports three devices:

0. Name 'Intel(R)_HD_Graphics_4000', platform 'OpenCL', toolkit 'Intel(R) OpenCL', compute '1.1', double available 'no'
1. Name 'Quadro_K1000M', platform 'OpenCL', toolkit 'NVIDIA CUDA', compute '1.1' , double available 'yes'
2. Name 'Intel(R)_Core(TM)_i7-3740QM_CPU @ 2.70GHz', platform 'OpenCL', toolkit 'Intel(R) OpenCL', compute '1.1', double available 'yes'

Using either devices 0 or 2 only (the Intel devices), program fails at the end.
However using device 1 only, program works perfectly

Best regards
Koldo

**Comment by 9prady9** [comment] 2015-05-07 15:11
@KoldoRamirez Thank you for sharing the detailed information. Your observation is correct, we are noticing this problem with only Intel devices and only on windows platform. Unfortunately, we didn't get a break at this issue yet, but we are looking into it and will update this issue whenever there is an update from our side.

Regards,
Pradeep.

**Comment by KoldoRamirez** [comment] 2015-05-08 06:28
Thank you 9prady9. I am sure you will solve it. 
It is an issue for my as in my company all laptops have Intel and just a few have Nvidia GPUs.

**Closed** 2015-05-27 00:51 UTC
Labels: OpenCL, Windows

**Comment by 9prady9** [comment] 2015-05-27 00:54
@KoldoRamirez Can you test your code now with latest devel ?

**Comment by KoldoRamirez** [comment] 2015-05-27 10:55
Sorry, the exception remains: "Runtime Error! R6025 - pure virtual function call"

Library used from last binaries.

info() reports this:
ArrayFire v3.0.beta (OpenCL, 64-bit Windows, build a4a26ce)
[0] INTEL   : Intel(R) HD Graphics 4000
-1- INTEL   : Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
-2- Experimental OpenCL 2.0 CPU Only Platform: Intel(R) Core(TM) i5-3320M CPU @
2.60GHz

**Comment by pavanky** [comment] 2015-05-27 13:14
HI

This is using the latest commit from master branch. We were talking about the devel branch. Can you give that a shot ?

**Comment by pavanky** [comment] 2015-05-27 13:18
Or are you using the installer from the website to check this ?

**Comment by KoldoRamirez** [comment] 2015-05-28 06:25
Hello Pavan. I am checking this with the installer.

**Comment by pavanky** [comment] 2015-05-28 07:02
We have not updated the installer on the website yet. This is currently fixed in the devel branch of our repo

**Comment by KoldoRamirez** [comment] 2015-05-29 06:29
Uups. I will try it this weekend.

**Comment by KoldoRamirez** [comment] 2015-05-31 19:01
Sorry. For now I cannot compile OpenCL version (CPU version yes). Opened a question in Google Groupd here (https://groups.google.com/forum/#!topic/arrayfire-users/oRafHz8LL44)

**Comment by KoldoRamirez** [comment] 2015-06-05 07:47
Excellent. Problem solved. Thank you!

**Comment by samp0** [comment] 2017-04-07 12:26
Hi, I'm facing very similar issue. I'm using ArrayFire 3.4.2 release on Windows7. When running your unified/basic example (http://arrayfire.org/docs/unified_2basic_8cpp-example.htm) I get the exact same  "Runtime Error! R6025 - pure virtual function call" error during application exit.

Application prints my OpenCL backend info as:

Trying OpenCL Backend
ArrayFire v3.4.2 (OpenCL, 64-bit Windows, build 2da9967)
-0- INTEL   : Intel(R) HD Graphics 4600, 1297 MB
-1- INTEL   : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 24450 MB
[2] Experimental OpenCL 2.1 CPU Only Platform: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 24450 MB

If I call setDevice(0); i.e. force the first one from the list, it doesn't give me the pure virtual call but crashes on exit nevertheless. Devices with index 1 and 2 also give the abovementioned pure virtual function call exception. So it looks like the issue is still present in 3.4.2.
