### ISSUE TITLE
Access violation on Windows+OpenCL when graphics is enabled

### ISSUE THREAD

**Issue by paolobardella** [arrayfire/arrayfire#1175] opened 2015-12-18 17:27 UTC
On Windows 8.1 64bit, Visual Studio 2013/2015, Open CL on ATI card, I get an Access Violation Exception with the simple code 

```
try {
        setDevice(0);
        info();
        array a = randu(4, 5, 2);
    }
    catch (af::exception& e) {
        printf("Error: %s\n", e.what());
    }
```

The error occurs both in Debug and Release mode, at the application exit.
![accessviolation](https://cloud.githubusercontent.com/assets/13315243/11902832/f613cad0-a5b4-11e5-9359-5f2abb1496b5.png)

**Comment by shehzan10** [comment] 2016-04-15 17:06
It looks like this is happening when destroying graphics resources. Can you try setting the environment variable `AF_DISABLE_GRAPHICS=1` and try it again?

**Comment by PeterMJ** [comment] 2017-07-26 10:29
Although this is an old ticket, I am also getting this issue with window 10 MSVC 2017. info() prints:

> ArrayFire v3.5.0 (OpenCL, 64-bit Windows, build 05999f3)
> -0- INTEL: Intel(R) HD Graphics 530, 3214 MB
> [1] INTEL: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, 8056 MB

The stack trace for the error is:

> 1  NtUserWaitMessage                                                      win32u                0x7ffe25a91204 
2  DwmGetDxSharedSurface                                                  USER32                0x7ffe26ace25d 
3  DwmGetDxSharedSurface                                                  USER32                0x7ffe26ace0cf 
4  SoftModalMessageBox                                                    USER32                0x7ffe26ad004a 
5  MessageBoxTimeoutW                                                     USER32                0x7ffe26acf7c0 
6  MessageBoxTimeoutW                                                     USER32                0x7ffe26acf5dc 
7  MessageBoxW                                                            USER32                0x7ffe26b1009e 
8  RegisterGlobalAtExitNotification                                       intelocl64            0x7ffdeec88d12 
9  RegisterGlobalAtExitNotification                                       intelocl64            0x7ffdeec7f056 
10 RegisterGlobalAtExitNotification                                       intelocl64            0x7ffdeec746fe 
11 clWaitForEvents                                                        intelocl64            0x7ffdeebda0e7 
12 clReleaseMemObject                                                     intelocl64            0x7ffdeebcfb25 
13 opencl::MemoryManager::nativeFree                                      memory.cpp        180 0x7ffde6f00aea 
14 common::MemoryManager<opencl::MemoryManager>::cleanDeviceMemoryManager memorymanager.hpp 105 0x7ffde6a9feb0 
15 opencl::MemoryManager::~MemoryManager                                  memory.cpp        156 0x7ffde6efdbf9 
16 opencl::MemoryManager::`scalar deleting destructor'                    afopencl              0x7ffde6efe104 
17 opencl::DeviceManager::~DeviceManager                                  platform.cpp      767 0x7ffde6a9c195 
18 o__execute_onexit_table                                                ucrtbase              0x7ffe25bb8673 
19 register_onexit_function                                               ucrtbase              0x7ffe25bbc127 
20 execute_onexit_table                                                   ucrtbase              0x7ffe25bb877e 
21 dllmain_crt_process_detach                                             dll_dllmain.cpp   109 0x7ffde81e1466 
22 dllmain_dispatch                                                       dll_dllmain.cpp   207 0x7ffde81e155c 
23 RtlDeactivateActivationContextUnsafeFast                               ntdll                 0x7ffe2935485f 
24 LdrShutdownProcess                                                     ntdll                 0x7ffe2937d43c 
25 RtlExitUserProcess                                                     ntdll                 0x7ffe2937d2f4 
26 FatalExit                                                              KERNEL32              0x7ffe26c6c0da 
27 wassert                                                                ucrtbased             0x7ffdeedf7c2a 
28 wassert                                                                ucrtbased             0x7ffdeedf7be9 
29 exit                                                                   ucrtbased             0x7ffdeedf7f26 
30 __scrt_common_main_seh                                                 exe_common.inl    268 0x7ff72ea73530 
31 __scrt_common_main                                                     exe_common.inl    302 0x7ff72ea733de 
32 mainCRTStartup                                                         exe_main.cpp      17  0x7ff72ea73679 
33 BaseThreadInitThunk                                                    KERNEL32              0x7ffe26c62774 
34 RtlUserThreadStart                                                     ntdll                 0x7ffe293a0d51 

The error text says:
> R6025 
> - Pure virtual function call

I have added the AF_DISABLE_GRAPHICS=1 to the run environment, and the crash on exit still occurs.

**Comment by 9prady9** [comment] 2020-04-08 12:26
We have fixed couple of bugs related to use of ArrayFire on headless systems, cleaned up forge management and fixed order of destruction of device manager class in all backends. This issue may have been fixed in the later releases, @paolobardella Can you please verify the examples with latest release - v3.7.1

**Comment by 9prady9** [comment] 2020-04-13 11:44
> We have fixed couple of bugs related to use of ArrayFire on headless systems, cleaned up forge management and fixed order of destruction of device manager class in all backends. This issue may have been fixed in the later releases, @paolobardella Can you please verify the examples with latest release - v3.7.1

@PeterMJ Can you also please check latest release and let us know if the problem is resolved or not.

**Comment by 9prady9** [comment] 2020-04-18 07:58
Closing due to inactivity.

**Closed by 9prady9** 2020-04-18 07:58 UTC
Labels: Windows, graphics, unconfirmed
