### ISSUE TITLE
3.4.2 doesn't compile

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#1688] opened 2016-12-22 08:00 UTC
Getting this during compilation:

```
/build/arrayfire/src/arrayfire-full-3.4.2/src/api/c/hist.cpp: In function 'forge::Chart* setup_histogram(const forge::Window*, af_array, double, double, const af_cell*)':
/build/arrayfire/src/arrayfire-full-3.4.2/src/api/c/hist.cpp:54:16: error: 'class forge::Chart' has no member named 'getAxesLimits'; did you mean 'setAxesLimits'?
         chart->getAxesLimits(&xMin, &xMax, &yMin, &yMax);
                ^~~~~~~~~~~~~
make[2]: *** [src/backend/cpu/CMakeFiles/afcpu.dir/build.make:2847: src/backend/cpu/CMakeFiles/afcpu.dir/__/__/api/c/hist.cpp.o] Error 1
```

gcc 6.2.1 on Arch Linux.

Weirdly enough, the compiler knows about `setAxesLimits` but not about `getAxesLimits` so probably this is not an error on my side.

**Comment by 9prady9** [comment] 2016-12-22 08:41
@svenstaro Because of some changes in the upstream graphics library, we had to change few things internally and what you are seeing is the because of that. do `rm -rf <build_foler>/third_party/forge` to remove the forge related external project builds and try building the code again. If that doesn't work out, just start with a clean build. I am sure one of them will get you going.

**Comment by 9prady9** [comment] 2016-12-22 13:51
@svenstaro Did you get a chance to revisit this problem ? If its not a problem anymore, please close the issue.

**Comment by pavanky** [comment] 2016-12-22 13:59
@9prady9 He is the one that packages arrayfire for archlinux. I don't think the error is happening because of a left over build directory.

@svenstaro  The error sounds like it is because of `PKGCONFIG` pointing to older version of forge. Can you upgrade forge to 0.9.2 and try again?

**Comment by 9prady9** [comment] 2016-12-22 14:05
@pavanky But, I got the exact same error message after pulling latest devel and doing a clean build fixed it.

**Comment by svenstaro** [comment] 2016-12-22 16:48
With forge 0.9.2 I get:

```
Scanning dependencies of target cuda_ptx_headers_bin_target
make[2]: *** No rule to make target 'src/backend/cuda/cuda_compile_ptx_generated_arith.cu.ptx', needed by 'src/backend/cuda/arith.ptx'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:617: src/backend/cuda/CMakeFiles/cuda_ptx_headers_bin_target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by shehzan10** [comment] 2016-12-22 16:58
@9prady9 are you getting the same error as well? Also if you are, did you install CUDA using package manager or installer? I am unable to reproduce this error.

**Comment by svenstaro** [comment] 2016-12-22 17:06
Using cuda 8.0.44 from Arch, by the way.

**Comment by pavanky** [comment] 2016-12-22 17:25
Hmm I was building the hotfixes branch on arrayfire just a couple of days ago. Let me check if forge is an issue.

**Comment by shehzan10** [comment] 2016-12-22 17:34
Looks like its happening on Windows too.

**Comment by pavanky** [comment] 2016-12-22 17:48
@shehzan10 @svenstaro looks like it is a problem with cmake 3.7. 3.6 works fine.

 My desktop was still on 3.6 so it was building fine. Upgrading to 3.7 breaks. I'll see if there is an easy fix for this.

**Comment by shehzan10** [comment] 2016-12-22 17:50
@grzegorz-gutowski Are you using CMake 3.7 as well?

**Comment by grzegorz-gutowski** [comment] 2016-12-22 17:52
@shehzan10 Yes. I'll downgrade cmake to 3.6.3 and check what happens.

**Comment by pavanky** [comment] 2016-12-22 17:55
@shehzan10 I am assuming this is because 3.7 no longer generates ptx files in the format like `cuda_compile_ptx_generated_$NAME.cu.ptx`

I was relying on an undocumented feature when I added that into the build process.

**Comment by shehzan10** [comment] 2016-12-22 17:56
I can look into it and see whats going on.

**Comment by grzegorz-gutowski** [comment] 2016-12-22 18:00
I confirm that downgrading cmake helped with my build.

**Comment by 9prady9** [comment] 2016-12-23 00:17
@shehzan10 I got the second error he reported as well which is why i tried a clean build. As in, i removed all the contents of build folder and started from scratch.

**Comment by 9prady9** [comment] 2016-12-23 00:18
I am using CMake 3.5.

**Comment by pavanky** [comment] 2016-12-23 03:24
@svenstaro since the release is already out and only affects newer versions of cmake, I don't think a new release will happen.

Is there any chance you can package it using this patch: 
https://github.com/arrayfire/arrayfire/pull/1689/commits/13c484e10537b52bcd012e6850520659769cece6

**Comment by bitstormGER** [comment] 2016-12-28 10:45
I have just compiled on arch with gcc 6.2.1 - compilation works fine with cmake-3.6 from AUR but not with cmake 3.7 from extra

**Comment by pavanky** [comment] 2016-12-28 16:47
@bitstormGER I am going to update the aur with the patch.

**Comment by pavanky** [comment] 2016-12-28 16:53
@bitstormGER done. Not sure if you are aware, but you can downgrade archlinux packages if you did not delete your cache. You do not need to install cmake-3.6 from aur.

**Comment by pavanky** [comment] 2016-12-28 17:02
@bitstormGER I updated the aur package to v3.4.2 and re-enabled graphics support. You may want to upgrade.

**Comment by shehzan10** [comment] 2016-12-29 15:49
Fixed by #1689

**Closed by shehzan10** 2016-12-29 15:49 UTC
Labels: build

**Comment by navidR** [comment] 2017-05-17 16:02
Please backport this patch to latest stable version : v3.4.2 branch. Is it possible ?

**Comment by pavanky** [comment] 2017-05-17 16:11
@navidR There should be a new release in a few days.
