### ISSUE TITLE
How to reduce time to set image for rendering using ArrayFire Window?

### ISSUE THREAD

**Issue by krish021195** [arrayfire/arrayfire#2642] opened 2019-09-13 07:28 UTC
Hi,

Trying to display using ArrayFire window. It takes almost 10ms to display a 1080p RGB image. 

window_arrayfire.image(frame); // frame - 1080p RGB Array 

How do i reduce the time taken to set the image to af::window?

Thanks

**Comment by 9prady9** [comment] 2019-09-13 09:28
How are you timing the code ? Can you also please share a stand alone minimal working example that can show this behavior.

**Comment by krish021195** [comment] 2019-09-13 10:57
code :  
`               timer start1 = timer::start();
		while(!window_arrayfire.close())
		{		
			window_arrayfire.image(frame,"display rgb");
			printf("processing time : %g\n\n\n",timer::stop(start1));
			start1 = timer::start();
		}
`

Details,
 1) arrayfire version - 3.6.4
 2) cuda 10.0
 3) Nvidia Jetson Xavier,
         GPU max clock rate - 1500MHz
         Memory clock rate - 1377GHz

Thanks

**Comment by 9prady9** [comment] 2019-09-13 12:15
Can you please add the call `af::sync()` before you start the timer so that rendering by itself is being timed.

**Comment by krish021195** [comment] 2019-09-13 12:39
Hi,

I have added the af::sync() before starting the timer , even then it takes the same time as before to set the image.

I also see that the time varies depending on the refresh rate of the monitor. The window.image() api seems to be a blocking call. 

Thanks

**Comment by 9prady9** [comment] 2019-09-13 12:42
Can you come online on slack for quick exchange of messages ? https://arrayfire-org.slack.com/messages/C6M9AEJTB

Unless the Interop is not working due to which OpenGL buffer is being filled using fallback approach - via CPU, the image API is an asynchronous call in CUDA backend.

**Comment by krish021195** [comment] 2019-09-13 13:05
Hi,

I am not having access to this workspace. Can you send me the invite? or we could have quick exchange of messages on skype if possible

Thanks

**Comment by 9prady9** [comment] 2019-09-13 13:07
Sorry about that, here's the invite link

https://join.slack.com/t/arrayfire-org/shared_invite/MjI4MjIzMDMzMTczLTE1MDI5ODg4NzYtN2QwNGE3ODA5OQ

**Comment by 9prady9** [comment] 2019-09-17 11:09
@krish021195 As per discussion we had on Slack, the render times are increasing only when you are manually changing your display's refresh rate. Therefore, it is not exactly a rendering-latency issue as I originally thought and must be related to refresh rate settings and driver/hardware.

As mentioned in [GLFW documentation](https://www.glfw.org/docs/latest/group__context.html#ga6d4e0cdf151b5e579bd67f13202994ed) , there are a range of situations where `glfwSwapInterval` call isn't always honored by drivers/hardware. Having said that, forge(ArrayFire's graphics upstream) doesn't change swap interval and leaves to the defaults whatever they may be - doesn't need to 0 always.

If exposing swap interval API helps your use case in any way, that should be done in https://github.com/arrayfire/forge and later exposed/utilized from ArrayFire.

I am closing the issue since the issue doesn't originate in ArrayFire's code base. Feel free to open the issue on https://github.com/arrayfire/forge with more details (minimum working example, I think this can be reproduced without ArrayFire also).

Thank you.

**Closed by 9prady9** 2019-09-17 11:09 UTC
