### ISSUE TITLE
Memory leak when chaining rows() and cols()

### ISSUE THREAD

**Issue by damienfir** [arrayfire/arrayfire#1927] opened 2017-09-13 10:19 UTC
When chaining the rows() and cols() function to get a sub region of an array, ArrayFire creates 2 or 3 additional buffers locked by ArrayFire that are not release by the GC :
```
array A(100,100);
return A.cols(2, end-2).rows(2, end-2);
```

This is fixed by separating the functions into two steps:
```
array A(100,100);
A = A.cols(2, end-2);
return A.rows(2, end-2);
```

Device info:
```
ArrayFire v3.5.0 (CUDA, 64-bit Linux, build 05999f3)
Platform: CUDA Toolkit 8, Driver: 375.66
[0] GeForce GTX 1080, 8112 MB, CUDA Compute 6.1
```

**Comment by 9prady9** [comment] 2017-09-13 12:27
@damienfir There is a fix for this problem in 3.5.1 release. We are soon going to release this fix release. Here is the commit that should fix this https://github.com/arrayfire/arrayfire/commit/4684020f5cbf36549dc07ff4000c9f45e8f8e05f I will leave this issue open until we do 3.5.1 release.

**Comment by pavanky** [comment] 2017-09-13 16:05
@9prady9 We are closing issues as soon as they are merged into the appropriate branch. No reason to keep this open. There are identical issues that have been closed.

**Closed by pavanky** 2017-09-13 16:05 UTC

**Comment by pavanky** [comment] 2017-09-13 16:07
Duplicate of https://github.com/arrayfire/arrayfire/issues/1867, fixed in https://github.com/arrayfire/arrayfire/pull/1879

**Comment by 9prady9** [comment] 2017-09-13 17:28
I was aware that there was similar issue reported in the past, but I couldn't find #1867 as I was searching for terms `chainging`, `cascading` and `indexing`, hence left this one open. I was hoping either you or Umar would close this out once you link the duplicate here :smile:
