### ISSUE TITLE
cpp version of constant is not in correct group in documentation

### ISSUE THREAD

**Issue by 9prady9** [arrayfire/arrayfire#834] opened 2015-06-18 19:13 UTC
http://www.arrayfire.com/docs/group__data__func__constant.htm

Constant function group in the documentation doesn't show cpp interface.

**Comment by pavanky** [comment] 2015-06-18 20:15
Duplicate of https://github.com/arrayfire/arrayfire/issues/824

**Closed by pavanky** 2015-06-18 20:15 UTC
Labels: bug, Documentation
