### ISSUE TITLE
Invalid checksum for BoostCompute

### ISSUE THREAD

**Issue by Brainiarc7** [arrayfire/arrayfire#1348] opened 2016-03-18 01:53 UTC
See build log:

-- Boost version: 1.60.0
-- BoostCompute...
--   getting https://github.com/boostorg/compute/archive/v0.5.tar.gz
--   validating /tmp/nix-build-arrayfire-3.3.3.drv-0/build/third_party/compute-0.5.tar.gz
CMake Warning at CMakeModules/build_boost_compute.cmake:47 (MESSAGE):
  /tmp/nix-build-arrayfire-3.3.3.drv-0/build/third_party/compute-0.5.tar.gz:
  Invalid check sum d41d8cd98f00b204e9800998ecf8427e.  Expected was
  69a52598ac539d3b7f6005a3dd2b6f58
Call Stack (most recent call first):
  src/backend/opencl/CMakeLists.txt:91 (INCLUDE)

Currently building the package version from the hotfix-3.2.2 branch.

**Comment by shehzan10** [comment] 2016-03-18 02:06
`d41d8cd98f00b204e9800998ecf8427e` is the checksum for an empty file, ie `touch empty.txt` will give that checksum.
The primary mode of download is using CMake's File Download. However, this is known to fail on some systems and return the specified checksum. So we added a fallback using wget. [Here is the relevant code](https://github.com/arrayfire/arrayfire/blob/hotfix-3.2.2/CMakeModules/build_boost_compute.cmake#L44-L57).
So the question is, do you have wget installed? To debug, you can add more verbosity to those lines linked above.
Also, I don't see any message about wget from lines [49](https://github.com/arrayfire/arrayfire/blob/hotfix-3.2.2/CMakeModules/build_boost_compute.cmake#L49),  [53](https://github.com/arrayfire/arrayfire/blob/hotfix-3.2.2/CMakeModules/build_boost_compute.cmake#L53),  [55](https://github.com/arrayfire/arrayfire/blob/hotfix-3.2.2/CMakeModules/build_boost_compute.cmake#L55).

Can you paste the entire log?

**Comment by Brainiarc7** [comment] 2016-03-18 02:07
You can pull in the correct checksum from here: https://github.com/Brainiarc7/arrayfire/blob/devel/CMakeModules/build_boost_compute.cmake

**Comment by Brainiarc7** [comment] 2016-03-18 02:07
Oh, sorry, early reply.

Let me add wget as an input and retest.

**Comment by Brainiarc7** [comment] 2016-03-18 02:14
Here's the entire log:

`phase `unpack' succeeded after 0.1 seconds
starting phase `patch-usr-bin-file'
phase `patch-usr-bin-file' succeeded after 0.0 seconds
starting phase `patch-source-shebangs'
patch-shebang: ./CMakeModules/osx_install/cpu_scripts/postinstall: changing `/bin/bash' to `/gnu/store/x8dmdlrn5qn0wrbcnngj55y3ab73h0pp-bash-4.3.42/bin/bash'
patch-shebang: ./CMakeModules/osx_install/cuda_scripts/postinstall: changing `/bin/bash' to `/gnu/store/x8dmdlrn5qn0wrbcnngj55y3ab73h0pp-bash-4.3.42/bin/bash'
patch-shebang: ./CMakeModules/osx_install/opencl_scripts/postinstall: changing `/bin/bash' to `/gnu/store/x8dmdlrn5qn0wrbcnngj55y3ab73h0pp-bash-4.3.42/bin/bash'
phase `patch-source-shebangs' succeeded after 0.1 seconds
starting phase `configure'
source directory: "/tmp/nix-build-arrayfire-3.3.3.drv-0/source" (relative from build: "../source")
build directory: "/tmp/nix-build-arrayfire-3.3.3.drv-0/build"
running 'cmake' with arguments ("../source" "-DCMAKE_BUILD_TYPE=RelWithDebInfo" "-DCMAKE_INSTALL_PREFIX=/gnu/store/baafcg2j7s6d1zkzf5p9mh9pjfhvh254-arrayfire-3.3.3" "-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE" "-DCMAKE_INSTALL_RPATH=/gnu/store/baafcg2j7s6d1zkzf5p9mh9pjfhvh254-arrayfire-3.3.3/lib" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DBUILD_OPENCL=ON" "-DBUILD_GRAPHICS=OFF")
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /gnu/store/pg8nnqprjxgwhwiyh8nhbphzj53ax77i-gcc-4.9.3/bin/gcc
-- Check for working C compiler: /gnu/store/pg8nnqprjxgwhwiyh8nhbphzj53ax77i-gcc-4.9.3/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /gnu/store/pg8nnqprjxgwhwiyh8nhbphzj53ax77i-gcc-4.9.3/bin/c++
-- Check for working CXX compiler: /gnu/store/pg8nnqprjxgwhwiyh8nhbphzj53ax77i-gcc-4.9.3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- MIN_BUILD_TIME IS OFF
-- Using Dynamic FreeImage Lib
-- Found FREEIMAGE: /gnu/store/yf9x5vg5awqaa8g3m8zg9d9rz2ll6i9f-freeimage-3.17.0/include  
-- Using FreeImage library /gnu/store/yf9x5vg5awqaa8g3m8zg9d9rz2ll6i9f-freeimage-3.17.0/lib/libfreeimage.so
fatal: Not a git repository (or any of the parent directories): .git
-- No git. Setting hash to default
-- Found PkgConfig: /gnu/store/nqh64v4dnm0bv9r1c1r9rdvl72licxp3-pkg-config-0.29/bin/pkg-config (found version "0.29") 
-- checking for module 'cblas'
--   package 'cblas' not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_rt]
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Includes found
-- Looking for cblas_dgemm
-- Looking for cblas_dgemm - found
-- CBLAS Symbols FOUND
-- CBLAS library found
-- Using CBLAS Library: /gnu/store/697vf7zj4in48ixh2k2wcbwda8cr2nf0-atlas-3.10.2/lib/libcblas.a;/gnu/store/697vf7zj4in48ixh2k2wcbwda8cr2nf0-atlas-3.10.2/lib/libatlas.a
-- Found FFTW: /gnu/store/4azwr0cfqklc2jwyr7wddg341f5m1iha-fftw-3.3.4/include  
-- FFTW Found ? TRUE
-- FFTW Library: /gnu/store/4azwr0cfqklc2jwyr7wddg341f5m1iha-fftw-3.3.4/lib/libfftw3.so;/gnu/store/7vyf121h26yjvj2z536ls3ncrzs304r2-fftwf-3.3.4/lib/libfftw3f.so
-- Could NOT find LAPACK (missing:  LAPACK_INCLUDE_DIR) 
CMake Warning at src/backend/cpu/CMakeLists.txt:56 (MESSAGE):
  LAPACK not found.  Functionality will be disabled


-- threads submodule unavailable. Updating submodules.
fatal: Not a git repository (or any of the parent directories): .git
-- Found OpenCL: /gnu/store/c5m06c75hqkxym7rz23xdw4dq4rgi8pp-ocl-icd-2.2.9/lib/libOpenCL.so (found version "2.0") 
-- Could NOT find LAPACK (missing:  LAPACK_INCLUDE_DIR) 
CMake Warning at src/backend/opencl/CMakeLists.txt:38 (MESSAGE):
  LAPACK not found.  Functionality will be disabled


-- Boost version: 1.60.0
-- BoostCompute...
--   getting https://github.com/boostorg/compute/archive/v0.5.tar.gz
--   validating /tmp/nix-build-arrayfire-3.3.3.drv-0/build/third_party/compute-0.5.tar.gz
CMake Warning at CMakeModules/build_boost_compute.cmake:47 (MESSAGE):
  /tmp/nix-build-arrayfire-3.3.3.drv-0/build/third_party/compute-0.5.tar.gz:
  Invalid check sum d41d8cd98f00b204e9800998ecf8427e.  Expected was
  69a52598ac539d3b7f6005a3dd2b6f58
Call Stack (most recent call first):
  src/backend/opencl/CMakeLists.txt:91 (INCLUDE)


-- Trying wget https://github.com/boostorg/compute/archive/v0.5.tar.gz
--2016-03-18 02:11:36--  https://github.com/boostorg/compute/archive/v0.5.tar.gz
Resolving github.com (github.com)... failed: Name or service not known.
wget: unable to resolve host address ?github.com?
CMake Error at CMakeModules/build_boost_compute.cmake:53 (MESSAGE):
  /tmp/nix-build-arrayfire-3.3.3.drv-0/build/third_party/compute-0.5.tar.gz:
  Invalid check sum d41d8cd98f00b204e9800998ecf8427e.  Expected was
  69a52598ac539d3b7f6005a3dd2b6f58
Call Stack (most recent call first):
  src/backend/opencl/CMakeLists.txt:91 (INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/tmp/nix-build-arrayfire-3.3.3.drv-0/build/CMakeFiles/CMakeOutput.log".
phase `configure' failed after 2.8 seconds
builder for `/gnu/store/m4fxfia1sriw3c48fh61s59bfc3zi2rk-arrayfire-3.3.3.drv' failed with exit code 1
@ build-failed /gnu/store/m4fxfia1sriw3c48fh61s59bfc3zi2rk-arrayfire-3.3.3.drv - 1 builder for `/gnu/store/m4fxfia1sriw3c48fh61s59bfc3zi2rk-arrayfire-3.3.3.drv' failed with exit code 1
guix build: error: build failed: build of `/gnu/store/m4fxfia1sriw3c48fh61s59bfc3zi2rk-arrayfire-3.3.3.drv' failed
`

**Comment by shehzan10** [comment] 2016-03-18 02:16
> -- Trying wget https://github.com/boostorg/compute/archive/v0.5.tar.gz
> --2016-03-18 02:11:36-- https://github.com/boostorg/compute/archive/v0.5.tar.gz
> Resolving github.com (github.com)... failed: Name or service not known.
> wget: unable to resolve host address ?github.com?
> CMake Error at CMakeModules/build_boost_compute.cmake:53 (MESSAGE):
> /tmp/nix-build-arrayfire-3.3.3.drv-0/build/third_party/compute-0.5.tar.gz:
> Invalid check sum d41d8cd98f00b204e9800998ecf8427e. Expected was
> 69a52598ac539d3b7f6005a3dd2b6f58
> Call Stack (most recent call first):
> src/backend/opencl/CMakeLists.txt:91 (INCLUDE)

So this is where wget is failing. It's unable to resolve github.com, which is the root cause of failure. Why wget is failing, that I cannot say.

**Comment by Brainiarc7** [comment] 2016-03-18 02:17
Yes.

Failing within GNU Guix, and passing outside the build system.

**Comment by pavanky** [comment] 2016-03-18 02:26
Does GNU GUIX build system support downloading from the internet at build time ?

**Comment by Brainiarc7** [comment] 2016-03-18 03:33
@pavanky yes, it does.

In this case, though, it fails. Badly.

**Comment by Brainiarc7** [comment] 2016-03-18 15:10
I have figured out the problem, in part, at least.

When fetching Arrayfire's source code via git, it also requires fetching extras via git submodules.
At the moment, I'm failing to dom so within Guix and this is why the configuration stage fails.
See my scheme file here for more details:

https://github.com/Brainiarc7/guix-bioinformatics/blob/master/gn/packages/arrayfire.scm

Maybe someone can try hacking it up in GNU Guix.

**Comment by shehzan10** [comment] 2016-03-18 15:14
We provide a git-less source package that includes the submodules with all our releases. You can find it under the [github releases section](https://github.com/arrayfire/arrayfire/releases). Quick note, download the link from arrayfire.com rather than the tar-balls generated by github. The github generated tarballs do not include submodules.

The one caveat is that we do not ship external dependencies like clBLAS, clFFT, Boost.Compute with this source package. So if you just need submodules and not the external dependencies, the source tar balls should work for you.

**Comment by Brainiarc7** [comment] 2016-03-18 15:22
Thanks a lot for the clarification.

**Comment by Brainiarc7** [comment] 2016-03-18 18:28
From the GNU Guix developers' input on the same:

"In Guix, builds are performed in an isolated container where there is
*no* external network access.  It must be this way because otherwise
builds would be non-deterministic. The only exception is for "fixed
output derivations", whose checksum is known in advance, which
wouldn't be the case here.  So, the problem lies with Arrayfire's
build system.  A build system really shouldn't download from the net.
It should use what the system has provided for it.  In my experience,
build systems that try to download from the net usually try to find
something to use locally first.  Without knowing anything beyond the
log you've shown me, I would guess that you need to package
BoostCompute first and provide that as an input to Arrayfire.
Hopefully then it won't try to download it.

Hope this helps!

- Dave".

Seems I'll have to take up on the following tasks:

1. Clean up the build system and remove references to the external dependencies
2. Port the specified external dependencies to GNU Guix so they can be used as inputs.

This should result in a self-contained build system that does not try to download any dependencies at the configure stage.

Current progress:

https://github.com/Brainiarc7/guix-bioinformatics/blob/master/gn/packages/arrayfire.scm

**Comment by pavanky** [comment] 2016-03-18 18:44
@Brainiarc7 The problem is not with arrayfire's build system. We only download boost compute if it is not available on the system. Ideally the package should be packaged with the distro (like Debian and Gentoo were doing). So for boost compute you either begin packaging it for GNU GUIX or wait until it is part of the official boost package from Boost 1.62.

However that will not solve the issue with the remaining dependencies (clBLAS and clFFT). You should look into packaging the arrayfire's dependencies before you go ahead with packaging arrayfire.

I am closing the issue because the solution is clear.

**Closed by pavanky** 2016-03-18 18:44 UTC
Labels: build, OpenCL

**Comment by Brainiarc7** [comment] 2016-03-18 18:58
Ok, thanks.
